(function(g){var window=this;'use strict';var tk=function(K){K.publish("cardstatechange",K.v1()&&K.i5()?1:0)},Ak=function(K,R){var f=g.Xp(R),V=f?R:arguments;
for(f=f?0:1;f<V.length;f++){if(K==null)return;K=K[V[f]]}return K},Yhz=function(K){var R=g.hQ(K);
K=g.i6(K);return new g.Rs(R.x,R.y,K.width,K.height)},mdS=function(K,R,f){var V=V===void 0?{}:V;
var D;return D=g.We(K,R,function(){g.tq(D);f.apply(K,arguments)},V)},B0=function(K){K=g.n8(K);
delete Jk[K];g.ZL(Jk)&&ZK&&ZK.stop()},uli=function(){ZK||(ZK=new g.CW(function(){GB$()},20));
var K=ZK;K.isActive()||K.start()},GB$=function(){var K=g.OS();
g.T2(Jk,function(R){sK_(R,K)});
g.ZL(Jk)||uli()},XS=function(K,R,f,V){g.hF.call(this);
if(!Array.isArray(K)||!Array.isArray(R))throw Error("Start and end parameters must be arrays");if(K.length!=R.length)throw Error("Start and end points must be the same length");this.K=K;this.N=R;this.duration=f;this.B=V;this.coords=[];this.progress=this.T=0;this.J=null},sK_=function(K,R){R<K.startTime&&(K.endTime=R+K.endTime-K.startTime,K.startTime=R);
K.progress=(R-K.startTime)/(K.endTime-K.startTime);K.progress>1&&(K.progress=1);K.T=1E3/(R-K.J);K.J=R;CTS(K,K.progress);K.progress==1?(K.U=0,B0(K),K.onFinish(),K.Y0()):K.isPlaying()&&K.A7()},CTS=function(K,R){typeof K.B==="function"&&(R=K.B(R));
K.coords=Array(K.K.length);for(var f=0;f<K.K.length;f++)K.coords[f]=(K.N[f]-K.K[f])*R+K.K[f]},e_S=function(K,R){g.fo.call(this,K);
this.coords=R.coords;this.x=R.coords[0];this.y=R.coords[1];this.z=R.coords[2];this.duration=R.duration;this.progress=R.progress;this.fps=R.T;this.state=R.U},k1=function(K,R,f,V,D){XS.call(this,R,f,V,D);
this.element=K},Kp_=function(K,R,f,V,D){if(R.length!=2||f.length!=2)throw Error("Start and end points must be 2D");
k1.call(this,K,R,f,V,D)},Rg8=function(K){return Math.pow(K,3)},fPi=function(K){return 3*K*K-2*K*K*K},Vv8=function(K){g.O.call(this);
this.K=K||window;this.U=[]},TC=function(K){return K.baseUrl||null},P0=function(K,R){return g.Im(g.JQ(K,R),function(f){return!!f})},D2T=function(K,R,f){function V(Rw){var FG=Rw.hovercardButton;
if(!FG)return null;FG=FG.subscribeButtonRenderer;if(!FG)return null;var yN=H(FG.unsubscribedButtonText),VN=H(FG.subscribedButtonText);if(FG.subscribed){var aw=H(FG.subscriberCountWithUnsubscribeText);var s5=H(FG.subscriberCountText)}else aw=H(FG.subscriberCountText),s5=H(FG.subscriberCountWithSubscribeText);var dW=null;if(Rw.signinEndpoint){dW=Ak(Rw,"signinEndpoint","webNavigationEndpointData","url");if(!dW){var DB,b_;dW=(b_=g.z((DB=FG.signInEndpoint)==null?void 0:DB.commandMetadata,g.wA))==null?
void 0:b_.url}if(!dW)return null}return yN&&(VN||dW)?{subscribed:FG.subscribed,subscribeText:yN,subscribeCount:aw,unsubscribeText:VN,unsubscribeCount:s5,enabled:FG.enabled,signinUrl:dW,classic:Rw.useClassicSubscribeButton}:null}
function D(Rw){if(Rw){var FG=[],yN=Rw.videoId;yN&&FG.push("v="+yN);(yN=Rw.playlistId)&&FG.push("list="+yN);(Rw=Rw.startTimeSeconds)&&FG.push("t="+Rw);return"/watch?"+FG.join("&")}}
function H(Rw){if(!Rw)return null;var FG=Rw.simpleText;return FG?FG:Rw.runs?g.JQ(Rw.runs,function(yN){return yN.text}).join(""):null}
R=R.endscreenElementRenderer;if(!R)return null;var l=R.style,F=R.endpoint||{},c=null,r=null,y=!1,h=null,S=null,v=null,L=null,E=!1,Q=null,J=null,A=null,B=null,k=null,b=null;if(l==="VIDEO")g.z(F,g.Tq)?c=g.z(F,g.Tq).url:(b=g.z(F,g.$s),c=D(b)),r=!1,h=K,R.thumbnailOverlays?(y=R.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,S=H(y.text),y=y.style==="LIVE"):S=H(R.videoDuration);else if(l==="PLAYLIST")g.z(F,g.Tq)?c=g.z(F,g.Tq).url:(b=g.z(F,g.$s),c=D(b)),r=!1,h=K,v=H(R.playlistLength);else if(l===
"CHANNEL"){if(E=Ak(F,"browseEndpoint","browseId"))L=E,c="/channel/"+L;r=!1;h="new";(E=!!R.isSubscribe)?Q=V(R):J=H(R.subscribersText)}else l==="WEBSITE"?((A=Ak(F,"urlEndpoint","url"))&&(c=A),r=!0,h="new",A=R.icon.thumbnails[0].url):l==="CREATOR_MERCHANDISE"&&(R.productPrice&&(B=H(R.productPrice)),R.additionalFeesText&&(k=H(R.additionalFeesText)),(r=Ak(F,"urlEndpoint","url"))&&(c=r),r=!0,h="new");K=Ak(R,"title","accessibility","accessibilityData","label");var M=R.endpoint?R.endpoint.clickTrackingParams:
null,Hc="";if(R.metadata){var fB=H(R.metadata);fB&&(Hc=fB)}return{id:"element-"+f,type:l,title:H(R.title),metadata:Hc,callToAction:H(R.callToAction),Ri:R.image,iconUrl:A,left:Number(R.left),width:Number(R.width),top:Number(R.top),aspectRatio:Number(R.aspectRatio),startMs:Math.floor(Number(R.startMs)),endMs:Math.floor(Number(R.endMs)),videoDuration:S,AT:y,playlistLength:v,channelId:L,subscribeButton:Q,subscribersText:J,isSubscribe:E,targetUrl:c||null,jYa:r,sessionData:M?{itct:M}:null,ZP0:h,qE:K?K:
null,isPlaceholder:R.isPlaceholder,impressionUrls:P0(R.impressionUrls||[],TC),Mre:P0(R.hovercardShowUrls||[],TC),clickUrls:P0(F.loggingUrls||[],TC),visualElement:g.SV(R.trackingParams),productPrice:B,additionalFeesText:k,watchEndpoint:b||null}},HCV=function(K,R){var f={startMs:Math.floor(Number(K.startMs)),
impressionUrls:P0(K.impressionUrls||[],TC),elements:P0(K.elements||[],function(V,D){return D2T(R,V,D)})};
K.trackingParams&&(f.visualElement=g.SV(K.trackingParams));return f},$2_=function(K){g.cz.call(this,K);
this.J=this.endscreen=null;this.K={};this.T={};this.B=this.X=null;this.Z=[];this.U=null;this.UF=!0;this.N=0;K=K.C();this.EF=g.Oc(K)||g.ql(K);this.events=new g.de(this);g.q(this,this.events);this.events.j(this.player,g.gI("creatorendscreen"),this.onCueRangeEnter);this.events.j(this.player,g.OK("creatorendscreen"),this.onCueRangeExit);this.events.j(this.player,"resize",this.xl);this.events.j(window,"focus",this.Fi0);this.load();var R=g.tB("STYLE");(g.wE("HEAD")[0]||document.body).appendChild(R);this.addOnDisposeCallback(function(){g.kU(R)});
R.sheet&&(R.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),R.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},lPi=function(K){return K.player.getVideoData().nL?"current":K.EF?"new":"current"},nm=function(K){return K.player.C().playerStyle==="creator-endscreen-editor"},d2p=function(K){var R=K.player.getVideoData(),f=R.videoId;
K.J&&K.J.abort();f={method:"POST",onFinish:function(D){var H=K.J=null;D.status===200&&(D=D.responseText,D.substring(0,3)===")]}"&&(D=D.substring(3),H=JSON.parse(D),H=HCV(H,lPi(K))));Ic(K,H)},
urlParams:{v:f},withCredentials:!0};K.EF&&(f.urlParams.ptype="embedded");var V=R.Vx;V&&(f.postParams={ad_tracking:V});if(R=g.Sre(R))if(R=g.N2(R),R=g.EA(R))K.J=g.Jm(R,f)},Ic=function(K,R,f){f=f===void 0?!0:f;
K.player.BV("creatorendscreen");K.X&&(K.X.dispose(),K.X=null,K.B.dispose(),K.B=null);for(var V=g.Z(Object.values(K.K)),D=V.next();!D.done;D=V.next())D.value.dispose();K.K={};K.T={};K.Z.length>0&&(K.Z.forEach(function(F){F.dispose()}),K.Z.length=0);
K.U&&(g.c2(K.U,"ytp-ce-element-show"),K.U.setAttribute("aria-hidden","true"));K.N=0;if((K.endscreen=R)&&R.elements){f&&Fpp(K);f=[];V=new g.nQ(R.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});f.push(V);K.player.C().K||(K.X=new g.Y({V:"div",D:"ytp-ce-shadow"}),g.nl(K.player,K.X.element,4),K.B=new g.K0(K.X,200));for(V=0;V<R.elements.length;++V){D=R.elements[V];var H=clH(K,D);if(H){K.K[D.id]=H;K.T[D.id]=D;g.nl(K.player,H.element,4);var l=new g.nQ(D.startMs,D.endMs,{id:"ytp-ce-element-"+
D.id,namespace:"creatorendscreen"});f.push(l);rlV(K,H,D)}else g.A$(new g.NB("buildEndscreenElement null",D))}K.player.PV(f);K.xl()}},Fpp=function(K){var R=g.LM(),f=g.wu();
f&&R&&K.endscreen.visualElement&&g.DY(g.jV)(void 0,f,R,K.endscreen.visualElement)},clH=function(K,R){var f=null;
switch(R.type){case "VIDEO":K={V:"div",Me:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":R.qE||"","aria-hidden":"true"},S:[{V:"div",D:"ytp-ce-element-shadow"},{V:"div",D:"ytp-ce-covering-image",L:g5(R)},{V:"div",D:"ytp-ce-covering-shadow-top"},{V:"a",D:"ytp-ce-covering-overlay",L:{href:Ob(K,R.targetUrl),tabindex:"-1"},S:[{V:"div",Me:["ytp-ce-video-title","ytp-webkit-ellipsis"],L:{dir:g.Le(R.title||"")},Q0:R.title},{V:"div",D:R.AT?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Q0:R.videoDuration||void 0}]}]};f=new g.Y(K);break;case "PLAYLIST":K={V:"div",Me:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":R.qE||"","aria-hidden":"true"},S:[{V:"div",D:"ytp-ce-element-shadow"},{V:"div",D:"ytp-ce-covering-image",L:g5(R)},{V:"div",D:"ytp-ce-covering-shadow-top"},{V:"a",D:"ytp-ce-covering-overlay",L:{href:Ob(K,R.targetUrl),tabindex:"-1"},S:[{V:"div",Me:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],L:{dir:g.Le(R.title||"")},Q0:R.title},{V:"div",D:"ytp-ce-playlist-count",
S:[{V:"div",D:"ytp-ce-playlist-icon"},{V:"div",D:"ytp-ce-playlist-count-text",Q0:R.playlistLength||void 0}]}]}]};f=new g.Y(K);break;case "CHANNEL":f={V:"div",Me:["ytp-ce-element","ytp-ce-channel",R.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":R.qE||"","aria-hidden":"true"},S:[{V:"div",D:"ytp-ce-element-shadow"},{V:"div",D:"ytp-ce-expanding-overlay",S:[{V:"div",D:"ytp-ce-expanding-overlay-hider"},{V:"div",D:"ytp-ce-expanding-overlay-background"},{V:"div",D:"ytp-ce-expanding-overlay-content",
S:[{V:"div",D:"ytp-ce-expanding-overlay-body",S:[{V:"div",D:"ytp-ce-expanding-overlay-body-padding",S:[{V:"a",Me:["ytp-ce-channel-title","ytp-ce-link"],L:{href:Ob(K,R.targetUrl),target:"_blank",tabindex:"-1",dir:g.Le(R.title||"")},Q0:R.title},R.subscribeButton?{V:"div",D:"ytp-ce-subscribe-container",S:[{V:"div",D:"ytp-ce-channel-subscribe"}]}:"",R.subscribersText?{V:"div",D:"ytp-ce-channel-subscribers-text",Q0:R.subscribersText}:"",R.metadata?{V:"div",Me:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Q0:R.metadata}:""]}]}]}]},{V:"div",D:"ytp-ce-expanding-image",L:g5(R)}]};f=new g.Y(f);var V=g.xU(document,"div","ytp-ce-channel-subscribe",f.element)[0];if(R.subscribeButton&&R.channelId){g.dy(V,"ytp-ce-subscribe-button");if(K.player.C().K){var D=null;var H=R.sessionData.itct}else D="endscreen",H=null;D=new g.bY(R.subscribeButton.subscribeText,R.subscribeButton.subscribeCount,R.subscribeButton.unsubscribeText,R.subscribeButton.unsubscribeCount,!!R.subscribeButton.enabled,!!R.subscribeButton.classic,
R.channelId,!!R.subscribeButton.subscribed,D,H,K.player,!1);V.appendChild(D.element);K.Z.push(D)}break;case "WEBSITE":K={V:"div",Me:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":R.qE||"","aria-hidden":"true"},S:[{V:"div",D:"ytp-ce-element-shadow"},{V:"div",D:"ytp-ce-expanding-overlay",S:[{V:"div",D:"ytp-ce-expanding-overlay-hider"},{V:"div",D:"ytp-ce-expanding-overlay-background"},{V:"div",D:"ytp-ce-expanding-overlay-content",S:[{V:"div",D:"ytp-ce-expanding-overlay-body",S:[{V:"div",
D:"ytp-ce-expanding-overlay-body-padding",S:[{V:"div",D:"ytp-ce-website-title",L:{dir:g.Le(R.title||"")},Q0:R.title},{V:"div",D:"ytp-ce-website-metadata",Q0:R.metadata},{V:"a",Me:["ytp-ce-website-goto","ytp-ce-link"],L:{href:Ob(K,R.targetUrl),target:"_blank",tabindex:"-1"},Q0:R.callToAction}]}]}]}]},{V:"div",D:"ytp-ce-expanding-image",L:g5(R)},{V:"div",D:"ytp-ce-expanding-icon",L:yl_(R.iconUrl)}]};f=new g.Y(K);break;case "CREATOR_MERCHANDISE":f="",R.productPrice&&(f={V:"div",D:"ytp-ce-merchandise-price-container",
S:[{V:"div",D:"ytp-ce-merchandise-price",Q0:R.productPrice}]},R.additionalFeesText&&f.S.push({V:"div",D:"ytp-ce-merchandise-additional-fees",Q0:R.additionalFeesText})),K={V:"div",Me:["ytp-ce-element","ytp-ce-merchandise"],L:{tabindex:"0","aria-label":R.qE||"","aria-hidden":"true"},S:[{V:"div",D:"ytp-ce-element-shadow"},{V:"div",D:"ytp-ce-expanding-overlay",S:[{V:"div",D:"ytp-ce-expanding-overlay-hider"},{V:"div",D:"ytp-ce-expanding-overlay-background"},{V:"div",D:"ytp-ce-expanding-overlay-content",
S:[{V:"div",D:"ytp-ce-expanding-overlay-body",S:[{V:"div",D:"ytp-ce-expanding-overlay-body-padding",S:[{V:"div",D:"ytp-ce-merchandise-title",L:{dir:g.Le(R.title||"")},Q0:R.title},f,{V:"div",D:"ytp-ce-merchandise-metadata",Q0:R.metadata},{V:"a",Me:["ytp-ce-merchandise-goto","ytp-ce-link"],L:{href:Ob(K,R.targetUrl),target:"_blank",tabindex:"-1"},Q0:R.callToAction}]}]}]}]},{V:"div",D:"ytp-ce-expanding-image",L:g5(R)},{V:"div",D:"ytp-ce-merchandise-invideo-cta-container",S:[{V:"div",D:"ytp-ce-merchandise-invideo-cta",
Q0:R.callToAction||void 0}]}]},f=new g.Y(K)}R.isPlaceholder&&g.dy(f.element,"ytp-ce-placeholder");return f},g5=function(K){if(K.Ri)var R=K.Ri.thumbnails;
return yl_(R?R[R.length-1].url:null)},yl_=function(K){return K?{style:"background-image: url("+K+")"}:{}},rlV=function(K,R,f){function V(c){c&&(R.listen("blur",function(){c.style.display!="none"&&K.UF&&c.focus()}),R.j(c,"focus",H),R.j(c,"blur",l))}
function D(c){K.N+=c;K.N>0?(g.dy(R.element,"ytp-ce-force-expand"),jP(K,f.id,!0)):(g.c2(R.element,"ytp-ce-force-expand"),g.c2(R.element,"ytp-ce-element-hover"),jP(K,f.id,!1))}
function H(){D(1)}
function l(){D(-1)}
R.listen("mouseenter",function(){hgu(K,R,f)});
R.listen("mouseleave",function(){o7p(K,R,f)});
K.player.C().K||R.listen("click",function(){g.dy(R.element,"ytp-ce-element-hover")});
R.listen("click",function(c){SAB(K,f,c)});
R.listen("keypress",function(c){SAB(K,f,c)});
R.listen("focus",function(){hgu(K,R,f)});
R.listen("blur",function(){o7p(K,R,f)});
R.listen("touchstart",function(){hgu(K,R,f)});
var F=g.Ea("ytp-ce-expanding-overlay-hider",R.element);F&&R.j(F,"touchstart",function(c){c.stopPropagation();g.c2(R.element,"ytp-ce-element-hover");g.c2(R.element,"ytp-ce-force-expand")});
R.listen("keydown",function(c){K.UF=c.keyCode===9&&!c.shiftKey});
V(g.Ea("ytp-sb-subscribe",R.element));V(g.Ea("ytp-sb-unsubscribe",R.element));R.listen("focus",H);R.listen("blur",l)},SAB=function(K,R,f){if(R.targetUrl&&(!f||f.type!=="keypress"||f.keyCode===13)){for(var V=f.target;V&&!g.lp(V,"ytp-ce-element");){g.lp(V,"subscribe-label")&&iCW(K,R);
if(g.lp(V,"ytp-ce-channel-subscribe"))return;V=V.parentElement||null}if(!V||g.lp(V,"ytp-ce-element-hover")){f.preventDefault();f.stopPropagation();if(V=K.K[R.id])o7p(K,V,R),V.element.blur();if(f.ctrlKey||f.metaKey||R.ZP0==="new")iCW(K,R),K.player.sendVideoStatsEngageEvent(17,void 0),K.player.pauseVideo(),f=g.N2(Ob(K,R.targetUrl)),f=g.EA(f),g.jC(f,void 0,R.sessionData);else{var D=g.fc(K.player.C())||K.player.getVideoData().nL,H=function(){var l=Ob(K,R.targetUrl),F=R.sessionData,c=R.watchEndpoint,r=
g.FN(l);D&&r&&(r.v||r.list)?K.player.V4(r.v,F,r.list,!1,void 0,c||void 0):g.O_(l,F)};
iCW(K,R,function(){K.player.sendVideoStatsEngageEvent(17,H)})}}}},Ob=function(K,R){K=K.player.C();
if(R){if(R.startsWith("//"))return K.protocol+":"+R;if(R.startsWith("/"))return g.cd(K)+R}else return"";return R},hgu=function(K,R,f){g.lp(R.element,"ytp-ce-element-hover")||(f.type==="VIDEO"||f.type==="PLAYLIST"?g.dy(R.element,"ytp-ce-element-hover"):K.player.C().K?(new g.CW(function(){g.dy(R.element,"ytp-ce-element-hover")},200)).start():g.dy(R.element,"ytp-ce-element-hover"),qA(K,f.Mre),jP(K,f.id,!0))},o7p=function(K,R,f){g.c2(R.element,"ytp-ce-element-hover");
g.c2(R.element,"ytp-ce-force-expand");jP(K,f.id,!1)},jP=function(K,R,f){K.X&&(f?K.B.show():K.B.hide());
for(var V=g.Z(Object.keys(K.K)),D=V.next();!D.done;D=V.next())D=D.value,D!==R&&g.yb(K.K[D].element,"ytp-ce-element-shadow-show",f)},qA=function(K,R,f){function V(){H||(D++,D===R.length&&(l.stop(),f&&f()))}
if(!R||R.length===0||nm(K))f&&f();else{R=v78(K,R);var D=0,H=!1,l=new g.CW(function(){H=!0;f&&f()},1E3,K);
l.start();for(K=0;K<R.length;K++)g.PY(R[K],V)}},iCW=function(K,R,f){qA(K,R.clickUrls,f);
(K=g.wu())&&R.jYa&&g.eV(K,R.visualElement)},v78=function(K,R){var f=K.player.getVideoData().clientPlaybackNonce;
K=K.player.getCurrentTime().toFixed(2);f={CPN:f,AD_CPN:f,MT:K};K=[];for(var V=0;V<R.length;V++)K.push(LpH(R[V],f));return K},LpH=function(K,R){return K.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(f){var V=unescape(f);
V=V.substring(1,V.length-1);return R[V]?escape(R[V]):f})},wbu=function(K){return typeof K==="string"?K:""},MA=function(K,R,f){for(var V in R)if(R[V]===K)return K;
return f},zgV=function(K,R,f,V){this.value=K;
this.target=R;this.showLinkIcon=f;this.U=V},bG=function(K){return K.value?K.value:null},pm=function(K){if(!K)return null;
var R=g.N2(wbu(K.value));R=g.EA(R);if(!R)return null;var f=MA(K.target,x2S,"current");if(f==null)K=null;else{var V=K.show_link_icon;K=new zgV(R,f,V==="true"||V==="false"?V==="true":!0,K.pause_on_navigation!=null?K.pause_on_navigation:!0)}return K},E7i=function(K,R,f){this.type=K;
this.trigger=R;this.url=f},NNS=function(K){if(!K)return null;
var R=MA(K.type,aP_),f=MA(K.trigger,QES);K=K.url;K=Array.isArray(K)&&K.length?K[0]:K;K=pm(K?K:null);return R?new E7i(R,f,K):null},U2z=function(K,R,f,V,D){this.id=K;
this.type=R;this.style=f;this.data=D;this.action=V||[]},WpE=function(K,R){return g.G$(K.action,R)},tv_=function(K,R){this.context=K;
this.U=R},AlT=function(K){return K.customMessage?Y1("div","iv-card-message",K.customMessage):""},mP=function(K,R){K="background-image: url("+K+");";
var f=[];R&&f.push(R);return{V:"div",D:"iv-card-image",L:{style:K},S:f}},Jli=function(K){if(!K.metaInfo||K.metaInfo.length===0)return"";
var R=[];K=g.Z(K.metaInfo);for(var f=K.next();!f.done;f=K.next())R.push(Y1("li","",f.value));return{V:"ul",D:"iv-card-meta-info",S:R}},Y1=function(K,R,f){R?typeof R==="string"?R={"class":R}:Array.isArray(R)&&(R={"class":R.join(" ")}):R={};
R.dir=g.Le(f);return{V:K,L:R,Q0:f}},ZCS=function(K){if(!K.customMessage)return"";
var R=["iv-card-action","iv-card-primary-link"],f={};K.jB&&(R.push("iv-card-action-icon"),f.style="background-image: url("+K.jB+");");f.dir=g.Le(K.customMessage);var V=[{V:"span",Q0:K.customMessage}];K.showLinkIcon&&(V.push("\u00a0"),V.push({V:"span",D:"iv-card-link-icon"}));return{V:"div",Me:R,L:f,S:V}},GC=function(K,R,f,V){if(V){R=g.Z(R);
for(var D=R.next();!D.done;D=R.next())K.U(D.value,V,f.id,f.sessionData,f.U$.click,5)}},BN$=function(K,R){this.merchant=K;
this.price=R},Xbp=function(K){var R;
(R=K)&&!(R=K.length>1?K.charAt(0)==="/"&&K.charAt(1)!=="/":K==="/")&&(R=K.replace(/^(https?:)?\/\//,"").split("/",1),R=!R||R.length<1||!R[0]?[]:R[0].toLowerCase().split(".").reverse(),R=R[0]==="com"&&R[1]==="youtube"||R[0]==="be"&&R[1]==="youtu");return R?K.indexOf("/redirect?")===-1:!1},kd8=function(K,R){return R?R:Xbp(K)?"current":"new"},uG=function(K,R){g.O.call(this);
var f=this;this.element=K;this.context=R;this.v5=!1;this.Ne=new Map;this.kW=new Map;this.context.G.addEventListener(g.gI("annotations_module"),function(V){(V=f.Ne.get(V))&&V.apply(f)});
this.context.G.addEventListener(g.OK("annotations_module"),function(V){(V=f.kW.get(V))&&V.apply(f)})},sb=function(K,R,f,V,D,H,l){K.context.U.listen(R,"click",function(F){K.eU(f,V,D,H||[],l||0,F)});
K.context.U.listen(R,"touchstart",function(){K.v5=!1});
K.context.U.listen(R,"touchmove",function(){K.v5=!0})},TNi=function(K){var R;
return((R=g.z(K,g.Tq))==null?0:R.url)?g.z(K,g.Tq).url:(K=g.z(K,g.$s))&&K.videoId?(R="/watch?v="+K.videoId,K.playlistId&&(R+="&list="+K.playlistId),K.index&&(R+="&index="+K.index),K.startTimeSeconds&&(R+="&t="+K.startTimeSeconds),R):null},Cm=function(K,R,f){return{WO:(K.impressionLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
click:(f.loggingUrls||[]).map(function(V){return V.baseUrl||""}),
close:(R.dismissLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
XZ:(R.impressionLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
je:(R.clickLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""})}},Pm8=function(K,R,f){uG.call(this,R,f);
var V=this;this.G=K;this.eventId=null;this.Kh=this.qe=this.hV=this.X=this.isInitialized=!1;this.cards=[];this.pQ=this.B=this.er=this.T=this.oY=this.U=null;this.UF=[];this.aY=this.Z=this.H9=this.y0=null;this.N=0;this.B5=new g.CW(function(){},f.W.Ml?4E3:3E3);
g.q(this,this.B5);this.OF=new g.CW(function(){});
g.q(this,this.OF);this.Xt=new tv_(f,function(D,H,l,F,c,r){sb(V,D,H,l,F,c,r)});
this.EF=new g.Y({V:"div",D:"iv-drawer",L:{id:"iv-drawer"},S:[{V:"div",D:"iv-drawer-header",L:{"aria-role":"heading"},S:[{V:"span",D:"iv-drawer-header-text"},{V:"button",Me:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{V:"div",D:"iv-drawer-content"}]});g.q(this,this.EF);this.J=this.EF.element;this.Za=new g.K0(this.EF,330);g.q(this,this.Za);this.bd=g.Ea("iv-drawer-header-text",this.J);this.K=g.Ea("iv-drawer-content",this.J);this.addCueRange(0,f.videoData.lengthSeconds*
1E3,"",function(){V.hV&&eP(V,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(V.hV=V.X)&&KK(V)});
this.G2=new g.de(this);g.q(this,this.G2);this.G.addEventListener("videodatachange",this.u$.bind(this))},n7u=function(K,R){R=R.data;
R.autoOpenMs&&K.addCueRange(R.autoOpenMs,0x8000000000000,"",function(){eP(K,"YOUTUBE_DRAWER_AUTO_OPEN")});
R.autoCloseMs&&K.addCueRange(R.autoCloseMs,0x8000000000000,"",function(){KK(K)});
var f=R.headerText;g.Pa(K.bd,f);K.B&&(K.G.Y("player_tooltip_data_title_killswitch")?K.B.setAttribute("title",f):K.B.setAttribute("data-tooltip-title",f));R.eventId&&(K.eventId=R.eventId);K.y0=g.SV(R.trackingParams);K.Z=g.SV(R.closeTrackingParams);K.H9=g.SV(R.iconTrackingParams)},IPV=function(K,R){var f=R.cardId?R.cardId:"cr:"+K.N,V=K.G.C().experiments.rU("enable_error_corrections_infocard_web_client");
if(!R.content&&R.teaser.simpleCardTeaserRenderer&&V){var D=R.teaser.simpleCardTeaserRenderer,H=R.icon?R.icon.infoCardIconRenderer:null;if(D.channelAvatar&&D.channelAvatar.thumbnails&&D.channelAvatar.thumbnails.length>0)var l=Re(D.channelAvatar.thumbnails,22,22).url;R={id:f,timestamp:K.N,type:"simple",teaserText:g.ri(D.message),teaserDurationMs:Number(R.cueRanges[0].teaserDurationMs),startMs:Number(R.cueRanges[0].startCardActiveMs),autoOpen:!!R.autoOpen,sessionData:{},sponsored:!1,U$:{},Ey:null,lZ:D.trackingParams?
g.SV(D.trackingParams):null,H9:H&&H.trackingParams?g.SV(H.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,jB:null,title:"",customMessage:"",url:null,onClickCommand:D.onTapCommand||null,Is:l};fK(K,R)}else{var F;if((F=R.content)==null?0:F.simpleCardContentRenderer){if(!R.cueRanges.length)return;l=(D=R.content)==null?void 0:D.simpleCardContentRenderer;D=R.teaser.simpleCardTeaserRenderer;H=R.icon?R.icon.infoCardIconRenderer:null;R={id:f,timestamp:K.N,type:"simple",teaserText:g.ri(D.message),
teaserDurationMs:Number(R.cueRanges[0].teaserDurationMs),startMs:Number(R.cueRanges[0].startCardActiveMs),autoOpen:!!R.autoOpen,sessionData:V$(K,f,R,l),sponsored:!1,U$:Cm(l,D,l.command),Ey:l.trackingParams?g.SV(l.trackingParams):null,lZ:D.trackingParams?g.SV(D.trackingParams):null,H9:H&&H.trackingParams?g.SV(H.trackingParams):null,imageUrl:Re(l.image.thumbnails,290,290).url,displayDomain:l.displayDomain?g.ri(l.displayDomain):null,showLinkIcon:!!l.showLinkIcon,jB:null,title:l.title?g.ri(l.title):"",
customMessage:l.callToAction?g.ri(l.callToAction):"",url:g.z(l.command,g.Tq).url?pm({pause_on_navigation:!K.context.videoData.isLivePlayback,target:"new",value:g.z(l.command,g.Tq).url}):null,onClickCommand:null};fK(K,R)}else{var c;if((c=R.content)==null?0:c.collaboratorInfoCardContentRenderer){if(!R.cueRanges.length)return;l=(H=R.content)==null?void 0:H.collaboratorInfoCardContentRenderer;D=R.teaser.simpleCardTeaserRenderer;H=R.icon?R.icon.infoCardIconRenderer:null;R={id:f,timestamp:K.N,type:"collaborator",
teaserText:g.ri(D.message),teaserDurationMs:Number(R.cueRanges[0].teaserDurationMs),startMs:Number(R.cueRanges[0].startCardActiveMs),autoOpen:!!R.autoOpen,sessionData:V$(K,f,R,l),sponsored:!1,U$:Cm(l,D,l.endpoint),Ey:l.trackingParams?g.SV(l.trackingParams):null,lZ:D.trackingParams?g.SV(D.trackingParams):null,H9:H&&H.trackingParams?g.SV(H.trackingParams):null,channelId:g.z(l.endpoint,g.BD).browseId,customMessage:l.customText?g.ri(l.customText):null,profileImageUrl:Re(l.channelAvatar.thumbnails,290,
290).url,title:l.channelName?g.ri(l.channelName):"",metaInfo:[l.subscriberCountText?g.ri(l.subscriberCountText):""],url:pm({pause_on_navigation:!K.context.videoData.isLivePlayback,target:"new",value:g.z(l.endpoint,g.BD).canonicalBaseUrl?g.z(l.endpoint,g.BD).canonicalBaseUrl:"/channel/"+g.z(l.endpoint,g.BD).browseId}),onClickCommand:null};fK(K,R)}else{var r;if((r=R.content)==null?0:r.playlistInfoCardContentRenderer){if(!R.cueRanges.length)return;var y;l=(y=R.content)==null?void 0:y.playlistInfoCardContentRenderer;
D=R.teaser.simpleCardTeaserRenderer;H=R.icon?R.icon.infoCardIconRenderer:null;R={id:f,timestamp:K.N,type:"playlist",teaserText:g.ri(D.message),teaserDurationMs:Number(R.cueRanges[0].teaserDurationMs),startMs:Number(R.cueRanges[0].startCardActiveMs),autoOpen:!!R.autoOpen,sessionData:V$(K,f,R,l),sponsored:!1,U$:Cm(l,D,l.action),Ey:l.trackingParams?g.SV(l.trackingParams):null,lZ:D.trackingParams?g.SV(D.trackingParams):null,H9:H&&H.trackingParams?g.SV(H.trackingParams):null,gp:Re(l.playlistThumbnail.thumbnails,
258,290).url,customMessage:l.customMessage?g.ri(l.customMessage):null,playlistVideoCount:g.ri(l.playlistVideoCount),title:l.playlistTitle?g.ri(l.playlistTitle):"",metaInfo:[l.channelName?g.ri(l.channelName):"",l.videoCountText?g.ri(l.videoCountText):""],url:pm({pause_on_navigation:!K.context.videoData.isLivePlayback,target:"new",value:TNi(l.action)}),onClickCommand:null};fK(K,R)}else{var h;if((h=R.content)==null?0:h.videoInfoCardContentRenderer){if(!R.cueRanges.length)return;var S;l=(S=R.content)==
null?void 0:S.videoInfoCardContentRenderer;D=R.teaser.simpleCardTeaserRenderer;H=R.icon?R.icon.infoCardIconRenderer:null;R={id:f,timestamp:K.N,type:"video",teaserText:g.ri(D.message),teaserDurationMs:Number(R.cueRanges[0].teaserDurationMs),startMs:Number(R.cueRanges[0].startCardActiveMs),autoOpen:!!R.autoOpen,sessionData:V$(K,f,R,l),sponsored:!1,U$:Cm(l,D,l.action),Ey:l.trackingParams?g.SV(l.trackingParams):null,lZ:D.trackingParams?g.SV(D.trackingParams):null,H9:H&&H.trackingParams?g.SV(H.trackingParams):
null,gp:Re(l.videoThumbnail.thumbnails,258,290).url,videoDuration:l.lengthString?g.ri(l.lengthString):null,customMessage:l.customMessage?g.ri(l.customMessage):null,title:l.videoTitle?g.ri(l.videoTitle):"",metaInfo:[l.channelName?g.ri(l.channelName):"",l.viewCountText?g.ri(l.viewCountText):""],isLiveNow:!!l.badge,url:pm({pause_on_navigation:!K.context.videoData.isLivePlayback,target:"new",value:TNi(l.action)}),onClickCommand:null};fK(K,R)}}}}}K.N++},Re=function(K,R,f){for(var V=-1,D=-1,H=0;H<K.length;H++){if(K[H].height===
R||K[H].width===f)return K[H];
((K[H].height||0)<R||(K[H].width||0)<f)&&(V<0||(K[V].height||0)<(K[H].height||0)||(K[V].width||0)<(K[H].width||0))?V=H:((K[H].height||0)>=R||(K[H].width||0)>=f)&&(D<0||(K[D].height||0)>(K[H].height||0)||(K[D].width||0)>(K[H].width||0))&&(D=H)}return K[D>=0?D:V]},V$=function(K,R,f,V){return{feature:f.feature?f.feature:"cards",
src_vid:K.context.videoData.videoId,annotation_id:R,ei:K.context.videoData.eventId||"",itct:V.trackingParams||""}},OCi=function(K,R){if(R=g7E(K,R))R===K.U&&(K.U=null),K.G.removeCueRange(R.qR.id),g.kU(R.nG),g.fa(K.cards,R),K.UG(),D0(K)},eP=function(K,R,f){if(!K.X){K.Za.show();
K.oY=new g.CW(function(){g.dy(K.context.G.getRootNode(),g.UC.IV_DRAWER_OPEN)},0);
K.oY.start();K.G2.j(K.K,"mousewheel",function(l){K.B5.start();l.preventDefault();l=l||window.event;var F=0;l.type=="MozMousePixelScroll"?F=0==(l.axis==l.HORIZONTAL_AXIS)?l.detail:0:window.opera?F=l.detail:F=l.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?l.wheelDeltaY/-30:l.wheelDeltaY/-1.2:l.wheelDelta/-1.6:l.wheelDeltaY/-3;if(l=F)K.K.scrollTop+=l});
K.X=!0;var V=g.wu();V&&K.y0&&K.Z&&g.sI(V,[K.y0,K.Z]);R={TRIGGER_TYPE:R};for(var D=g.Z(K.cards),H=D.next();!H.done;H=D.next())H=H.value,H.xw||(H.xw=!0,jE8(K.context.logger,H.qR.U$.WO,R)),V&&g.sI(V,[H.qR.Ey]);tk(K.G);f&&(K.T=new g.CW(function(){K.er=K.B;K.pQ.focus()},330),K.T.start())}},KK=function(K){K.X&&(K.Za.hide(),g.kc(K.G2),g.c2(K.context.G.getRootNode(),g.UC.IV_DRAWER_OPEN),K.X=!1,tk(K.G),K.T&&K.T.stop(),K.T=new g.CW(function(){K.er&&(K.er.focus(),K.er=null)},330),K.T.start())},qA8=function(K){g.FJ(K.ud(),
[g.UC.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.nl(K.G,K.J,5);K.Az();K.B=g.Ea("ytp-cards-button",K.G.getRootNode());K.pQ=g.Ea("iv-drawer-close-button",K.J);K.isInitialized=!0},pbi=function(K){K.UF.push(g.RQ("iv-teaser-shown",K.Jw,K));
K.UF.push(g.RQ("iv-teaser-hidden",K.QG5,K));K.UF.push(g.RQ("iv-teaser-clicked",K.yw,K));K.Kh=!0},YAB=function(K,R){var f;
return R.onClickCommand&&((f=g.z(R.onClickCommand,g.aD8))==null?void 0:f.targetId)==="engagement-panel-error-corrections"?(K.aY=R,!0):!1},m2z=function(K,R){K.aY=R;
var f=K.G.getVideoData();if(!f)return!1;f=g.Tj(f);if(f==null?0:f.markersMap)for(var V,D=0;((V=f)==null?void 0:V.markersMap.length)>D;D++){var H=void 0,l=(H=f)==null?void 0:H.markersMap[D];if(l.key==="ERROR_CORRECTION_MARKERS"&&(H=void 0,(l=(H=l.value)==null?void 0:H.markers)&&l.length>0))return V=void 0,R.startMs=((V=g.z(l[0],g.fC5))==null?void 0:V.timeRangeStartMillis)||0,K.aY=null,!0}return!1},fK=function(K,R){if(!YAB(K,R)||m2z(K,R)){var f=GdT(K,R);
if(f){var V={qR:R,nG:f.element,xw:!1};if(R.onClickCommand)K.G.Y("web_infocards_teaser_show_logging_fix")&&(K.Kh||pbi(K),OCi(K,R.id),f=K.findLastIndex(V),g.rJ(K.cards,f,0,V));else{K.isInitialized||qA8(K);OCi(K,R.id);var D=K.findLastIndex(V);g.rJ(K.cards,D,0,V);f.V0(K.K,D);K.UG()}R.autoOpen?K.addCueRange(R.startMs,0x8000000000000,R.id,function(){K.X||(K.U=V,D0(K),u8$(K,V),eP(K,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(f=K.context.G.getCurrentTime()*1E3,f<5E3&&f>R.startMs&&sET(K,V),K.addCueRange(R.startMs,
R.startMs+1,R.id,function(){sET(K,V)}),D0(K))}}},GdT=function(K,R){switch(R.type){case "simple":K=K.Xt;
var f=R.displayDomain?{V:"div",D:"iv-card-image-text",Q0:R.displayDomain}:void 0;var V=ZCS(R);f={V:"div",Me:["iv-card"],S:[{V:"a",D:"iv-click-target",L:{href:R.url?bG(R.url)||"":""},S:[mP(R.imageUrl,f),{V:"div",D:"iv-card-content",S:[Y1("h2",void 0,R.title),V]}]}]};f=new g.Y(f);GC(K,g.za("iv-click-target",f.element),R,R.url);R=f;break;case "collaborator":K=K.Xt;f={V:"div",Me:["iv-card","iv-card-channel"],S:[{V:"a",Me:["iv-click-target"],L:{href:bG(R.url)||"","data-ytid":R.channelId},S:[mP(R.profileImageUrl),
{V:"div",D:"iv-card-content",S:[AlT(R),{V:"h2",D:"iv-card-primary-link",Q0:R.title},Jli(R)]}]}]};f=new g.Y(f);GC(K,g.za("iv-click-target",f.element),R,R.url);R=f;break;case "playlist":K=K.Xt;f={V:"div",Me:["iv-card","iv-card-playlist"],S:[{V:"a",D:"iv-click-target",L:{href:bG(R.url)||""},S:[mP(R.gp,{V:"div",D:"iv-card-image-overlay",S:[{V:"span",D:"iv-card-playlist-video-count",Q0:R.playlistVideoCount}]}),{V:"div",D:"iv-card-content",S:[AlT(R),Y1("h2","iv-card-primary-link",R.title),Jli(R)]}]}]};
f=new g.Y(f);GC(K,g.za("iv-click-target",f.element),R,R.url);R=f;break;case "productListing":K=K.Xt;var D=R.offers.length!=0;f=["iv-card"];V="";var H=ZCS(R);D&&(f.push("iv-card-product-listing"),V="iv-card-primary-link",H=R.offers[0],D=[],H.price&&D.push({V:"div",D:"iv-card-offer-price",Q0:H.price}),H.merchant&&D.push({V:"div",D:"iv-card-offer-merchant",Q0:H.merchant}),H={V:"div",S:D});D=R.url?bG(R.url)||"":"";f={V:"div",Me:f,L:{tabindex:"0"},S:[{V:"a",Me:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+
R.imageUrl+");",href:D,"aria-hidden":"true",tabindex:"-1"}},{V:"div",D:"iv-card-content",S:[R.sponsored?{V:"div",D:"iv-card-sponsored",S:["Patrocinado",{V:"div",D:"iv-ad-info-container",S:[{V:"div",D:"iv-ad-info",Q0:"{{adInfo}}"},{V:"div",D:"iv-ad-info-icon-container",S:[{V:"div",D:"iv-ad-info-icon"},{V:"div",D:"iv-ad-info-callout"}]}]}]}:"",{V:"a",D:"iv-click-target",L:{href:D},S:[Y1("h2",V,R.title),H]}]}]};f=new g.Y(f);V=g.tB("span");g.Pa(V,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");
f.setContent(V,"adInfo");GC(K,g.za("iv-click-target",f.element),R,R.url);R=f;break;case "video":K=K.Xt;V=R.videoDuration?{V:"span",D:"iv-card-video-duration",Q0:R.videoDuration}:void 0;H=R.isLiveNow?{V:"span",Me:["yt-badge","yt-badge-live"],Q0:"EN DIRECTO AHORA"}:null;D={V:"div",Me:["iv-card","iv-card-video"],S:[{V:"a",D:"iv-click-target",L:{href:((f=R.url)==null?void 0:bG(f))||""},S:[mP(R.gp,V),{V:"div",D:"iv-card-content",S:[AlT(R),Y1("h2","iv-card-primary-link",R.title),Jli(R),H]}]}]};f=new g.Y(D);
GC(K,g.za("iv-click-target",f.element),R,R.url);R=f;break;default:return null}return R},Cmz=function(K){if(K.U)return K.U.qR.type==="productListing";
if(K.G.Y("enable_wn_infocards")){var R;return!((R=K.cards)==null||!R.length)&&g.Zs(K.cards,function(f){return f.qR.type==="productListing"})}return g.Zs(K.cards,function(f){return f.qR.type==="productListing"})},D0=function(K){g.yb(K.G.getRootNode(),"ytp-cards-shopping-active",Cmz(K))},sET=function(K,R){if(!g.lp(K.G.getRootNode(),"ytp-cards-teaser-shown")){if(K.U!==R){var f=g.wu(),V=K.U?K.U.qR.H9:K.H9;
f&&V&&g.CM(f,[V]);K.U=R;D0(K)}(f=K.isInitialized&&K.ud().style.display=="none")||(f=K.context.G.getPlayerState(),V=f===0&&K.context.G.getCurrentTime()===0,f=!(f===1||f===3||V));if(!f&&R.qR.teaserDurationMs){var D;f={teaserText:R.qR.teaserText,durationMs:R.qR.teaserDurationMs,onClickCommand:R.qR.onClickCommand,Is:(D=R.qR.Is)!=null?D:null};K.G.l1(!0,f)}K.OF.isActive()||((!K.X||!K.B5.isActive()&&K.qe)&&u8$(K,R),K.OF.start(910+R.qR.teaserDurationMs))}},u8$=function(K,R){K.EF.EC?(R=new XS([0,
K.K.scrollTop],[0,R.nG.offsetTop],600,fPi),K.context.X.listen(R,"animate",function(f){K.K.scrollTop=f.y}),K.context.X.listen(R,"finish",function(f){K.K.scrollTop=f.y}),R.play()):(K.EF.dn(!0),K.K.scrollTop=R.nG.offsetTop,K.EF.dn(!1))},HU=function(K){return K.U&&K.U.qR?K.U.qR:K.cards[0]&&K.cards[0].qR?K.cards[0].qR:null},g7E=function(K,R){return g.G$(K.cards,function(f){return f.qR.id===R})},$G=function(K,R,f){uG.call(this,K,R);
this.annotation=f;this.isActive=!1},egB=function(K){var R=K.annotation.data;
"start_ms"in R&&"end_ms"in R&&K.addCueRange(Number(R.start_ms),Number(R.end_ms),K.annotation.id,function(){K.show()},function(){K.hide()})},lL=function(K,R,f){$G.call(this,K,R,f);
this.U=null;this.X=!1;this.K=null},KaV=function(K,R){var f=f===void 0?0:f;
var V=Yhz(R).width;g.rB(R,V);f=new Kp_(R,[V,R.offsetTop],[V-V-f,R.offsetTop],200,Rg8);g.q(K,f);K.context.X.listen(f,"begin",function(){g.vi(R,!0)});
f.play()},ROB=function(K,R,f,V,D,H,l){this.U=K;
this.X=R;this.W=f;this.videoData=V;this.logger=D;this.G=H;this.K=l},fzi=function(K,R,f){$G.call(this,K,R,f);
var V=this;this.Z=this.isCollapsed=this.EF=!1;this.T=5E3;this.K=this.X=this.U=this.J=null;this.N=this.createElement({V:"div",Me:["iv-promo-contents"]});this.B=new g.CW(function(){V.U.setAttribute("aria-hidden","true");g.vi(V.X,!1);g.vi(V.K,!0)},700,this);
g.q(this,this.B)},DVz=function(K){var R=K.annotation.data;
if(K.annotation.style==="cta")var f=6;else if(K.annotation.style==="video"||K.annotation.style==="playlist")f=7;K.T=R.collapsedelay_ms||K.T;var V=["iv-promo","iv-promo-inactive"];K.ud().setAttribute("aria-hidden","true");K.ud().setAttribute("aria-label","Promoci\u00f3n");K.ud().tabIndex=0;var D=K.annotation.y9(),H=R.image_url;if(H){var l=K.createElement({V:"div",Me:["iv-promo-img","iv-click-target"]});H=K.createElement({V:"img",L:{src:H,"aria-hidden":"true"}});l.appendChild(H);R.video_duration&&!R.is_live?
(H=K.createElement({V:"span",D:"iv-promo-video-duration",Q0:R.video_duration}),l.appendChild(H)):R.playlist_length&&(H=K.createElement({V:"span",D:"iv-promo-playlist-length",Q0:R.playlist_length.toString()}),l.appendChild(H));D&&sb(K,l,D,K.annotation.id,R.session_data,void 0,f)}D?(H=K.createElement({V:"a",D:"iv-promo-txt"}),g.Wb(H,bG(D)),K.U=H):K.U=K.createElement({V:"div",D:"iv-promo-txt"});switch(K.annotation.style){case "cta":case "website":var F=K.createElement({V:"p",S:[{V:"strong",Q0:R.text_line_1}]});
var c=K.createElement({V:"p",S:[{V:"span",D:"iv-promo-link",Q0:R.text_line_2}]});if(H=R.text_line_3){V.push("iv-promo-website-card-cta-redesign");var r=K.createElement({V:"button",Me:["iv-promo-round-expand-icon","ytp-button"]});H=K.createElement({V:"button",Me:["iv-button","iv-promo-button"],S:[{V:"span",D:"iv-button-content",Q0:H}]});var y=K.createElement({V:"div",D:"iv-promo-button-container"});y.appendChild(H);D&&sb(K,K.ud(),D,K.annotation.id,R.session_data,void 0,f)}g.dy(K.U,"iv-click-target");
D&&sb(K,K.U,D,K.annotation.id,R.session_data,void 0,f);break;case "playlist":case "video":F=K.createElement({V:"p",S:[{V:"span",Q0:R.text_line_1}]}),c=K.createElement({V:"p",S:[{V:"strong",Q0:R.text_line_2}]}),R.is_live&&(F=c,c=K.createElement({V:"span",Me:["yt-badge","iv-promo-badge-live"],Q0:"EN DIRECTO AHORA"})),g.dy(K.U,"iv-click-target"),D&&sb(K,K.U,D,K.annotation.id,R.session_data,void 0,f),V.push("iv-promo-video")}F&&K.U.appendChild(F);c&&K.U.appendChild(c);K.N.appendChild(K.U);y&&K.N.appendChild(y);
f=K.createElement({V:"div",D:"iv-promo-actions"});K.K=K.createElement({V:"button",Me:["iv-promo-expand","ytp-button"]});K.K.title="Expandir";K.context.U.listen(K.K,"click",function(h){VLi(K,5E3,h)});
f.appendChild(K.K);g.vi(K.K,!1);K.context.U.listen(K.ud(),"mouseover",K.Sn,K);K.context.U.listen(K.ud(),"mouseout",K.x$,K);K.context.U.listen(K.ud(),"touchend",function(h){VLi(K,5E3,h)});
K.X=K.createElement({V:"button",Me:["iv-promo-close","ytp-button"]});K.X.title="Cerrar";K.context.U.listen(K.X,"click",K.annotation.style==="cta"&&R.text_line_3?K.Ce:K.Hm,K);f.appendChild(K.X);g.FJ(K.ud(),V);l&&(g.JB(K.ud(),l),r&&l.appendChild(r));g.JB(K.ud(),K.N);g.JB(K.ud(),f)},VLi=function(K,R,f){f.stopPropagation();
HTT(K);$Vi(K,R);K.U.focus()},lz$=function(K){K.isCollapsed||K.Z||K.J||(g.dy(K.ud(),"iv-promo-collapsed"),K.isCollapsed=!0,K.B.start())},HTT=function(K){K.B.stop();
K.isCollapsed&&(g.ry(K.ud(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),K.isCollapsed=!1,K.U&&K.U.removeAttribute("aria-hidden"),g.vi(K.K,!1),g.vi(K.X,!0))},$Vi=function(K,R){K.J||(K.J=g.no(function(){dVu(this);
lz$(this)},R,K))},dVu=function(K){K.J&&(g.Nz.clearTimeout(K.J),K.J=null)},Fai=function(K){this.G=K},jE8=function(K,R,f){R&&(f?dY(K,R.map(function(V){return g.XZ(V,f)})):dY(K,R))},dY=function(K,R,f,V){var D=1,H=void 0,l=-1;
if(f){var F=!1;H=function(){D--;D||F||(clearTimeout(l),F=!0,f())};
l=setTimeout(function(){F=!0;f()},1E3)}R=g.Z(R||[]);
for(var c=R.next();!c.done;c=R.next())c=c.value,D++,g.PY(c,H);V&&(D++,V!==0&&K.G.sendVideoStatsEngageEvent(V,H))},hO8=function(K){g.cz.call(this,K);
var R=this;this.UF=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new Fai(this.player);this.B=new g.de(this);this.T=this.J=null;this.events=new g.de(this);this.NQ=this.EF=this.U=null;this.aY=[];g.q(this,this.B);this.B.j(this.player,"onVideoAreaChange",function(){R.publish("onVideoAreaChange")});
this.B.j(this.player,"onHideControls",function(){R.publish("onHideControls")});
this.B.j(this.player,"onShowControls",function(){R.publish("onShowControls")});
this.B.j(this.player,"resize",function(H){R.publish("resize",H)});
this.B.j(this.player,"presentingplayerstatechange",function(H){R.publish("presentingplayerstatechange",H)});
this.subscribe("presentingplayerstatechange",this.Vw,this);this.subscribe("resize",this.UX,this);this.player.C().qe.subscribe("vast_info_card_add",this.BD,this);g.q(this,this.events);this.Xt=this.createElement({V:"div",D:"video-custom-annotations"});this.K=new g.Y({V:"div",Me:["ytp-player-content","ytp-iv-player-content"]});g.q(this,this.K);g.nl(this.player,this.K.element,4);this.K.hide();this.X=new g.Y({V:"div",Me:["ytp-iv-video-content"]});g.q(this,this.X);K=this.createElement({V:"div",D:"video-annotations"});
K.appendChild(this.Xt);this.X.element.appendChild(K);this.ge()?this.load():this.player.Y("web_fix_annotations")&&(this.J=function(){R.loaded||R.mZ()||!R.ge()||(cBz(R),R.load())},this.player.addEventListener("videodatachange",this.J));
var f=this.createElement({V:"style"});(g.wE("HEAD")[0]||document.body).appendChild(f);this.addOnDisposeCallback(function(){g.kU(f)});
if(K=f.sheet){for(var V=g.Z(rBW),D=V.next();!D.done;D=V.next())K.insertRule(D.value,0);V=g.Z(yBH);for(D=V.next();!D.done;D=V.next())K.insertRule(D.value,0)}},oUH=function(K){K=K.createElement({V:"div",
Me:["annotation","annotation-type-custom"]});g.vi(K,!1);return K},Sai=function(K){var R=K.player.C();
K=K.player.getVideoData();return(R.annotationsLoadPolicy||K.annotationsLoadPolicy)===1&&!K.Av||R.qe.get(K.videoId)||g.Ot(K)||g.j7(K)?!0:!1},xV_=function(K,R){function f(F){var c=K.loadNumber;
K.T=null;K.loaded&&K.loadNumber===c&&K.player.getVideoData().videoId===V&&(F=g.wG(F)&&F.responseXML?F.responseXML:null)&&(iTE(K,F),g.dy(K.player.getRootNode(),"iv-module-loaded"))}
var V=R.videoId;g.fP()&&(f=vUB(K,f));var D={format:"XML",onFinish:f,onError:function(){K.T=null},
urlParams:{}};R.isPharma&&(D.urlParams.pharma="1");D.method="POST";D.withCredentials=!0;var H=K.player.C().qe.get(V);H&&LaE(D,H);var l=H&&(H.gh||H.RA);(H==null?0:H.gh)&&Math.random()<g.mz(K.player.C().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.A$(new g.NB("Unexpected call to loadVastInfoCards; Attempting to load annotations via cardsXml."));if(!R.OW||l)R.TT?(Math.random()<g.mz(K.player.C().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.A$(new g.NB("Unexpected call to loadVastInfoCards; Attempting to load annotations via invideo URL.")),
wau(K,R.TT,D)):(K.J=function(){if(!K.Z)K.onVideoDataChange(D);var F=K.player.getVideoData();(F==null?0:g.gQ(F))&&!K.UF&&zOS(K,F)},K.player.addEventListener("videodatachange",K.J))},EUu=function(K,R){R=!R.isCued()&&!g.G(R,1024);
K.K.dn(R);K.X.dn(R)},wau=function(K,R,f){K.Z=!0;
K.T=g.Jm(R,f)},cBz=function(K){K.J&&(K.player.removeEventListener("videodatachange",K.J),K.J=null)},azi=function(K,R){for(var f={},V=g.Z(R.attributes),D=V.next();!D.done;D=V.next())D=D.value,f[D.name]=D.nodeValue;
for(V=0;V<R.childNodes.length;V++)if(D=R.childNodes[V],g.kV(D)&&D.nodeType==1){if(f[D.tagName])var H=f[D.tagName];else if(D.tagName==="data"){D.childNodes.length>0&&(H=D.childNodes[0].nodeValue,f[D.tagName]=typeof H==="string"?H.trim():H);continue}else H=[],f[D.tagName]=H;D&&D.tagName==="TEXT"?D.childNodes.length===1&&D.childNodes[0].nodeType===3?H.push(D.childNodes[0].nodeValue):H.push(""):D&&H.push(azi(K,D))}return f},QzB=function(K){var R=K.player.getVideoData();
if(R.TT){var f=K.player.C().qe.get(R.videoId);if(f){var V={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(D,H,l){D=K.loadNumber;H=R.videoId;K.loaded&&K.loadNumber===D&&K.player.getVideoData().videoId===H&&(l=g.wG(l)&&l.responseXML?l.responseXML:null)&&iTE(K,l)}};
g.fP()&&(V.onFinish=vUB(K,V.onFinish));V.postParams={ic_only:"1"};LaE(V,f);K.Z=!0;g.Jm(R.TT,V)}}},LaE=function(K,R){K.method="POST";
K.postParams=K.postParams||{};R.RA&&(K.postParams.ic_coll=R.RA);R.gh&&(K.postParams.ic_xml=R.gh);R.GC&&(K.postParams.ic_track=R.GC)},NEW=function(K){var R=new g.Y({V:"div"});
g.vi(R.element,!1);var f=new Pm8(K.player,R.element,F7(K));g.q(f,R);R.V0(K.K.element);f.rF();return f},zOS=function(K,R){var f,V;
if(R=(f=R.getWatchNextResponse())==null?void 0:(V=f.cards)==null?void 0:V.cardCollectionRenderer)K.UF=!0,UVi(K,R),R.headerText&&K.NQ&&(f=g.ri(R.headerText),K.player.Y("player_tooltip_data_title_killswitch")?K.NQ.setAttribute("title",f):K.NQ.setAttribute("data-tooltip-title",f))},F7=function(K){if(!K.EF){var R=new Vv8(K);
g.q(K,R);var f=new g.LW(K);g.q(K,f);K.EF=new ROB(R,f,K.player.C(),K.player.getVideoData(),K.logger,K.player,K.r4)}return K.EF},iTE=function(K,R){var f=!1,V=R.getElementsByTagName("annotations");
if(V&&!(V.length<1)&&(V=V[0].getAttribute("itct"))){var D=g.wu();if(D){var H=g.LM();H&&g.DY(g.OI)(void 0,D,H,[g.SV(V)])}}R=R.getElementsByTagName("annotation");for(V=0;V<R.length;V++){H=azi(K,R[V]);D=null;try{if(H){var l=H.id,F=/.+/;var c=typeof l==="string"&&F!=null&&l!=null&&l.match(F)?l:"";var r=MA(H.type,WaS),y=MA(H.style,tLE),h=wbu(H.data),S=h.length!==0?JSON.parse(h):{};var v=H.action;H=NNS;if(v==null)var L=null;else if(g.Xp(v)){F=[];for(var E=g.Z(v),Q=E.next();!Q.done;Q=E.next()){var J=H(Q.value);
J&&F.push(J)}L=F}else{var A=H(v);L=A?[A]:[]}D=c&&r?new U2z(c,r,y,L,S):null}else D=null}catch(fB){}if(D)if(D.type==="branding"||D.type==="promotion"){H=K;F=D;var B=oUH(H),k=null;switch(F.type){case "branding":if(H.player.C().M1)break;H.player.Y("web_player_overlay_positioned_layout")?(B.setAttribute("data-overlay-order","11"),H.player.gm(B,4,!0)):H.K.element.appendChild(B);k=new lL(B,F7(H),F);break;case "promotion":g.nl(H.player,B,4),k=new fzi(B,F7(H),F)}k&&k.rF();if(H=k)g.q(K,H),K.N[D.id]=H}else if(D.type===
"card"||D.type==="drawer"){K.U||(K.U=NEW(K),g.q(K,K.U));if(D.type==="card"){B=K.U;var b=(f=D)&&f.data&&f.data.card_type;D=f.data;if(b)switch(H=D.tracking||{},H={WO:H.impression,click:H.click,close:H.close,XZ:H.teaser_impression,je:H.teaser_click},F=D.tracking_params||{},k=null,b){case "collaborator":f={id:f.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,startMs:D.start_ms,autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||
!1,U$:H,Ey:F.card?g.SV(F.card):null,lZ:F.teaser?g.SV(F.teaser):null,H9:F.icon?g.SV(F.icon):null,channelId:D.channel_id,customMessage:D.custom_message?D.custom_message:null,profileImageUrl:D.image_url,title:D.title,metaInfo:D.meta_info,url:pm({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),onClickCommand:null};fK(B,f);break;case "playlist":f={id:f.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,startMs:D.start_ms,
autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||!1,U$:H,Ey:F.card?g.SV(F.card):null,lZ:F.teaser?g.SV(F.teaser):null,H9:F.icon?g.SV(F.icon):null,gp:D.image_url,playlistVideoCount:D.playlist_video_count,customMessage:D.custom_message?D.custom_message:null,title:D.title,metaInfo:D.meta_info,url:pm({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),onClickCommand:null};fK(B,f);break;case "productListing":D.signin_url&&(k=pm({target:"current",
value:D.signin_url}));b=[];for(var M=D.offers||[],Hc=0;Hc<M.length;Hc++)b.push(new BN$(g.Y7(M[Hc].merchant),g.Y7(M[Hc].price)));f={id:f.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,startMs:D.start_ms,autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||!1,U$:H,Ey:F.card?g.SV(F.card):null,lZ:F.teaser?g.SV(F.teaser):null,H9:F.icon?g.SV(F.icon):null,imageUrl:D.image_url,displayDomain:D.display_domain?D.display_domain:
null,showLinkIcon:!!D.show_link_icon,jB:D.button_icon_url?D.button_icon_url:null,title:D.title,customMessage:D.custom_message?D.custom_message:null,url:pm({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),IpY:k,X_Z:D.signin_title?D.signin_title:void 0,u_Q:D.signin_message?D.signin_message:void 0,offers:b,onClickCommand:null};fK(B,f);break;case "simple":f={id:f.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,
startMs:D.start_ms,autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||!1,U$:H,Ey:F.card?g.SV(F.card):null,lZ:F.teaser?g.SV(F.teaser):null,H9:F.icon?g.SV(F.icon):null,imageUrl:D.image_url,displayDomain:D.display_domain?D.display_domain:null,showLinkIcon:!!D.show_link_icon,jB:D.button_icon_url?D.button_icon_url:null,title:D.title,customMessage:D.custom_message?D.custom_message:null,url:pm({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),onClickCommand:null};
fK(B,f);break;case "video":f={id:f.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,startMs:D.start_ms,autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||!1,U$:H,Ey:F.card?g.SV(F.card):null,lZ:F.teaser?g.SV(F.teaser):null,H9:F.icon?g.SV(F.icon):null,gp:D.image_url,videoDuration:D.video_duration||null,customMessage:D.custom_message?D.custom_message:null,title:D.title,metaInfo:D.meta_info,isLiveNow:!!D.is_live_now,
url:pm({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),onClickCommand:null},fK(B,f)}}else n7u(K.U,D);f=!0}}f&&(tk(K.player),K.UX())},UVi=function(K,R){var f=!1;
K.U||(K.U=NEW(K),g.q(K,K.U));for(var V=g.Z(R.cards||[]),D=V.next();!D.done;D=V.next())D=D.value,D.cardRenderer&&(IPV(K.U,D.cardRenderer),f=!0);if(f){var H;(H=K.player.getVideoData())!=null&&g.gQ(H)||(f=K.U,V=R.headerText?g.ri(R.headerText):"",g.Pa(f.bd,V),f.B&&(f.G.Y("player_tooltip_data_title_killswitch")?f.B.setAttribute("title",V):f.B.setAttribute("data-tooltip-title",V)),f.context.videoData.eventId&&(f.eventId=f.context.videoData.eventId),f.y0=R.trackingParams?g.SV(R.trackingParams):null,f.Z=
R.closeButton.infoCardIconRenderer.trackingParams?g.SV(R.closeButton.infoCardIconRenderer.trackingParams):null,f.H9=R.icon.infoCardIconRenderer.trackingParams?g.SV(R.icon.infoCardIconRenderer.trackingParams):null,K.UX());tk(K.player)}},AB$=function(K,R,f,V,D){if(!K.player.C().M1){var H=[];
R.navigationEndpoint&&g.z(R.navigationEndpoint,g.BD)&&g.z(R.navigationEndpoint,g.BD).browseId&&H.push(new E7i("openUrl","click",new zgV("/channel/"+g.z(R.navigationEndpoint,g.BD).browseId,"new",!0,!0)));var l=R.watermark.thumbnails[0];V={channel_name:R.channelName,end_ms:R.endTimeMs,image_height:l.height,image_type:1,image_url:l.url,image_width:l.width,is_mobile:!1,session_data:{annotation_id:f,ei:D,feature:"iv",itct:R.trackingParams,src_vid:V},start_ms:R.startTimeMs};if(R.subscribeButton&&g.z(R.subscribeButton,
g.XB)){V.channel_id=g.z(R.subscribeButton,g.XB).channelId;var F;R=g.z(R.subscribeButton,g.XB);l=D=null;R.subscribed?(R.subscriberCountWithUnsubscribeText&&(D=g.ri(R.subscriberCountWithUnsubscribeText)),R.subscriberCountText&&(l=g.ri(R.subscriberCountText))):(R.subscriberCountText&&(D=g.ri(R.subscriberCountText)),R.subscriberCountWithSubscribeText&&(l=g.ri(R.subscriberCountWithSubscribeText)));var c,r=((c=g.z((F=R.signInEndpoint)==null?void 0:F.commandMetadata,g.wA))==null?void 0:c.url)||"";F={subscribeText:g.ri(R.unsubscribedButtonText),
subscribeCount:D||"",unsubscribeText:g.ri(R.subscribedButtonText),unsubscribeCount:l||"",enabled:R.enabled||!1,classic:!1,subscribed:R.subscribed||!1,feature:"iv",signInUrl:r};V.standalone_subscribe_button_data=F}H=new U2z(f,"branding","branding",H,V);F=oUH(K);K.player.Y("web_player_overlay_positioned_layout")?(F.setAttribute("data-overlay-order","11"),K.player.gm(F,4,!0)):K.K.element.appendChild(F);H=new lL(F,F7(K),H);H.rF();g.q(H,H);K.N[f]=H}},vUB=function(K,R){return function(){var f=g.wW.apply(0,
arguments);
K.mZ()||K.aY.push(g.b7.sU(function(){R.apply(null,g.X(f))}))}},JB8=function(K){return K==="annotation-editor"||K==="live-dashboard"};
g.Wm.prototype.l1=g.O5(35,function(K,R){var f=g.QW(this.JV());f&&f.l1(K,R)});
var Jk={},ZK=null;g.Mz(XS,g.hF);g.w=XS.prototype;g.w.getDuration=function(){return this.duration};
g.w.play=function(K){if(K||this.U==0)this.progress=0,this.coords=this.K;else if(this.isPlaying())return!1;B0(this);this.startTime=K=g.OS();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.J=this.startTime;this.progress||this.Z6();this.Of("play");this.isPaused()&&this.Of("resume");this.U=1;var R=g.n8(this);R in Jk||(Jk[R]=this);uli();sK_(this,K);return!0};
g.w.stop=function(K){B0(this);this.U=0;K&&(this.progress=1);CTS(this,this.progress);this.onStop();this.Y0()};
g.w.pause=function(){this.isPlaying()&&(B0(this),this.U=-1,this.Of("pause"))};
g.w.uD=function(){this.U==0||this.stop(!1);this.Of("destroy");XS.ZN.uD.call(this)};
g.w.destroy=function(){this.dispose()};
g.w.A7=function(){this.Of("animate")};
g.w.Of=function(K){this.dispatchEvent(new e_S(K,this))};
g.Mz(e_S,g.fo);g.Mz(k1,XS);k1.prototype.X=function(){};
k1.prototype.A7=function(){this.X();k1.ZN.A7.call(this)};
k1.prototype.Y0=function(){this.X();k1.ZN.Y0.call(this)};
k1.prototype.Z6=function(){this.X();k1.ZN.Z6.call(this)};
g.Mz(Kp_,k1);Kp_.prototype.X=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(Vv8,g.O);g.w=Vv8.prototype;g.w.listen=function(K,R,f,V){f=(0,g.Ii)(f,V||this.K);K=g.We(K,R,f);this.U.push(K);return K};
g.w.lk=function(K,R,f,V){f=(0,g.Ii)(f,V||this.K);K=mdS(K,R,f);this.U.push(K);return K};
g.w.hs=function(K){g.tq(K);g.fa(this.U,K)};
g.w.removeAll=function(){g.tq(this.U);this.U.length=0};
g.w.uD=function(){this.removeAll();g.O.prototype.uD.call(this)};g.x($2_,g.cz);g.w=$2_.prototype;g.w.load=function(){g.cz.prototype.load.call(this);if(!nm(this)){var K=g.iu2(this.player.getVideoData());K?(K=HCV(K,lPi(this)),Ic(this,K,!1)):d2p(this)}};
g.w.unload=function(){Ic(this,null);this.J&&(this.J.abort(),this.J=null);g.cz.prototype.unload.call(this)};
g.w.OJ=function(K,R){return nm(this)?K==="loadCustomEndscreenRenderer"?(K=HCV(R,"new"),Ic(this,K),!0):null:null};
g.w.getOptions=function(){return nm(this)?["loadCustomEndscreenRenderer"]:[]};
g.w.xl=function(){if(this.endscreen&&this.endscreen.elements){var K=this.player.getVideoContentRect();if(K&&K.width!==0&&K.height!==0){var R=this.player.getPlayerSize();if(R&&R.width!==0&&R.height!==0){var f=K.width/K.height;var V=0;for(var D=-1,H=0;H<ZT8.length;H++){var l=Math.abs(R.width-ZT8[H]);if(D===-1||V>=l)D=H,V=l}V=BE$[D];this.X&&g.Ds(this.X.element,"outline-width",Math.max(R.width,R.height)+"px");for(R=0;R<this.endscreen.elements.length;++R)if(H=this.endscreen.elements[R].id,D=this.K[H],
l=this.T[H],D&&l){var F=l.width*f/l.aspectRatio,c=Math.round(l.width*K.width);H=Math.round(F*K.height);var r=K.left+Math.round(l.left*K.width),y=K.top+Math.round(l.top*K.height);g.SX(D.element,c,H);g.rB(D.element,r,y);g.ry(D.element,Xau);c>256||H>256?g.dy(D.element,"ytp-ce-large-round"):c>96||H>96?g.dy(D.element,"ytp-ce-medium-round"):g.dy(D.element,"ytp-ce-small-round");g.ry(D.element,ka_);c=l.left+l.width/2;l=l.top+F/2;g.dy(D.element,c<=.5&&l<=.5?"ytp-ce-top-left-quad":c>.5&&l<=.5?"ytp-ce-top-right-quad":
c<=.5&&l>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ry(D.element,BE$);g.dy(D.element,V);(D=g.xU(document,"div","ytp-ce-expanding-overlay-body",D.element)[0])&&g.Ds(D,"height",H+"px")}}}}};
g.w.onCueRangeEnter=function(K){if(this.endscreen)if(K.getId()==="ytp-ce-in-endscreen")qA(this,this.endscreen.impressionUrls),(K=g.wu())&&this.endscreen.visualElement&&g.ug(K,this.endscreen.visualElement),this.U&&(g.dy(this.U,"ytp-ce-element-show"),this.U.removeAttribute("aria-hidden"),this.player.v1()?g.dy(this.U,"ytp-ce-hide-button-lower"):g.c2(this.U,"ytp-ce-hide-button-lower"));else{K=K.getId().substring(15);var R=this.K[K],f=this.T[K];g.dy(R.element,"ytp-ce-element-show");R.element.removeAttribute("aria-hidden");
R=this.player.getRootNode();g.dy(R,"ytp-ce-shown");qA(this,f.impressionUrls);(R=g.wu())&&g.ug(R,f.visualElement);this.player.C().Z&&this.player.lD("endscreenelementshown",K)}};
g.w.onCueRangeExit=function(K){if(K.getId()==="ytp-ce-in-endscreen")this.U&&(g.c2(this.U,"ytp-ce-element-show"),this.U.setAttribute("aria-hidden","true"));else{K=K.getId().substring(15);var R=this.K[K];g.c2(R.element,"ytp-ce-element-show");R.element.setAttribute("aria-hidden","true");R=this.player.getRootNode();g.c2(R,"ytp-ce-shown");this.player.C().Z&&this.player.lD("endscreenelementhidden",K)}};
g.w.Fi0=function(K){var R=this;K.target===window&&(new g.CW(function(){for(var f=g.Z(Object.values(R.K)),V=f.next();!V.done;V=f.next())g.ry(V.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.w.dn=function(K){for(var R=g.Z(Object.values(this.K)),f=R.next();!f.done;f=R.next())f=f.value,K?f.element.setAttribute("hidden",""):f.element.removeAttribute("hidden")};
g.w.Rx0=function(K){this.U&&this.player.getRootNode().removeChild(this.U);K&&(g.dy(K,"ytp-ce-hide-button-container"),this.U=K,g.nl(this.player,this.U,4))};
var ZT8=[346,426,470,506,570,640,853,1280,1920],BE$="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ka_=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Xau=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var x2S={k8e:"current",yZt:"new"};var aP_={CLOSE:"close",AZ5:"openUrl",SUBSCRIBE:"subscribe"},QES={yxt:"click",CLOSE:"close",d$Z:"hidden",Yye:"rollOut",obD:"rollOver",rXY:"shown"};U2z.prototype.y9=function(){var K=WpE(this,function(R){return R.type==="openUrl"&&R.url!=null});
return K?K.url:null};
var tLE={q$W:"anchored",tq:"branding",CHANNEL:"channel",NiZ:"cta",Cme:"highlightText",Yf5:"label",PLAYLIST:"playlist",POPUP:"popup",SyU:"speech",SUBSCRIBE:"subscribe",uT5:"title",VIDEO:"video",PzZ:"website"},WaS={tq:"branding",Eqt:"card",x40:"drawer",H8U:"highlight",xlp:"marker",P5D:"promotion",TEXT:"text",mSe:"widget"};var rBW=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
yBH=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];g.x(uG,g.O);g.w=uG.prototype;g.w.addCueRange=function(K,R,f,V,D){K=new g.nQ(K,R,{id:f,namespace:"annotations_module"});V&&this.Ne.set(K,V);D&&this.kW.set(K,D);this.context.G.PV([K],1)};
g.w.rF=function(){this.context.K.subscribe("resize",this.UG,this)};
g.w.ud=function(){return this.element};
g.w.eU=function(K,R,f,V,D,H){if(this.v5)return!1;H&&(H.stopPropagation(),H.preventDefault());this.navigate(K,f,V,D);return!1};
g.w.show=function(){};
g.w.hide=function(){};
g.w.destroy=function(){g.kU(this.ud())};
g.w.UG=function(){};
g.w.navigate=function(K,R,f,V){var D=this,H=bG(K);if(H){var l=kd8(H,K.target),F=function(){K.U&&D.context.G.pauseVideo();var c=D.context.videoData.nL||!1,r=g.FN(H||"");c&&r&&(r.v||r.list)?D.context.G.V4(r.v,R,r.list,!1):g.jC(H||"",l==="current"?"_top":void 0,R)};
l==="new"&&(F(),F=null);dY(this.context.logger,f,F,V);Xbp(H)||(f=g.wu(),V=R.itct,f&&V&&g.eV(f,g.SV(V)))}};
g.w.uD=function(){this.Ne.clear();this.kW.clear();g.O.prototype.uD.call(this)};
g.w.createElement=function(K){K=new g.Y(K);g.q(this,K);return K.element};g.x(Pm8,uG);g.w=Pm8.prototype;g.w.u$=function(){this.aY&&fK(this,this.aY)};
g.w.isAvailable=function(){var K;if(K=!!this.cards.length)(K=this.G.getRootNode())?(K=g.i6(K),K=173<K.width&&173<K.height):K=!1;return K};
g.w.UG=function(){var K=this.isAvailable();g.vi(this.ud(),K);g.yb(this.context.G.getRootNode(),g.UC.IV_DRAWER_ENABLED,K);tk(this.G)};
g.w.destroy=function(){this.G.l1(!1);try{this.G.getRootNode().removeChild(this.J)}catch(K){}g.f3(this.UF);g.kc(this.G2);this.oY&&this.oY.dispose();this.T&&this.T.dispose();uG.prototype.destroy.call(this)};
g.w.Az=function(){var K=this;this.context.U.listen(g.Ea("iv-drawer-close-button",this.J),"click",this.oD,this);this.context.U.listen(this.K,"touchend",function(){K.B5.start()});
this.context.U.listen(this.K,"scroll",this.E6,this);this.context.K.subscribe("onHideControls",function(){K.qe=!0});
this.context.K.subscribe("onShowControls",function(){K.qe=!1});
this.context.K.subscribe("onVideoAreaChange",function(){K.qe=g.lp(K.G.getRootNode(),"ytp-autohide")});
this.UF.push(g.RQ("iv-button-shown",this.aZD,this));this.UF.push(g.RQ("iv-button-hidden",this.KBp,this));pbi(this)};
g.w.findLastIndex=function(K){if(this.cards.length===0)return 0;var R=g.sS(this.cards,function(f){return K.qR.startMs>f.qR.startMs||K.qR.startMs===f.qR.startMs&&K.qR.timestamp>=f.qR.timestamp?!0:!1});
return R===-1?0:R+1};
g.w.oD=function(){if(this.X){dY(this.context.logger,HU(this).U$.close);var K=g.wu();K&&this.Z&&g.eV(K,this.Z);KK(this)}};
g.w.E6=function(){g.yb(this.J,"iv-drawer-scrolled",this.K.scrollTop>0)};
g.w.aZD=function(){var K=g.wu(),R=HU(this);R=R?R.H9:this.H9;K&&R&&g.sI(K,[R])};
g.w.KBp=function(){var K=g.wu(),R=HU(this);R=R?R.H9:this.H9;K&&R&&g.CM(K,[R])};
g.w.Jw=function(){var K=HU(this);dY(this.context.logger,K.U$.XZ);var R=g.wu();if(R&&K)if(this.G.Y("web_infocards_teaser_show_logging_fix")){var f=[];K.lZ&&f.push(K.lZ);K.H9&&f.push(K.H9);f.length>0&&g.sI(R,f)}else g.sI(R,[K.lZ,K.H9])};
g.w.QG5=function(){var K=g.wu(),R=HU(this);K&&R&&g.CM(K,[R.lZ])};
g.w.yw=function(K){var R=HU(this),f=g.wu();this.U?K?(K=this.context.logger,dY(K,R.U$.je),K.G.sendVideoStatsEngageEvent(4,void 0),f&&R.lZ&&g.eV(f,R.lZ)):(K=this.context.logger,dY(K,R.U$.je),K.G.sendVideoStatsEngageEvent(4,void 0),f&&R.H9&&g.eV(f,R.H9)):(K=this.context.logger,dY(K,R.U$.je),K.G.sendVideoStatsEngageEvent(4,void 0),f&&this.H9&&g.eV(f,this.H9))};g.x($G,uG);$G.prototype.rF=function(){uG.prototype.rF.call(this);egB(this)};
$G.prototype.show=function(){uG.prototype.show.call(this);var K=g.wu(),R=this.annotation.data;K&&R&&(R=R.session_data)&&g.sI(K,[g.SV(R.itct)])};
$G.prototype.hide=function(){uG.prototype.hide.call(this);var K=g.wu(),R=this.annotation.data;K&&R&&(R=R.session_data)&&g.CM(K,[g.SV(R.itct)])};g.x(lL,$G);
lL.prototype.show=function(){if(!this.isActive){$G.prototype.show.call(this);if(!this.X){g.dy(this.ud(),"iv-branding");var K=this.annotation.data;this.U=this.createElement({V:"img",Me:["branding-img","iv-click-target"],L:{"aria-label":"Marca de agua del canal",src:K.image_url,width:K.image_width,height:K.image_height}});g.vi(this.U,!1);var R=this.createElement({V:"button",Me:["branding-img-container","ytp-button"]});R.appendChild(this.U);this.ud().appendChild(R);var f=this.annotation.y9();f&&sb(this,
R,f,this.annotation.id,K.session_data);this.X=!0}g.vi(this.ud(),!0);this.isActive=!0;if(this.U){try{KaV(this,this.U)}catch(V){}g.dy(this.context.G.getRootNode(),"ytp-branding-shown");this.context.G.getRootNode().style.setProperty("--branding-image-width",this.U.getAttribute("width")+"px")}}};
lL.prototype.hide=function(){this.isActive&&($G.prototype.hide.call(this),g.vi(this.ud(),!1),this.isActive=!1,g.c2(this.context.G.getRootNode(),"ytp-branding-shown"))};
lL.prototype.destroy=function(){this.K&&(this.K.dispose(),this.K=null);g.c2(this.context.G.getRootNode(),"ytp-branding-shown");$G.prototype.destroy.call(this)};g.x(fzi,$G);g.w=fzi.prototype;g.w.show=function(){this.isActive||($G.prototype.show.call(this),this.EF||(DVz(this),this.EF=!0),g.vi(this.ud(),!0),g.no(function(){g.c2(this.ud(),"iv-promo-inactive")},100,this),this.ud().removeAttribute("aria-hidden"),this.isActive=!0,dVu(this),HTT(this),$Vi(this,this.T))};
g.w.hide=function(){this.isActive&&(g.dy(this.ud(),"iv-promo-inactive"),this.isActive=!1,this.ud().setAttribute("aria-hidden","true"))};
g.w.eU=function(K,R,f,V,D,H){return this.isCollapsed?!1:$G.prototype.eU.call(this,K,R,f,V,D,H)};
g.w.Sn=function(K){this.Z=!0;VLi(this,500,K)};
g.w.x$=function(){this.Z=!1;lz$(this)};
g.w.Hm=function(K){K.stopPropagation();this.hide()};
g.w.Ce=function(K){K.stopPropagation();dVu(this);this.isCollapsed=!0;g.dy(this.ud(),"iv-promo-collapsed-no-delay");this.B.start()};
g.w.destroy=function(){this.B.dispose();$G.prototype.destroy.call(this)};g.x(hO8,g.cz);g.w=hO8.prototype;g.w.OJ=function(K,R){if(!JB8(this.player.C().playerStyle))return null;switch(K){case "loadCustomAnnotationsXml":return(K=g.pR(R))&&iTE(this,K),!0;case "removeCustomAnnotationById":return R&&this.U&&(OCi(this.U,R),tk(this.player)),!0}return null};
g.w.getOptions=function(){return JB8(this.player.C().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.w.ge=function(){var K=this.player.getVideoData(),R,f,V=(R=K.getWatchNextResponse())==null?void 0:(f=R.playerOverlays)==null?void 0:f.playerOverlayRenderer;if(K.nL||this.player.isMutedByEmbedsMutedAutoplay())return!1;if(!this.player.Y("web_fix_annotations"))return Sai(this);if(Sai(this)){if((V==null?void 0:V.isWatermarkEnforced)===!0)return!0;var D;return(D=V==null?void 0:V.isAnnotationsEnabled)!=null?D:!1}return!1};
g.w.UX=function(){if(this.X){var K=this.player.Ft().getVideoContentRect(!0);g.SX(this.X.element,K.width,K.height);g.rB(this.X.element,K.left,K.top)}if(this.U){var R=this.player.OT();K=this.U;R=R.width;g.yb(K.J,"iv-drawer-small",R<=426);g.yb(K.J,"iv-drawer-big",R>=1280)}};
g.w.Vw=function(K){EUu(this,K.state);g.G(K.state,2)&&(this.v1()&&this.i5()&&this.player.getPresentingPlayerType()!==2&&this.rI(!1),this.l1(!1))};
g.w.load=function(){g.cz.prototype.load.call(this);EUu(this,this.player.getPlayerStateObject());this.loadNumber++;var K=this.player.getVideoData();xV_(this,K);g.nl(this.player,this.X.element,4);this.UX();var R=g.j7(K),f=g.Ot(K);if(this.player.Y("web_fix_annotations")){if(R){R.featuredChannel&&AB$(this,R.featuredChannel,R.annotationId||"branding",K.videoId||null,K.eventId||null);var V,D;R=(V=this.player.getVideoData().getWatchNextResponse())==null?void 0:(D=V.playerOverlays)==null?void 0:D.playerOverlayRenderer;
if(R!=null&&R.isWatermarkEnforced&&(R==null||!R.isAnnotationsEnabled))return}f&&UVi(this,f)}else f&&UVi(this,f),R&&R.featuredChannel&&AB$(this,R.featuredChannel,R.annotationId||"branding",K.videoId||null,K.eventId||null);this.NQ=g.Ea("ytp-cards-button",this.player.getRootNode());g.gQ(K)&&zOS(this,K)};
g.w.onVideoDataChange=function(K){var R=this.player.getVideoData();R.TT&&wau(this,R.TT,K)};
g.w.unload=function(){this.player.BV("annotations_module");for(var K=g.Z(Object.keys(this.N)),R=K.next();!R.done;R=K.next())this.N[R.value].destroy();this.EF=null;this.U&&(this.U.destroy(),this.U=null,tk(this.player));this.Z=!1;this.T&&(this.T.abort(),this.T=null);this.UF=!1;this.N={};this.K.hide();g.cz.prototype.unload.call(this);this.X.detach();cBz(this)};
g.w.BD=function(K){K===this.player.getVideoData().videoId&&(this.loaded?QzB(this):this.load())};
g.w.v1=function(){var K;return((K=this.U)==null?void 0:K.isAvailable())||this.UF};
g.w.i5=function(){return!!this.U&&this.U.X};
g.w.rI=function(K,R,f){R=R===void 0?!1:R;this.v1();this.U&&(K?f?eP(this.U,f,R):eP(this.U,"YOUTUBE_DRAWER_AUTO_OPEN",R):KK(this.U))};
g.w.l1=function(K,R){this.player.publish(K?"cardsteasershow":"cardsteaserhide",R)};
g.w.uD=function(){this.player.C().qe.unsubscribe("vast_info_card_add",this.BD,this);g.c2(this.player.getRootNode(),g.UC.IV_DRAWER_OPEN);for(var K=this.aY,R=g.b7,f=0,V=K.length;f<V;f++)R.SQ(K[f]);this.aY.length=0;g.cz.prototype.uD.call(this)};
g.w.createElement=function(K){K=new g.Y(K);g.q(this,K);return K.element};g.Fk("annotations_module",hO8);g.Fk("creatorendscreen",$2_);})(_yt_player);
