(function(g){var window=this;'use strict';var nUS=function(K,R,f){g.I(function(V){K.K=g.Jm(R,f);g.lE(V)})},cU=function(K){K.isActive()||K.start()},Iz$=function(K,R){return R?K.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},gUW=function(K){return g.fc(K)||K.Y("web_enable_caption_language_preference_stickiness")},OT$=function(K,R){var f=new g.zj;
f.languageCode=K.languageCode;f.languageName=K.languageName;f.name=K.name;f.displayName=K.displayName;f.kind=K.kind;f.isDefault=!1;f.U=K.U;f.isTranslateable=K.isTranslateable;f.vssId=K.vssId;f.url=K.url;f.translationLanguage=R;K.xtags&&(f.xtags=K.xtags);K.captionId&&(f.captionId=K.captionId);return f},jzT=function(K,R){var f,V,D;
return g.I(function(H){if(H.U==1)return f=K+"|"+R,g.P(H,g.e1(),2);if(H.U!=3){V=H.K;if(!V)throw g.wT("gct");return g.P(H,g.O2(V),3)}D=H.K;return H.return(D.get("captions",f))})},qa8=function(K,R,f){jzT(K,R).then(function(V){V&&f(V.trackData,new g.zj(V.metadata))})},pai=function(K){if(!ML$.test(K))throw Error("'"+K+"' is not a valid hex color");
K.length==4&&(K=K.replace(bTS,"#$1$1$2$2$3$3"));K=K.toLowerCase();K=parseInt(K.slice(1),16);return[K>>16,K>>8&255,K&255]},Ya8=function(){var K=void 0;
K=K===void 0?{}:K;var R="suggest_correction"in g.c_T?g.c_T.suggest_correction:"Edit caption";R=R||"";var f={},V;for(V in K){f={o8:f.o8};f.o8=V;var D=function(H){return function(){return String(K[H.o8])}}(f);
R=R.replace(new RegExp("\\$\\{"+f.o8+"\\}","gi"),D);R=R.replace(new RegExp("\\$"+f.o8,"gi"),D)}return R},mVu=function(){return g.n4("yt-player-caption-display-settings")},Ga8=function(K){g.yW.call(this,K);
this.K=new Set},rY=function(){this.segments=[]},uUz=function(K,R){var f=g.hh(K.segments,R);
f>=0||f<0&&(-f-1)%2===1||(f=-f-1,f>0&&R-K.segments[f-1]===1&&f<K.segments.length&&K.segments[f]-R===1?(g.RK(K.segments,f),g.RK(K.segments,f-1)):f>0&&R-K.segments[f-1]===1?K.segments[f-1]=R:f<K.segments.length&&K.segments[f]-R===1?K.segments[f]=R:(g.rJ(K.segments,f,0,R),g.rJ(K.segments,f+1,0,R)))},szu=function(K,R,f,V,D,H){g.O.call(this);
this.policy=K;this.player=R;this.RY=f;this.Z=V;this.B=D;this.EF=H;this.J=new rY;this.T=-1;this.K=this.X=this.U=null;this.UF=0;this.N=new g.CW(this.O4,1E3,this);this.events=new g.de(this);g.q(this,this.N);g.q(this,this.events);this.events.j(R,"SEEK_COMPLETE",this.jS);this.jS();this.O4()},CuS=function(K){return K.U&&K.U.B?K.U.B+K.player.jy()<K.player.getCurrentTime():!1},eOW=function(K,R){if(K.policy.kL&&K.player.iT()){var f=g.ll(R,K.policy,{});
f.set("pot",K.player.iT());f=f.y9()}else f=g.ll(R,K.policy,{}).y9();var V={format:"RAW",withCredentials:!0};if(K.policy.G2){V.method="POST";var D=R.J;D&&Object.keys(D).length>0?V.postBody=g.gS(D,g.vM):V.postBody=(0,g.Ph)([120,0])}K.B&&(V.responseType="arraybuffer");var H=++K.UF,l=(0,g.N7)();K.K=g.kA(f,V,3,100,-1,function(F){F.errorCode==="net.timeout"&&K.player.KQ("capnt",{rn:H++})}).then(function(F){if(K.policy.FOQ&&H%100===1){var c=(0,g.N7)();
K.player.KQ("caprsp",{rn:H,ms:c-l,kb:(F.xhr.responseText.length/1024).toFixed()})}a:{F=F.xhr;K.mZ();if(K.X){var r=!(K.B?F.response:F.responseText)||F.status>=400;if(c=g.luD(F)){F=g.ll(K.X,K.policy,{});K.X.xV(F,c);eOW(K,K.X);break a}if(r)K.player.KQ("capfail",{status:F.status});else{var y;g.tL("fcb_r",(0,g.N7)(),((y=K.player.getVideoData())==null?void 0:y.EF)||"");y=K.X.xW[0];c=y.t5;K.Z!=null&&K.T!==c&&(K.B?K.Z(F.response,(y.startTime+K.player.jy())*1E3):K.Z(F.responseText,(y.startTime+K.player.jy())*
1E3),K.T=c)}}K.X=null;K.K=null}}).rk(function(F){K.X=null;
K.K=null;var c;K.player.KQ("capfail",{rn:H,status:(c=F.xhr)==null?void 0:c.status})});
K.X=R;uUz(K.J,K.X.xW[0].t5)},y$=function(K,R){g.yW.call(this,R);
this.K=K;this.G=R;this.J=null;this.T=!1;this.logger=new g.vf("caps");this.N=g.Wn5(this.G,this.K)},RKS=function(K,R){var f=[],V;
for(V in K.K.U)if(K.K.U.hasOwnProperty(V)){var D=K.K.U[V];if(g.o$(D,R||null)){var H=D.info.id,l=H,F="."+H,c="",r="";if(D=D.info.captionTrack)H=D.languageCode,l=D.displayName,F=D.vssId,c=D.kind,r=D.id;else{D=H;var y=g.ZaW.get(D);y==null&&(y=KbS[D]||KbS[D.replace(/-/g,"_")],g.ZaW.set(D,y));D=y;l=D||l}f.push(new g.zj({id:V,languageCode:H,languageName:l,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:F,kind:c,captionId:r}))}}return f},fsS=function(K,R){return R!=null&&R in K.K.U?K.K.U[R]:null},
VXV=function(K,R,f){var V=[],D;
for(D in K.K.U)if(K.K.U.hasOwnProperty(D)){var H=K.K.U[D];if(g.o$(H,f||null)){var l=H.info.captionTrack;l&&l.languageCode===R&&V.push(H)}}return V.length?V[0]:null},h9=function(K,R,f,V,D,H,l,F,c,r){var y=r.isInline()&&!0,h={};
Object.assign(h,R);Object.assign(h,K.params);Object.assign(h,f);var S={};Object.assign(S,R.xB);K.params.xB&&Object.assign(S,K.params.xB);Object.assign(S,f.xB);y&&(h.windowOpacity=.6,S.backgroundOpacity=0);h.xB=S;var v=h.Gs===1,L=[{V:"span",D:"captions-text",L:{style:"word-wrap: normal; display: block;"}}],E,Q,J;(F=F.rU("caption_edit_on_hover")&&((E=r.getVideoData().getPlayerResponse())==null?void 0:(Q=E.captions)==null?void 0:(J=Q.playerCaptionsTracklistRenderer)==null?void 0:J.openTranscriptCommand))&&
L.unshift({V:"button",D:"caption-edit",L:{tabindex:"0","aria-label":Ya8()},S:[{V:"svg",L:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},S:[{V:"path",L:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.Y.call(this,{V:"div",D:"caption-window",L:{id:"caption-window-"+K.id,dir:v?"rtl":"ltr",tabindex:"0",lang:h.lang},S:L});var A=
this;this.T=[];this.y0=!1;this.K=K;this.qe=this.er=null;this.aQ=H;this.vK=l;this.N=null;this.maxWidth=H*.96;this.maxHeight=l*.96;this.U=h;this.XQ=f;this.aY=R;this.J=this.IY("captions-text");this.hV=this.J.style.getPropertyValue("box-decoration-break")!==""||this.J.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.oY=D8V(V,D,H,l);this.nh=c;F&&(this.B=this.IY("caption-edit"),this.j(this.B,"click",function(){A.nh()}));
this.type=0;this.Ne=this.oY*HU_(S);this.pQ=y;K=new g.UM(this.element,!0);g.q(this,K);K.subscribe("dragstart",this.Mm,this);K.subscribe("dragmove",this.hw,this);K.subscribe("dragend",this.B3,this);this.Za=this.kW=this.v5=this.OF=0;K="";this.U.windowOpacity&&(K=pai(this.U.windowColor),K="rgba("+K[0]+","+K[1]+","+K[2]+","+this.U.windowOpacity+")");R={"background-color":K,display:this.U.isVisible===!1?"none":"","text-align":$8E[this.U.textAlign]};this.hV&&(R["border-radius"]=K?this.Ne/8+"px":"");(this.X=
this.K.params.Gs===2||this.K.params.Gs===3)&&ls8(this,this.element);g.Ds(this.element,R);if(y){var B;(B=this.element.parentElement)==null||B.style.setProperty("--caption-window-color",K)}switch(this.U.oM){case 0:case 1:case 2:g.dy(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.dy(this.element,"ytp-caption-window-bottom")}},ls8=function(K,R){var f="vertical-rl";
K.U.Dv===1&&(f="vertical-lr");g.ip&&(f=f==="vertical-lr"?"tb-lr":"tb-rl");g.Ds(R,"-o-writing-mode",f);g.Ds(R,"-webkit-writing-mode",f);g.Ds(R,"writing-mode",f);g.Ds(R,"text-orientation","upright");g.dy(R,"ytp-vertical-caption");K.K.params.Gs===3&&(g.Ds(R,"text-orientation",""),g.Ds(R,"transform","rotate(180deg)"))},HU_=function(K){var R=1+.25*(K.fontSizeIncrement||0);
if(K.offset===0||K.offset===2)R*=.8;return R},d8_=function(K,R){var f={},V=R.background?R.background:K.U.xB.background;
if(R.backgroundOpacity!=null||R.background){var D=R.backgroundOpacity!=null?R.backgroundOpacity:K.U.xB.backgroundOpacity;V=pai(V);f.background="rgba("+V[0]+","+V[1]+","+V[2]+","+D+")";K.hV&&(f["box-decoration-break"]="clone",f["border-radius"]=K.Ne/8+"px")}if(R.fontSizeIncrement!=null||R.offset!=null)f["font-size"]=K.oY*HU_(R)+"px";V=1;D=R.color||K.U.xB.color;if(R.color||R.textOpacity!=null)D=pai(D),V=R.textOpacity==null?K.U.xB.textOpacity:R.textOpacity,D="rgba("+D[0]+","+D[1]+","+D[2]+","+V+")",
f.color=D,f.fill=D;var H=R.charEdgeStyle;H===0&&(H=void 0);if(H){D="rgba(34, 34, 34, "+V+")";var l="rgba(204, 204, 204, "+V+")";R.vk&&(l=D=R.vk);var F=K.oY/16/2,c=Math.max(F,1),r=Math.max(2*F,1),y=Math.max(3*F,1),h=Math.max(5*F,1);V=[];switch(H){case 4:for(;y<=h;y+=F)V.push(r+"px "+r+"px "+y+"px "+D);break;case 1:r=window.devicePixelRatio>=2?.5:1;for(H=c;H<=y;H+=r)V.push(H+"px "+H+"px "+D);break;case 2:V.push(c+"px "+c+"px "+l);V.push("-"+c+"px -"+c+"px "+D);break;case 3:for(y=0;y<5;y++)V.push("0 0 "+
r+"px "+D)}f["text-shadow"]=V.join(", ")}D="";switch(R.fontFamily){case 1:D='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:D='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:D='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:D='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:D='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:D=g.uj()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:D='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}D&&(f["font-family"]=D);D=R.offset;D==null&&(D=K.U.xB.offset);switch(D){case 0:f["vertical-align"]="sub";break;case 2:f["vertical-align"]="super"}R.fontFamily===7&&(f["font-variant"]="small-caps");R.bold&&(f["font-weight"]="bold");R.italic&&(f["font-style"]="italic");R.underline&&(f["text-decoration"]=
"underline");R.BUU&&(f.visibility="hidden");R.Su===1&&K.X&&(f["text-combine-upright"]="all",f["text-orientation"]="mixed",D=g.$_||g.v7,K.K.params.Gs===3?f.transform=D?"rotate(90deg)":"rotate(180deg)":D&&(f.transform="rotate(-90deg)"));if(R.textEmphasis===1||R.textEmphasis===2||R.textEmphasis===3||R.textEmphasis===4||R.textEmphasis===5)if(g.$_)f["font-weight"]="bold";else switch(f["text-emphasis-style"]="filled circle",f["text-emphasis-color"]="currentcolor",f["webkit-text-emphasis"]="filled circle",
R.textEmphasis){case 4:case 3:f["text-emphasis-position"]="under left";f["webkit-text-emphasis-position"]="under left";break;case 5:case 2:f["text-emphasis-position"]="over right",f["webkit-text-emphasis-position"]="over right"}return f},oe=function(K){K=K.split("px");
return K.length>0?(K=Number(K[0]))?K:0:0},Fb$=function(K){K.N=g.tB("SPAN");
g.Ds(K.N,{display:"block"});g.dy(K.N,"caption-visual-line");K.J.appendChild(K.N)},cQp=function(K,R){var f=g.tB("SPAN");
g.Ds(f,{display:"inline-block","white-space":"pre-wrap"});g.Ds(f,d8_(K,R));f.classList.add("ytp-caption-segment");K.N.appendChild(f);f.previousElementSibling&&(g.Ds(f.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ds(f,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return f},rQ8=function(K,R,f){K.y0=K.y0||!!f;
var V={};Object.assign(V,K.U.xB);Object.assign(V,f||R.U);Object.assign(V,K.XQ.xB);(f=!K.N)&&Fb$(K);for(var D=K.er&&K.qe&&g.Xl(V,K.qe)?K.er:cQp(K,V),H=typeof R.text==="string",l=H?R.text.split("\n"):[R.text],F=0;F<l.length;F++){var c=F>0||!R.append,r=l[F];c&&!f?(Fb$(K),D=cQp(K,V)):c&&f&&(f=!1);r&&(D.appendChild(H?g.AB(r):r),H||r.tagName!=="RUBY"||r.childElementCount!==4||g.$_||!g.l6(r.children[2],"text-emphasis")||(c=K.X?"padding-right":"padding-top",g.l6(r.children[2],"text-emphasis-position")&&(c=
K.X?"padding-left":"padding-bottom"),g.QJ?g.Ds(D,c,"1em"):g.Ds(D,c,"0.5em")))}K.qe=V;K.er=D;K.T.push(R)},D8V=function(K,R,f,V){var D=R/360*16;
R>=K&&(K=640,V>f*1.3&&(K=480),D=f/K*16);return D},hKW=function(){this.X=this.time=this.mode=this.K=0;
this.J=new yQB(this);this.B=new yQB(this);this.U=[];this.clear()},SYS=function(K,R,f){if(K===255&&R===255||!K&&!R)return{VU:K,
s2:R,result:0};K=oOE[K];R=oOE[R];if(K&128){var V;if(V=!(R&128))V=R,V=f.e4()&&f.s2===V;if(V)return{VU:K,s2:R,result:1}}else if(R&128&&1<=K&&K<=31)return{VU:K,s2:R,result:2};return{VU:K,s2:R,result:3}},vOV=function(K,R,f,V){R===255&&f===255||!R&&!f?(++K.X===45&&K.reset(),K.J.K.clear(),K.B.K.clear()):(K.X=0,iU8(K.J,R,f,V))},LbS=function(K,R){K.U.sort(function(D,H){var l=D.time-H.time;
return l===0?D.order-H.order:l});
for(var f=g.Z(K.U),V=f.next();!V.done;V=f.next())V=V.value,K.time=V.time,V.type===0?vOV(K,V.T0,V.Dy,R):V.type===1&&K.K&496&&iU8(K.B,V.T0,V.Dy,R);K.U.length=0},SW=function(){this.type=0},iL=function(){this.state=this.s2=this.VU=0},wiV=function(){this.timestamp=this.U=0},vU=function(K){this.B=K;
this.X=[];this.U=this.K=this.row=0;this.style=new SW;for(K=this.J=0;K<=15;K++){this.X[K]=[];for(var R=0;R<=32;R++)this.X[K][R]=new wiV}},LK=function(K,R){if(K.style.type===3){for(var f=0,V=0,D=K.B.time+0,H="",l="",F=D,c=1;c<=15;++c){for(var r=!1,y=V?V:1;y<=32;++y){var h=K.X[c][y];
if(h.U!==0){f===0&&(f=c,V=y);r=String.fromCharCode(h.U);var S=h.timestamp;S<D&&(D=S);h.timestamp=F;l&&(H+=l,l="");H+=r;r=!0}if((h.U===0||y===32)&&r){l="\n";break}else if(V&&!r)break}if(f&&!r)break}H&&R.J(f,V,D,F,H)}else for(V=f=0,H=D=K.B.time+0,l=1;l<=15;++l)for(F="",c=1;c<=32;++c)if(y=K.X[l][c],h=y.U,h!==0&&(f===0&&(f=l,V=c),r=String.fromCharCode(h),S=y.timestamp,S<=D&&(D=S),F+=r,y.reset()),c===32||h===0)F&&R.J(f,V,D,H,F),D=H,F="",V=f=0},Qsu=function(K,R){switch(K){case 0:return zK$[(R&127)-32];
case 1:return x8H[R&15];case 2:return EOp[R&31];case 3:return asT[R&31]}return 0},wY=function(K){return K.X[K.row][K.K]},zS=function(K,R,f){R>=2&&K.K>1&&(--K.K,wY(K).U=0);
var V=wY(K);V.timestamp=K.B.time+0;V.U=Qsu(R,f);K.K<32&&K.K++},NBp=function(K,R,f,V){for(var D=0;D<V;D++)for(var H=0;H<=32;H++){var l=K.X[R+D][H],F=K.X[f+D][H];
l.U=F.U;l.timestamp=F.timestamp}},xG=function(K,R,f){for(var V=0;V<f;V++)for(var D=0;D<=32;D++)K.X[R+V][D].reset()},U8T=function(K){K.row=K.U>0?K.U:1;
K.K=1;xG(K,0,15)},Wbi=function(K){this.X=K;
this.B=0;this.style=new SW;this.T=new vU(this.X);this.N=new vU(this.X);this.text=new vU(this.X);this.K=this.T;this.J=this.N;this.U=this.K},tX8=function(K,R,f){var V=K.K,D=!1;
switch(K.style.get()){case 4:case 1:case 2:K.style.get()===4&&V.U>0||(LK(V,f),U8T(K.K),U8T(K.J),V.row=15,V.U=R,D=!0)}K.style.set(3);K.U=V;K.U.style=K.style;K.X.mode=1<<V.J;D?V.K=1:V.U!==R&&(V.U>R?(LK(V,f),xG(V,V.row-V.U,R)):V.row<R&&(R=V.U),V.U=R)},AQ_=function(K){K.style.set(1);
K.U=K.J;K.U.U=0;K.U.style=K.style;K.X.mode=1<<K.U.J},JQB=function(K){K.style.set(4);
K.U=K.text;K.U.style=K.style;K.X.mode=1<<K.U.J},yQB=function(K){this.U=K;
this.B=0;this.X=new Wbi(this.U);this.T=new Wbi(this.U);this.K=new iL;this.J=this.X},iU8=function(K,R,f,V){K.K.update();
R=SYS(R,f,K.K);switch(R.result){case 0:return;case 1:case 2:return}var D=R.VU;f=R.s2;if(32<=D||!D)K.U.mode&K.U.K&&(R=D,R&128&&(R=127),f&128&&(f=127),K=K.J.U,R&96&&zS(K,0,R),f&96&&zS(K,0,f),R!==0&&f!==0&&K.style.type===3&&LK(K,V));else if(D&16)a:if(!K.K.matches(D,f)&&(R=K.K,R.VU=D,R.s2=f,R.state=2,R=D&8?K.T:K.X,K.J=R,K.U.mode=1<<(K.B<<2)+(R.B<<1)+(R.style.type===4?1:0),(K.U.mode|1<<(K.B<<2)+(R.B<<1)+(R.style.type!==4?1:0))&K.U.K))if(f&64){V=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(D&7)<<1|f>>5&1];
K=f&16?((f&14)>>1)*4:0;f=R.U;switch(R.style.get()){case 4:V=f.row;break;case 3:if(V!==f.row){if(V<f.U&&(V=f.U,V===f.row))break;var H=1+f.row-f.U,l=1+V-f.U;NBp(f,l,H,f.U);R=H;D=f.U;l<H?(H=l+D-H,H>0&&(R+=H,D-=H)):(H=H+D-l,H>0&&(D-=H));xG(f,R,D)}}f.row=V;f.K=K+1}else switch(D&7){case 1:switch(f&112){case 32:zS(R.U,0,32);break a;case 48:f===57?(V=R.U,wY(V).U=0,V.K<32&&V.K++):zS(R.U,1,f&15)}break;case 2:f&32&&zS(R.U,2,f&31);break;case 3:f&32&&zS(R.U,3,f&31);break;case 4:case 5:if(32<=f&&f<=47)switch(f){case 32:AQ_(R);
break;case 33:V=R.U;V.K>1&&(--V.K,wY(V).U=0);break;case 36:V=R.U;R=wY(V);for(K=0;K<=15;K++)for(f=0;f<=32;f++)if(V.X[K][f]===R){for(;f<=32;f++)V.X[K][f].reset();break}break;case 37:tX8(R,2,V);break;case 38:tX8(R,3,V);break;case 39:tX8(R,4,V);break;case 40:zS(R.U,0,32);break;case 41:R.style.set(2);R.U=R.K;R.U.U=0;R.U.style=R.style;R.X.mode=1<<R.U.J;break;case 42:V=R.text;V.U=15;V.style.set(4);U8T(V);JQB(R);break;case 43:JQB(R);break;case 44:K=R.K;switch(R.style.get()){case 1:case 2:case 3:LK(K,V)}xG(K,
0,15);break;case 45:b:{K=R.U;switch(R.style.get()){default:case 2:case 1:break b;case 4:if(K.row<15){++K.row;K.K=1;break b}break;case 3:}K.U<2&&(K.U=2,K.row<K.U&&(K.row=K.U));R=K.row-K.U+1;LK(K,V);NBp(K,R,R+1,K.U-1);xG(K,K.row,1)}break;case 46:xG(R.J,0,15);break;case 47:LK(R.K,V),R.J.updateTime(R.X.time+0),V=R.J,R.J=R.K,R.K=V,AQ_(R)}break;case 7:switch(f){case 33:case 34:case 35:V=R.U,(V.K+=f&3)>32&&(V.K=32)}}},ZUW=function(){},ET=function(K,R,f,V,D,H,l){H=H===void 0?!1:H;
l=l===void 0?null:l;g.nQ.call(this,K,K+R,{priority:f,namespace:"captions"});this.windowId=V;this.text=D;this.append=H;this.U=l},Xi_=function(K,R,f,V,D,H,l){var F=H[0],c=l[F.getAttribute("p")];
if(c.K7===1){var r=H[1],y=H[2];H=H[3];F.getAttribute("t");r.getAttribute("t");y.getAttribute("t");H.getAttribute("t");F.getAttribute("p");r.getAttribute("p");H.getAttribute("p");l=l[y.getAttribute("p")];F=BB8(F.textContent,r.textContent,y.textContent,H.textContent,l);return new ET(K,R,D,f,F,V,c)}switch(c.K7){case 9:case 10:c.textEmphasis=1;break;case 11:c.textEmphasis=2;break;case 12:c.textEmphasis=3;break;case 13:c.textEmphasis=4;break;case 14:c.textEmphasis=5}return new ET(K,R,D,f,F.textContent||
"",V,c)},BB8=function(K,R,f,V,D){var H=g.uj(),l=H?g.tB("DIV"):g.tB("RUBY"),F=g.tB("SPAN");
F.textContent=K;l.appendChild(F);K=H?g.tB("DIV"):g.tB("RP");K.textContent=R;l.appendChild(K);R=H?g.tB("DIV"):g.tB("RT");R.textContent=f;l.appendChild(R);f=D.K7;if(f===10||f===11||f===12||f===13||f===14)if(g.Ds(R,"text-emphasis-style","filled circle"),g.Ds(R,"text-emphasis-color","currentcolor"),g.Ds(R,"webkit-text-emphasis","filled circle"),D.K7===11||D.K7===13)g.Ds(R,"webkit-text-emphasis-position","under left"),g.Ds(R,"text-emphasis-position","under left");f=!0;if(D.K7===4||D.K7===7||D.K7===12||
D.K7===14)g.Ds(l,"ruby-position","over"),g.Ds(l,"-webkit-ruby-position","before");else if(D.K7===5||D.K7===6||D.K7===11||D.K7===13)g.Ds(l,"ruby-position","under"),g.Ds(l,"-webkit-ruby-position","after"),f=!1;D=H?g.tB("DIV"):g.tB("RP");D.textContent=V;l.appendChild(D);H&&(V=f,g.Ds(l,{display:"inline-block",position:"relative"}),H=l.firstElementChild.nextElementSibling,g.Ds(H,"display","none"),H=H.nextElementSibling,g.Ds(H,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Ds(l.lastElementChild,"display","none"),V?(g.Ds(l,"padding-top","0.6em"),g.Ds(H,"top","0")):(g.Ds(l,"padding-bottom","0.6em"),g.Ds(H,"bottom","0")));return l},ae=function(){g.O.apply(this,arguments)},Q$=function(K,R,f,V,D){g.nQ.call(this,K,K+R,{priority:f,
namespace:"captions"});this.id=V;this.params=D;this.U=[]},k4V=function(K){var R="_"+NM++;
return new Q$(0,0x8000000000000,0,R,K)},UT=function(K){ae.call(this);
this.J=K;this.pens={};this.Z={};this.EF={};this.B="_"+NM++;this.N={};this.K=this.U=null;this.T=!0},WU=function(K,R){K=K.getAttribute(R);
if(K!=null)return Number(K)},t9=function(K,R){K=K.getAttribute(R);
if(K!=null)return K==="1"},A9=function(K,R){K=WU(K,R);
return K!==void 0?K:null},Z0=function(K,R){K=K.getAttribute(R);
if(K!=null)return J9.test(K),K},TBE=function(K,R){var f={},V=R.getAttribute("ws");
Object.assign(f,V?K.EF[V]:K.J);K=A9(R,"mh");K!=null&&(f.Kq=K);K=A9(R,"ju");K!=null&&(f.textAlign=K);K=A9(R,"pd");K!=null&&(f.Gs=K);K=A9(R,"sd");K!=null&&(f.Dv=K);K=Z0(R,"wfc");K!=null&&(f.windowColor=K);R=WU(R,"wfo");R!==void 0&&(f.windowOpacity=R/255);return f},P6u=function(K,R){var f={},V=R.getAttribute("wp");
V&&Object.assign(f,K.Z[V]);K=A9(R,"ap");K!=null&&(f.oM=K);K=WU(R,"cc");K!=null&&(f.j8=K);K=WU(R,"ah");K!=null&&(f.gi=K);K=WU(R,"rc");K!=null&&(f.ZL=K);R=WU(R,"av");R!=null&&(f.kE=R);return f},nOi=function(K,R,f,V){var D={};
Object.assign(D,P6u(K,R));Object.assign(D,TBE(K,R));V?g.Xl(D,K.J)?(V=K.B,D=K.J):V="_"+NM++:V=R.getAttribute("id")||"_"+NM++;K=WU(R,"t")+f;R=WU(R,"d")||0x8000000000000;if(D.Gs===2||D.Gs===3)f=D.ZL,D.ZL=D.j8,D.j8=f;return new Q$(K,R,0,V,D)},BU=function(K){ae.call(this);
this.T=K;this.U=new Map;this.J=new Map;this.B=new Map;this.K=new Map},X7=function(K){K=g.fT(Math.round(K),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-K.length)+K},IsW=function(K,R,f,V,D){V===0&&(V=0x8000000000000);
var H={};R.wpWinPosId&&Object.assign(H,K.J.get(R.wpWinPosId));R.wsWinStyleId&&Object.assign(H,K.B.get(R.wsWinStyleId));K=R.rcRowCount;K!==void 0&&(H.ZL=K);R=R.ccColCount;R!==void 0&&(H.j8=R);if(H.Gs===2||H.Gs===3)R=H.ZL,H.ZL=H.j8,H.j8=R;return new Q$(f,V,0,D,H)},kG=function(K,R,f){g.yW.call(this,K);
this.videoData=R;this.audioTrack=f;this.B=R.IA},TS=function(K,R,f,V,D,H,l,F,c,r){h9.call(this,K,R,f,V,D,H,l,F,c,r);
this.type=1},PU=function(K,R,f){this.trackData=K;
this.T=f;this.version=this.B=this.X=this.byteOffset=0;this.K=[];this.U=new DataView(this.trackData)},nK=function(K){var R=K.byteOffset;
K.byteOffset+=1;return K.U.getUint8(R)},Ie=function(K){var R=K.byteOffset;
K.byteOffset+=4;return K.U.getUint32(R)},gY=function(K,R){ae.call(this);
this.K=K;this.J=R;this.track=this.J.languageName==="CC3"?4:0;this.U=new hKW;this.U.K=1<<this.track},OUp=function(K){if(typeof K==="string")return!1;
K=new PU(K,8,0);return gOi(K)},gOi=function(K){if(!(K.byteOffset<K.U.byteLength)||Ie(K)!==1380139777)return!1;
K.version=nK(K);if(K.version>1)return!1;nK(K);nK(K);nK(K);return!0},OT=function(K,R,f,V,D,H,l,F,c,r){h9.call(this,K,R,f,V,D,H,l,F,c,r);
var y=this;this.type=2;this.Xt=[];this.UF=this.Z=this.G2=0;this.B5=NaN;this.bd=0;this.Gt=null;this.Kh=new g.CW(this.t8,433,this);this.B&&(r.createClientVe(this.B,this,167342),this.j(this.B,"click",function(){r.logClick(y.B)}),K=new g.UM(this.element,!0),g.q(this,K),K.subscribe("hoverstart",function(){r.logVisibility(y.B,!0)},this));
g.dy(this.element,"ytp-caption-window-rollup");g.q(this,this.Kh);g.Ds(this.element,"overflow","hidden")},jsT=function(K,R){if(!R)return"";
K.X&&K.K.params.Dv!==1&&(R*=-1);return"translate"+(K.X?"X":"Y")+"("+R+"px)"},qYu=function(K){K.Xt=Array.from(K.element.getElementsByClassName("caption-visual-line"));
for(var R=K.K.params.ZL,f=0,V=0,D=K.Xt.length-1;f<R&&D>-1;){var H=K.Xt[D];V+=K.X?H.offsetWidth:H.offsetHeight;f++;D--}K.Z=V;R=Math;f=R.max;isNaN(K.B5)&&((V=K.U.j8)?(D=g.tB("SPAN"),g.Pa(D,"\u2013".repeat(V)),g.Ds(D,d8_(K,K.U.xB)),K.J.appendChild(D),K.B5=D.offsetWidth,K.J.removeChild(D)):K.B5=0);V=K.J;K.UF=f.call(R,K.B5,K.bd,(K.X?V.offsetHeight:V.offsetWidth)+1)},MXu=function(K,R){qYu(K);
var f=K.Xt.reduce(function(H,l){return(K.X?l.offsetWidth:l.offsetHeight)+H},0);
f=K.Z-f;if(f!==K.G2){var V=f>0&&K.G2===0,D=f<K.G2;R||isNaN(f)||V||!D||(g.dy(K.element,"ytp-rollup-mode"),K.j(K.element,"transitionend",K.t8));g.Ds(K.J,"transform",jsT(K,f));K.G2=f}qYu(K)},bU8=function(K,R,f,V){var D=this;
this.G=K;this.X=R;this.logger=f;this.qY=V;this.QI=[];this.bT=[];this.U=null;this.OC={JE2:function(){return D.U},
A$:function(){return D.QI}};
K=g.mz(this.G.C().experiments,"html5_override_micro_discontinuities_threshold_ms");this.K=K>0?K:10},YYW=function(K,R){K.U=function(f,V){if(f.info.X){var D=f;
if(K.bT.length>0){for(D=K.bT.shift();K.bT.length>0;)D=g.xa(D,K.bT.shift());D=g.xa(D,f)}if(D){f=D;try{var H=g.Ey(f)*1E3}catch(r){H=f.info.startTime*1E3}try{var l=g.CRz(f)*1E3}catch(r){l=f.info.duration*1E3}if(H<0||l<0)H<0&&(H=f.info.startTime*1E3),l<0&&(l=f.info.duration*1E3);f.info.startTime=H/1E3;f.info.J=H/1E3;f.info.duration=l/1E3;f.info.N=l/1E3;H=K.HS(D);l=H.t5;H={formatId:H.formatId,startTimeMs:H.startTimeMs,durationMs:H.durationMs,bZ:l,SH:l};l=piT(K.QI,H.startTimeMs);var F=(f=l>=0?K.QI[l]:null)?
f.startTimeMs+f.durationMs:0,c=H.startTimeMs+H.durationMs;!f||H.startTimeMs-F>K.K?K.QI.splice(l+1,0,H):(f.durationMs=Math.max(F,c)-f.startTimeMs,f.SH=Math.max(f.SH,H.SH));V(K.QI);H=g.z5(D);V=K.X;H=H.buffer.slice(H.byteOffset,H.byteLength+H.byteOffset);D=D.info.J;V.T?V.J==null?g.Lh(V.logger,350058965,"Null loaded track meta data at captions data received"):R.u6(H,V.J,D*1E3):g.Lh(V.logger,350058965,"Null Representation at captions data received")}else g.Lh(K.logger,350058965,"Empty slice")}else K.bT.push(f)};
K.G.addEventListener("sabrCaptionsDataLoaded",K.U)},piT=function(K,R){K=g.hh(K,{startTimeMs:R},function(f,V){return f.startTimeMs-V.startTimeMs});
return K>=0?K:-K-2},jW=function(K,R){g.yW.call(this,R);
this.K=K;this.G=R;this.logger=new g.vf("caps");this.J=this.T=null;this.N=new bU8(this.G,this,this.logger,this.K.qY)},m88=function(K,R){var f=[],V;
for(V in K.K.U)if(K.K.U.hasOwnProperty(V)){var D=K.K.U[V];if(g.o$(D,R||null)){var H=D.info.id,l=H,F="."+H,c="",r="";if(D=D.info.captionTrack)H=D.languageCode,l=D.displayName,F=D.vssId,c=D.kind,r=D.id;f.push(new g.zj({id:V,languageCode:H,languageName:l,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:F,kind:c,captionId:r}))}}return f},G4u=function(K,R,f){var V=[],D;
for(D in K.K.U)if(K.K.U.hasOwnProperty(D)){var H=K.K.U[D];if(g.o$(H,f||null)){var l=H.info.captionTrack;l&&l.languageCode===R&&V.push(H)}}return V.length?V[0]:null},udT=function(K,R){if(!g.x32(K)||K.U!=null&&g.Wn5(R,K.U)&&K.U.U.rawcc!=null)return!1;
R=!!K.U&&K.U.isManifestless&&Object.values(K.U.U).some(function(f){return g.o$(f,"386")});
K=!!K.U&&!K.U.isManifestless&&g.rvG(K.U);return R||K},ssi=function(){ae.call(this)},eKi=function(K){var R=C68.length;
if(K.byteLength<R)return!1;K=new Uint8Array(K,0,R);for(var f=0;f<R;f++)if(C68[f]!==K[f])return!1;return!0},KG8=function(K,R,f,V,D,H,l,F,c){switch(l.tagName){case "b":F.bold=!0;
break;case "i":F.italic=!0;break;case "u":F.underline=!0}for(var r=0;r<l.childNodes.length;r++){var y=l.childNodes[r];if(y.nodeType===3)y=new ET(R,f,V,D.id,y.nodeValue,H||r>0,g.ZL(F)?void 0:F),c.push(y),D.U.push(y);else{var h={};Object.assign(h,F);KG8(K,R,f,V,D,!0,y,h,c)}}},Rfi=function(K){var R=K.split(":");
K=0;R=g.Z(R);for(var f=R.next();!f.done;f=R.next())K=K*60+Number(f.value);return K*1E3},fOV=function(K,R,f,V){V=Object.assign({Kq:0},V);
return new Q$(K,R,f,"_"+NM++,V)},qM=function(K,R){g.O.call(this);
this.G=K;this.W=R;this.U=null;this.BK=this.G.xZ();this.logger=new g.vf("caps")},DDT=function(K,R,f){if(typeof R==="string"||OUp(R))return[{trackData:R,
s1:f}];if(typeof R==="string"&&R.substring(0,6)==="WEBVTT"||typeof R!=="string"&&eKi(R))return[{trackData:R,s1:f}];var V=new DataView(R);if(V.byteLength<=8||V.getUint32(4)!==1718909296)return[];var D=g.eTG(V);if(K.BK&&D){var H=g.bQB(D),l=g.pXo(D);D=D.XH;H&&D&&K.BK.BT(D,H,l)}K=g.Ln(V,1835295092);if(!K||!K.length||!K[0].size)return[];H=[];for(l=0;l<K.length;l++)D=K[l],D=new Uint8Array(R,D.dataOffset,D.size-(D.dataOffset-D.offset)),D=g.vu(D),H.push({trackData:D,s1:f+l*1E3});Vqi(V,H,f);return H=H.filter(function(F){return!!F.trackData})},
Vqi=function(K,R,f){var V=g.F0(K,0,1836476516),D=9E4;
V&&(D=g.cF(V)||9E4);V=0;for(var H=g.Ln(K,1836019558),l=0;l<H.length;l++){var F=H[l];l<R.length&&(F=g.F0(K,F.dataOffset,1953653094))&&(F=g.F0(K,F.dataOffset,1952867444))&&(F=g.i2(F)/D*1E3,l===0&&(V=F),R[l].s1=F-V+f||f*l*1E3)}},HG8=function(K,R,f){K.U||(K.U=new ssi);
K=K.U.X(R,f);Math.random()<.01&&g.A$(Error("Deprecated subtitles format in web player: WebVTT"));return K},$DB=function(K){var R={};
if(K=g.a3(K))R.lang=K,g.ptv.test(K)&&(R.Gs=1);return R},FGE=function(K){g.cz.call(this,K);
var R=this;this.G=K;this.er=[];this.Xt={};this.Ne={};this.Z=!1;this.X="NONE";this.K=this.EF=this.UF=this.oY=this.OF=null;this.bd={iH:function(){R.iH()},
u6:function(H,l,F,c){R.u6(H,l,F,c)}};
this.U=null;this.W=this.G.C();this.videoData=this.G.getVideoData();this.pQ=this.G.Ft();this.B={xB:{}};this.T={xB:{}};g.RC(this.videoData)?this.X="OFFLINE":g.UhN(this.videoData,this.G)?this.X="HLS":udT(this.videoData,this.G)?this.X="SABR_LIVE":g.tZM(this.videoData,this.G)?this.X="LIVE":this.videoData.captionTracks.length?this.X="INNERTUBE":this.videoData.Gt&&(this.X="TTS");this.kW=this.W.controlsType==="3";this.Za=new qM(this.G,this.W);this.B5=new g.de(this);this.N=new g.Y({V:"div",D:"ytp-caption-window-container",
L:{id:"ytp-caption-window-container"}});this.aY={top:0,right:0,bottom:0,left:0,width:1,height:1};var f=null,V=g.It("yt-html5-player-modules::subtitlesModuleData");V&&(f=new g.AF(V));this.storage=f;var D;this.v5=!((D=K.CL())==null||!D.LH());this.J=lOi(this);this.y0=!this.J&&this.kW&&this.v5&&(this.X==="LIVE"||this.X==="SABR_LIVE");g.q(this,this.Za);this.J?this.G2=this.qe=null:(this.qe=new g.sH(this.Pp,void 0,this),g.q(this,this.qe),this.G2=new g.CW(this.H70,2E3,this),g.q(this,this.G2));g.q(this,this.B5);
g.nl(this.player,this.N.element,4);g.q(this,this.N);this.J||this.B5.j(K,"resize",this.Wc);(this.Kh=g.gV(this.W)&&!g.EX()&&!this.G.isFullscreen()&&!this.J&&!this.y0)&&this.B5.j(K,"resize",this.LtF);this.B5.j(K,"onPlaybackAudioChange",this.SCr);this.B5.j(K,g.gI("captions"),function(H){R.onCueRangeEnter(H)});
this.B5.j(K,g.OK("captions"),function(H){R.onCueRangeExit(H)});
dD$(this,mVu()||{});this.player.iM("onCaptionsModuleAvailable");this.X==="HLS"&&this.J&&(K=this.G.CL().ud(),this.v5&&this.B5.j(K.textTracks,"addtrack",this.Lir))},ytp=function(K){if(K.W.Pg===1||K.videoData.nM===1||g.JN(K.videoData,"yt:cc")==="alwayson")return!0;
if(K.videoData.captionTracks.length)var R=K.getAudioTrack().K;if(K.W.Pg===2){if(g.fc(K.W))var f=ctT(K);else if(K.storage)try{f=K.storage.get("module-enabled")}catch(D){K.storage.remove("module-enabled")}else f=null;if(f!=null)return!!f}f=Iz$(K.player.getAudioTrack(),g.fc(K.W));var V=g.JN(K.videoData,"yt:cc");if(rt8(K)===void 0){if(f==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return V?V==="on":!0;if(f==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return V==="on"}else return V==="on";return R==="ON"||g.JN(K.videoData,
"yt:cc")==="on"},MM=function(K,R){if(K.U&&(R===void 0||!R)||!K.videoData.captionTracks.length)return!1;
K=K.getAudioTrack();return!!K.U||K.K==="FORCED_ON"},rt8=function(K){var R=void 0,f=g.Mm().aG(65);
if(g.fc(K.W)&&f!=null){if(ctT(K)!=null)return!1;R=!f}return R},pK=function(K,R){if(!K.K)return null;
if(K.EF&&K.EF.J)return K.EF.J;R=hfi(K,R);R=g.bI(K.K.U,R);var f=null;if(gUW(K.W)){var V=K.G.isInline()?void 0:g.n4("yt-player-caption-sticky-language");for(var D=[V,K.videoData.captionsLanguagePreference,K.W.captionsLanguagePreference,g.JN(K.videoData,"yt:cc_default_lang")],H=!1,l=0;l<D.length;l++){var F=D[l];if(F){H=!0;for(var c=0;c<R.length;c++)if(g.a3(R[c])===F)return R[c];for(c=0;c<R.length;c++)if(g.a3(R[c]).split("-")[0]===F.split("-")[0])return R[c]}}if(H&&K.K&&(D=K.K.B,D.length))for(D=g.Z(D),
H=D.next();!H.done;H=D.next())if(H=H.value,H.languageCode===V){f=H;break}}else for(V=[K.videoData.captionsLanguagePreference,K.W.captionsLanguagePreference,g.JN(K.videoData,"yt:cc_default_lang")],D=0;D<V.length;D++)for(H=0;H<R.length;H++)if(g.a3(R[H])===V[D])return R[H];V=null;K.EF&&K.EF.X&&(V=K.EF.X);V||(V=R.find(function(r){return r.isDefault})||null);
V||(V=R[0]||bL(K));V&&f&&g.a3(V).split("-")[0]!==f.languageCode.split("-")[0]&&(V=OT$(V,f));return V},bL=function(K){return K.EF&&K.EF.U},YG=function(K){var R=bL(K);
return!!R&&K.U===R},ooE=function(K,R){if(K.U){var f=K.G.CL().ud().textTracks,V=null;
K.X==="HLS"?V=K.U.getId():V=K.U.toString();for(K=0;K<f.length;K++){var D=f[K];D.id===V&&(R?D.mode!=="showing"&&(D.mode="showing"):D.mode==="showing"&&(D.mode="disabled"))}}},uL=function(K,R,f){K.loaded&&K.unload();
f!=null&&(K.Z=f,K.Z&&(g.fc(K.W)?my(K,!!R):GS(K,!!R)));R!==null||MM(K,!0)||K.Tr(R,!!R,K.Z?"m":"s");K.U=R;MM(K)&&(K.U=bL(K));var V;Sqi(K,(V=K.U)!=null?V:void 0);K.load()},voH=function(K,R){if(R instanceof Q$){var f=K.Xt[R.id];
f&&f.K!==R&&(f.dispose(),delete K.Xt[R.id],f=null);f||(f=iGH(K,R))&&(K.Xt[R.id]=f)}else f=R.windowId,K.Ne[f]||(K.Ne[f]=[]),K.Ne[f].push(R)},iGH=function(K,R){var f=LGB(K);
if(!f)return null;var V=K.U?g.a3(K.U):null;V&&g.ptv.test(V)&&(R.params.Gs=1);var D=K.pQ.getPlayerSize();V=D.height*K.aY.height;D=D.width*K.aY.width;K.W.playerStyle!=="google-live"||K.B.isDefault||Object.assign(R.params,K.B);switch(R.params.Kq!=null?R.params.Kq:R.U.length>1?1:0){case 1:return new TS(R,K.B,K.T,f.width,f.height,D,V,K.W.experiments,K.t7.bind(K),K.G);case 2:return new OT(R,K.B,K.T,f.width,f.height,D,V,K.W.experiments,K.t7.bind(K),K.G);default:return new h9(R,K.B,K.T,f.width,f.height,D,
V,K.W.experiments,K.t7.bind(K),K.G)}},dD$=function(K,R,f){f=f===void 0?!1:f;
var V=sT.xB;K.B={};Object.assign(K.B,sT);K.B.xB={};Object.assign(K.B.xB,V);K.T={xB:{}};var D=R.backgroundOverride?K.T:K.B,H=R.background||V.background;J9.test(H);D.xB.background=H;D=R.colorOverride?K.T:K.B;H=R.color||V.color;J9.test(H);D.xB.color=H;D=R.windowColorOverride?K.T:K.B;H=R.windowColor||sT.windowColor;J9.test(H);D.windowColor=H;D=R.backgroundOpacityOverride?K.T:K.B;H=R.backgroundOpacity;H==null&&(H=V.backgroundOpacity);D.xB.backgroundOpacity=H;D=R.fontSizeIncrementOverride?K.T:K.B;H=R.fontSizeIncrement;
H==null&&(H=V.fontSizeIncrement);D.xB.fontSizeIncrement=H;H=R.fontStyleOverride?K.T:K.B;D=R.fontStyle;D==null&&(D=V.bold&&V.italic?3:V.bold?1:V.italic?2:0);H=H.xB;switch(D){case 1:H.bold=!0;delete H.italic;break;case 2:delete H.bold;H.italic=!0;break;case 3:H.bold=!0;H.italic=!0;break;default:delete H.bold,delete H.italic}D=R.textOpacityOverride?K.T:K.B;H=R.textOpacity;H==null&&(H=V.textOpacity);D.xB.textOpacity=H;D=R.windowOpacityOverride?K.T:K.B;H=R.windowOpacity;H==null&&(H=sT.windowOpacity);D.windowOpacity=
H;D=R.charEdgeStyleOverride?K.T:K.B;H=R.charEdgeStyle;H==null&&(H=V.charEdgeStyle);D.xB.charEdgeStyle=H;D=R.fontFamilyOverride?K.T:K.B;H=R.fontFamily;H==null&&(H=V.fontFamily);D.xB.fontFamily=H;K.loaded&&K.Wc();f&&g.Pe("yt-player-caption-display-settings",R,2592E3)},w4W=function(K,R){if(!K.K)return{};
if(R){g.ZL(R)||K.sJ(R.vss_id,"m");if(K.J&&K.X!=="HLS"||!g.kV(R))return;if(g.ZL(R)){uL(K,null,!0);return}for(var f,V=g.bI(K.K.U,!0),D=0;D<V.length;D++){var H=V[D];H.languageCode!==R.languageCode||f&&(H.languageName!==R.languageName||(H.captionId||"")!==(R.captionId||"")||g.x_(H)!==R.displayName)||(f=R.translationLanguage?OT$(H,R.translationLanguage):H)}K.nA(R.position);!f||f===K.U&&K.loaded||(R=g.Q0(),V=g.a3(f),R.length&&V===R[R.length-1]||(R.push(V),g.Pe("yt-player-caption-language-preferences",R)),
gUW(K.W)&&!K.G.isInline()&&g.Pe("yt-player-caption-sticky-language",V,2592E3),uL(K,f,!0))}else return K.loaded&&K.U&&!YG(K)?g.E2(K.U):{};return""},xDT=function(K,R,f){R&&!K.UF?(R=k4V({Gs:0,
lang:"es"}),K.UF=[R,new ET(R.start,R.end-R.start,0,R.id,f!=null?f:"Los subt\u00edtulos tendr\u00e1n este aspecto")],K.player.PV(K.UF)):!R&&K.UF&&(zf_(K,K.UF),K.UF=null)},zf_=function(K,R){K.player.LF(R);
R=g.Z(R);for(var f=R.next();!f.done;f=R.next())g.fa(K.er,f.value);cU(K.qe)},Sqi=function(K,R){K.W.Y("html5_modify_caption_vss_logging")&&(K.videoData.dS=R)},LGB=function(K){var R=K.pQ.getVideoContentRect(!0).height,f=K.pQ.getVideoContentRect(!0).width;
if(!R||!f)return null;R*=K.aY.height;f*=K.aY.width;return{width:f,height:R}},GS=function(K,R){if(K.storage)try{K.storage.set("module-enabled",R)}catch(f){}},my=function(K,R){K.G.isInline()||g.Pe("yt-player-sticky-caption",R,2592E3)},ctT=function(K){if(!K.G.isInline())return g.n4("yt-player-sticky-caption")},lOi=function(K){var R,f=!((R=K.G.CL())==null||!R.d3());
return K.X==="HLS"&&f?!0:K.kW&&f&&K.X!=="LIVE"&&K.X!=="SABR_LIVE"},hfi=function(K,R){if(K.X==="HLS")return!1;
g.MW(K.videoData)&&(R=!0);R||(R=K.X==="TTS"?!1:K.X==="INNERTUBE"?!1:!0);return R||K.W.Y("web_deprecate_always_includes_asr_setting")&&g.fc(K.W)?!0:!!g.Mm().aG(66)};
g.GZ.prototype.BT=g.O5(68,function(K,R,f){this.K.set(K,{jz:R,eB:f})});
g.ut.prototype.BT=g.O5(67,function(K,R,f){this.UF.BT(K,R,f)});
g.yW.prototype.UD=g.O5(66,function(){return!1});
g.yW.prototype.BA=g.O5(65,function(){});
g.hu.prototype.BA=g.O5(64,function(K,R,f){var V=this;this.mZ();R=this.uA(K,R);var D=this.YW.C().Y("html5_report_captions_ctmp_qoe"),H=(0,g.N7)();this.dC();nUS(this,R,{format:"RAW",onSuccess:function(l){V.K=null;if(D){var F=(l.responseText.length/1024).toFixed(),c=(0,g.N7)();V.videoData.KQ("capresp",{ms:c-H,kb:F})}f.u6(l.responseText,K)},
onError:D?function(l){var F;l=(F=l==null?void 0:l.status)!=null?F:0;V.videoData.KQ("capfail",{status:l})}:void 0,
withCredentials:!0})});
g.Su.prototype.BA=g.O5(63,function(K,R,f){var V=this;this.mZ();R=this.uA(K,R);this.dC();this.K=g.Jm(R,{format:"RAW",onSuccess:function(D){V.K=null;f.u6(D.responseText,K)},
withCredentials:!0})});
g.kf.prototype.k8=g.O5(62,function(){for(var K=g.xU(document,"track",void 0,this.U),R=0;R<K.length;R++)g.kU(K[R])});
g.NT.prototype.k8=g.O5(61,function(){for(var K=g.xU(document,"track",void 0,this.U),R=0;R<K.length;R++)g.kU(K[R])});
g.tg.prototype.k8=g.O5(60,function(){this.mediaElement.k8()});
g.kf.prototype.LH=g.O5(59,function(){return!(!this.U.textTracks||!this.U.textTracks.addEventListener)});
g.NT.prototype.LH=g.O5(58,function(){return!(!this.U.textTracks||!this.U.textTracks.addEventListener)});
g.tg.prototype.LH=g.O5(57,function(){return this.mediaElement.LH()});
g.kf.prototype.d3=g.O5(56,function(){return!!this.U.textTracks});
g.NT.prototype.d3=g.O5(55,function(){return!!this.U.textTracks});
g.tg.prototype.d3=g.O5(54,function(){return this.mediaElement.d3()});
g.kf.prototype.wq=g.O5(53,function(K){for(var R=0;R<K.length;R++)this.U.appendChild(K[R])});
g.NT.prototype.wq=g.O5(52,function(K){for(var R=0;R<K.length;R++)this.U.appendChild(K[R])});
g.tg.prototype.wq=g.O5(51,function(K){this.mediaElement.wq(K)});
g.Wm.prototype.Ga=g.O5(39,function(K){return g.vC(this.app,{playerType:void 0}).Ga(K)});
g.My.prototype.Ga=g.O5(38,function(K){return this.bD.zA.Ga(K)});
g.zG.prototype.Ga=g.O5(37,function(K){return this.qH().some(function(R){return R.namespace===K})});
g.PN.prototype.Ga=g.O5(36,function(){return!1});
g.Wm.prototype.sJ=g.O5(34,function(K,R){this.app.LQ().sJ(K,R)});
g.My.prototype.sJ=g.O5(33,function(K,R){this.bD.sJ(K,R)});
g.Qr.prototype.sJ=g.O5(32,function(K,R){K=[K,R];g.aN(this,g.Wo(this.provider),"cfi",K)});
g.Lz.prototype.sJ=g.O5(31,function(K,R){this.qoe&&this.qoe.sJ(K,R)});
g.Mg.prototype.sJ=g.O5(30,function(K,R){this.sC.sJ(K,R)});
g.PN.prototype.sJ=g.O5(29,function(){});
g.Wm.prototype.Tr=g.O5(28,function(K,R,f){this.app.LQ().Tr(K,R,f)});
g.My.prototype.Tr=g.O5(27,function(K,R,f){this.bD.Tr(K,R,f)});
g.Qr.prototype.Tr=g.O5(26,function(K,R,f){if(this.qe!==K||this.nh!==R)R=R==="rawcc"?"":R,f=[K,R,this.qe,f],g.BI(this.provider.W.ph())&&!this.v5&&f.push("sms.0"),g.aN(this,g.Wo(this.provider),"cfs",f),this.qe=K,this.nh=R,this.v5=!0});
g.Lz.prototype.Tr=g.O5(25,function(K,R,f){this.qoe&&this.qoe.Tr(K,R,f)});
g.Mg.prototype.Tr=g.O5(24,function(K,R,f){this.sC.Tr(K,R,f)});
g.PN.prototype.Tr=g.O5(23,function(){});
g.uf.prototype.jh=g.O5(3,function(K){return(K=this.Py(K))?K.U:0});
g.Uy.prototype.jh=g.O5(2,function(){return 0});
var bTS=/#(.)(.)(.)/,ML$=/^#(?:[0-9a-f]{3}){1,2}$/i,KbS={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};g.x(Ga8,g.yW);Ga8.prototype.hS=function(K){var R=this.YW.CL();if(R&&R.ud()){R=R.ud().textTracks;R=g.Z(R);for(var f=R.next();!f.done;f=R.next())f=f.value,f.kind==="subtitles"&&!this.K.has(f.language)&&f.language&&(g.r2(this.U,new g.zj({languageCode:f.language,languageName:f.language,kind:f.kind,id:f.id,displayName:f.label,vss_id:"."+f.language})),this.K.add(f.language))}g.bI(this.U).length>0&&K.iH()};
rY.prototype.contains=function(K){K=g.hh(this.segments,K);return K>=0||K<0&&(-K-1)%2===1};
rY.prototype.length=function(){return this.segments.length/2};
g.x(szu,g.O);g.w=szu.prototype;g.w.uD=function(){g.O.prototype.uD.call(this);this.K&&this.K.cancel()};
g.w.jS=function(){this.seekTo(this.player.getCurrentTime())};
g.w.seekTo=function(K){K-=this.player.jy();var R=this.U;this.U=g.p8(this.RY.QC(K).xW);R!==this.U&&this.EF&&this.EF()};
g.w.reset=function(){this.J=new rY;this.T=-1;this.K&&(this.K.cancel(),this.K=null)};
g.w.O4=function(){this.mZ();var K;if(K=this.U!=null)K=this.U,K=K.RY.Vd(K);if(K&&!this.K&&!(this.U&&this.U.startTime-this.player.getCurrentTime()>30)){K=this.U;K=K.RY.p5(K);var R=K.xW[0],f;if((f=this.player.getVideoData())==null?0:f.enableServerStitchedDai)if(f=this.player.xZ()){var V=R.RY.info.id,D=R.t5,H=K.xW[0].J;if(this.policy.G2){if(f=g.cP2(f,H,D,V,3))K.J=f}else if(V=f.gg(H,D,V,3))if(H=2,f.rR.has(D)?H=0:g.zjD(f,D)&&(H=1),f=H,f===0)V&&(K.U=new g.wo(V));else if(f===2){this.N.start();CuS(this)&&
this.seekTo(this.player.getCurrentTime());return}}R.RY.index.KM(R.t5)?(this.J.contains(K.xW[0].t5)||eOW(this,K),this.U=g.p8(K.xW)):CuS(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.x(y$,g.yW);g.w=y$.prototype;g.w.BA=function(K,R,f){var V=this;this.dC();R=fsS(this,K.getId());R||(R=K.languageCode,R=this.K.isManifestless?VXV(this,R,"386"):VXV(this,R));if(R){var D=(R.index.jh(R.index.Wy())-R.index.getStartTime(R.index.Wy()))*1E3,H=new g.HcB(this.G.C());this.J=new szu(H,this.G,R,function(l,F){f.u6(l,K,F,D)},this.N||g.BM(R.info),function(){V.J&&V.J.reset();
V.T=!0})}};
g.w.UD=function(){var K=this.T;this.T=!1;return K};
g.w.hS=function(K){var R=this.G.C().Y("html5_fallback_if_rawcc_missing");var f=this.K.U.rawcc!=null;if(!this.N||!f&&R)R=this.K.isManifestless?RKS(this,"386"):RKS(this);else{if(!f){g.Lh(this.logger,386248249,"rawcc used but unavailable");return}R=[new g.zj({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.zj({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}R=g.Z(R);
for(f=R.next();!f.done;f=R.next())g.r2(this.U,f.value);K.iH()};
g.w.dC=function(){this.J&&(this.J.dispose(),this.J=null)};
g.w.uA=function(){return""};
var J9=/^#(?:[0-9a-f]{3}){1,2}$/i;var $8E=["left","right","center","justify"];g.x(h9,g.Y);g.w=h9.prototype;g.w.Mm=function(K,R){this.kW=K;this.Za=R;var f=g.os(this.element,this.element.parentElement);this.OF=K-f.x;this.v5=R-f.y};
g.w.hw=function(K,R){if(K!==this.kW||R!==this.Za){g.lp(this.element,"ytp-dragging")||g.dy(this.element,"ytp-dragging");var f=g.i6(this.element);K=K-this.OF-.02*this.aQ;var V=R-this.v5-.02*this.vK,D=(K+f.width/2)/this.maxWidth*3;D=Math.floor(g.fT(D,0,2));var H=(V+f.height/2)/this.maxHeight*3;H=Math.floor(g.fT(H,0,2));R=D+H*3;K=(K+D/2*f.width)/this.maxWidth;K=g.fT(K,0,1)*100;f=(V+H/2*f.height)/this.maxHeight;f=g.fT(f,0,1)*100;this.K.params.oM=R;this.K.params.kE=f;this.K.params.gi=K;this.K.params.isDefault=
!1;this.U.oM=R;this.U.kE=f;this.U.gi=K;this.U.isDefault=!1;this.aY.oM=R;this.aY.kE=f;this.aY.gi=K;this.aY.isDefault=!1;this.gB()}};
g.w.B3=function(){g.c2(this.element,"ytp-dragging")};
g.w.gB=function(){this.v7(this.T)};
g.w.v7=function(K){var R=this.pQ?0:Math.min(this.Wd(),this.maxWidth),f=this.S9(),V=this.pQ;if(V){var D=getComputedStyle(this.J.parentNode);D=oe(D.borderLeftWidth)+oe(D.borderRightWidth)+oe(D.paddingLeft)+oe(D.paddingRight)}else D=0;var H=D;D="";this.K.params.Gs===3&&(D="rotate(180deg)");var l=V?"calc(96% - "+H+"px)":"96%";g.Ds(this.element,{top:0,left:0,right:"",bottom:"",width:R?R+"px":"",height:f?f+"px":"","max-width":l,"max-height":l,margin:"",transform:""});this.Y7(K);D={transform:D,top:"",left:"",
width:R?R+"px":"",height:f?f+"px":"","max-width":"","max-height":""};var F=this.U.gi*.96+2;l=this.U.oM;switch(l){case 0:case 3:case 6:(V=this.U.xB.fontSizeIncrement)&&V>0&&this.U.Gs!==2&&this.U.Gs!==3&&(F=Math.max(F/(1+V*2),2));D.left=F+"%";break;case 1:case 4:case 7:D.left=F+"%";F=this.J.offsetWidth;R||F?(R=R||F+1,D.width=R+"px",D["margin-left"]=V?R/-2-H/2+"px":R/-2+"px"):D.transform+=" translateX(-50%)";break;case 2:case 5:case 8:D.right=100-F+"%"}V=this.U.kE*.96+2;switch(l){case 0:case 1:case 2:D.top=
V+"%";break;case 3:case 4:case 5:D.top=V+"%";(f=f||this.element.clientHeight)?(D.height=f+"px",D["margin-top"]=f/-2+"px"):D.transform+=" translateY(-50%)";break;case 6:case 7:case 8:D.bottom=100-V+"%"}g.Ds(this.element,D);if(this.B){f=this.J.offsetHeight;V=1;for(R=0;R<K.length;R++)D=K[R],typeof D.text==="string"&&(V+=D.text.split("\n").length-1,D.append||R===0||V++);f/=V;this.B.style.height=f+"px";this.B.style.width=f+"px";this.element.style.paddingLeft=f+5+"px";this.element.style.paddingRight=f+
5+"px";K=Number(this.element.style.marginLeft.replace("px",""))-f-5;f=Number(this.element.style.marginRight.replace("px",""))-f-5;this.element.style.marginLeft=K+"px";this.element.style.marginRight=f+"px"}};
g.w.Y7=function(K){var R;for(R=0;R<K.length&&K[R]===this.T[R];R++);if(this.y0||this.T.length>R)R=0,this.y0=!1,this.T=[],this.N=this.qe=this.er=null,g.Ba(this.J);for(;R<K.length;R++)rQ8(this,K[R])};
g.w.Wd=function(){return 0};
g.w.S9=function(){return 0};
g.w.toString=function(){return g.Y.prototype.toString.call(this)};hKW.prototype.clear=function(){this.X=this.time=this.mode=0;this.U=[];this.reset()};
hKW.prototype.reset=function(){this.mode=0;this.J.reset(0);this.B.reset(1)};
var oOE=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];SW.prototype.set=function(K){this.type=K};
SW.prototype.get=function(){return this.type};
iL.prototype.clear=function(){this.state=0};
iL.prototype.update=function(){this.state=this.state===2?1:0};
iL.prototype.e4=function(){return this.state!==0};
iL.prototype.matches=function(K,R){return this.e4()&&K===this.VU&&R===this.s2};
wiV.prototype.reset=function(){this.timestamp=this.U=0};
vU.prototype.updateTime=function(K){for(var R=1;R<=15;++R)for(var f=1;f<=32;++f)this.X[R][f].timestamp=K};
vU.prototype.debugString=function(){for(var K="\n",R=1;R<=15;++R){for(var f=1;f<=32;++f){var V=this.X[R][f];K=V.U===0?K+"_":K+String.fromCharCode(V.U)}K+="\n"}return K};
vU.prototype.reset=function(K){for(var R=0;R<=15;R++)for(var f=0;f<=32;f++)this.X[R][f].reset();this.J=K;this.U=0;this.K=this.row=1};
var zK$=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],x8H=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],EOp=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],asT=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Wbi.prototype.reset=function(K,R){this.B=R;this.style.set(2);this.K=this.T;this.J=this.N;this.U=this.K;var f=(K<<2)+(R<<1);this.T.reset(f);this.N.reset(f);this.text.reset((K<<2)+(R<<1)+1)};
yQB.prototype.reset=function(K){this.B=K;this.K.clear();this.J=this.X;this.X.reset(K,0);this.T.reset(K,1)};ZUW.prototype.J=function(){};g.x(ET,g.nQ);ET.prototype.toString=function(){return g.nQ.prototype.toString.call(this)};g.x(ae,g.O);ae.prototype.reset=function(){};g.x(Q$,g.nQ);Q$.prototype.toString=function(){return g.nQ.prototype.toString.call(this)};
var NM=0;g.x(UT,ae);UT.prototype.reset=function(){this.N={};this.K=this.U=null;this.T=!0};
UT.prototype.X=function(K,R){K=K.firstChild;K.getAttribute("format");R=R||0;Number.isFinite(R);K=Array.from(K.childNodes);K=g.Z(K);for(var f=K.next();!f.done;f=K.next())if(f=f.value,f.nodeType===1)switch(f.tagName){case "head":var V=f;break;case "body":var D=f}if(V)for(V=Array.from(V.childNodes),V=g.Z(V),K=V.next();!K.done;K=V.next())if(K=K.value,K.nodeType===1)switch(K.tagName){case "pen":f=K.getAttribute("id");var H=this.pens,l={},F=K.getAttribute("p");F&&Object.assign(l,this.pens[F]);F=t9(K,"b");
F!=null&&(l.bold=F);F=t9(K,"i");F!=null&&(l.italic=F);F=t9(K,"u");F!=null&&(l.underline=F);F=A9(K,"et");F!=null&&(l.charEdgeStyle=F);F=A9(K,"of");F!=null&&(l.offset=F);F=Z0(K,"bc");F!=null&&(l.background=F);F=Z0(K,"ec");F!=null&&(l.vk=F);F=Z0(K,"fc");F!=null&&(l.color=F);F=A9(K,"fs");F!=null&&F!==0&&(l.fontFamily=F);F=WU(K,"sz");F!==void 0&&(l.fontSizeIncrement=F/100-1);F=WU(K,"bo");F!==void 0&&(l.backgroundOpacity=F/255);F=WU(K,"fo");F!==void 0&&(l.textOpacity=F/255);F=A9(K,"rb");F!=null&&F!==10&&
F!==0&&(l.K7=F>10?F-1:F);K=A9(K,"hg");K!=null&&(l.Su=K);H[f]=l;break;case "ws":f=K.getAttribute("id");this.EF[f]=TBE(this,K);break;case "wp":f=K.getAttribute("id"),this.Z[f]=P6u(this,K)}if(D){V=[];D=Array.from(D.childNodes);D=g.Z(D);for(K=D.next();!K.done;K=D.next())if(K=K.value,K.nodeType===1)switch(K.tagName){case "w":this.U=nOi(this,K,R,!1);(K=this.N[this.U.id])&&K.end>this.U.start&&(K.end=this.U.start);this.N[this.U.id]=this.U;V.push(this.U);break;case "p":var c=K;F=R;f=[];H=c.getAttribute("w")||
this.B;l=!!t9(c,"a");F=(WU(c,"t")||0)+F;var r=WU(c,"d")||5E3;l||(!this.T&&this.K&&this.K.windowId===H&&this.K.end>F&&(this.K.end=F),this.K&&this.K.text==="\n"&&(this.K.text=""));var y=l?6:5,h=c.getAttribute("p");h=h?this.pens[h]:null;var S=Array.from(c.childNodes);S.length&&(this.T=c.getAttribute("d")!=null);for(c=0;c<S.length;c++){var v=S[c],L=void 0;c>0&&(l=!0);var E=void 0;v.nodeType===1&&(E=v);if(E&&E.tagName==="s"){if((v=(v=E.getAttribute("p"))?this.pens[v]:null)&&v.K7&&(v.K7===1?(v=S.slice(c,
c+4),v.length===4&&(L=Xi_(F,r,H,l,y,v,this.pens),c+=3)):L=Xi_(F,r,H,l,y,[E],this.pens)),!L){var Q=E;L=F;E=r;v=H;var J=l,A=y,B=Q.textContent?Q.textContent:"",k=Q.getAttribute("p");k=k?this.pens[k]:null;Q=WU(Q,"t")||0;L=new ET(L+Q,E-Q,A,v,B,J,k)}}else L=new ET(F,r,y,H,v.textContent||"",l,h);f.push(L);this.K=L}if(f.length>0)for(f[0].windowId===this.B&&(this.U=nOi(this,K,R,!0),V.push(this.U)),K=g.Z(f),f=K.next();!f.done;f=K.next())f=f.value,f.windowId=this.U.id,this.U.U.push(f),V.push(f)}R=V}else R=[];
return R};var Eoz=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.x(BU,ae);BU.prototype.reset=function(){this.K.clear()};
BU.prototype.X=function(K,R){var f=JSON.parse(K);if(!f)return[];if(f.pens){K=0;for(var V=g.Z(f.pens),D=V.next();!D.done;D=V.next()){D=D.value;var H={},l=D.pParentId;l&&Object.assign(H,this.U.get(l));D.bAttr&&(H.bold=!0);D.iAttr&&(H.italic=!0);D.uAttr&&(H.underline=!0);l=D.ofOffset;l!=null&&(H.offset=l);D.szPenSize!==void 0&&(H.fontSizeIncrement=D.szPenSize/100-1);l=D.etEdgeType;l!=null&&(H.charEdgeStyle=l);D.ecEdgeColor!==void 0&&(H.vk=X7(D.ecEdgeColor));l=D.fsFontStyle;l!=null&&l!==0&&(H.fontFamily=
l);D.fcForeColor!==void 0&&(H.color=X7(D.fcForeColor));D.foForeAlpha!==void 0&&(H.textOpacity=D.foForeAlpha/255);D.bcBackColor!==void 0&&(H.background=X7(D.bcBackColor));D.boBackAlpha!==void 0&&(H.backgroundOpacity=D.boBackAlpha/255);(l=D.rbRuby)&&l!==10&&(H.K7=l>10?l-1:l,H.textEmphasis=Eoz.get(H.K7));D.hgHorizGroup&&(H.Su=D.hgHorizGroup);this.U.set(K++,H)}}if(f.wsWinStyles)for(K=0,V=g.Z(f.wsWinStyles),D=V.next();!D.done;D=V.next())D=D.value,H={},(l=D.wsParentId)?Object.assign(H,this.B.get(l)):Object.assign(H,
this.T),D.mhModeHint!==void 0&&(H.Kq=D.mhModeHint),D.juJustifCode!==void 0&&(H.textAlign=D.juJustifCode),D.pdPrintDir!==void 0&&(H.Gs=D.pdPrintDir),D.sdScrollDir!==void 0&&(H.Dv=D.sdScrollDir),D.wfcWinFillColor!==void 0&&(H.windowColor=X7(D.wfcWinFillColor)),D.wfoWinFillAlpha!==void 0&&(H.windowOpacity=D.wfoWinFillAlpha/255),this.B.set(K++,H);if(f.wpWinPositions)for(K=0,V=g.Z(f.wpWinPositions),D=V.next();!D.done;D=V.next())D=D.value,H={},(l=D.wpParentId)&&Object.assign(H,this.J.get(l)),D.ahHorPos!==
void 0&&(H.gi=D.ahHorPos),D.apPoint!==void 0&&(H.oM=D.apPoint),D.avVerPos!==void 0&&(H.kE=D.avVerPos),D.ccCols!==void 0&&(H.j8=D.ccCols),D.rcRows!==void 0&&(H.ZL=D.rcRows),this.J.set(K++,H);if(f.events){K=[];f=g.Z(f.events);for(V=f.next();!V.done;V=f.next()){var F=V.value;D=(F.tStartMs||0)+R;H=F.dDurationMs||0;if(F.id)l=String(F.id),V=IsW(this,F,D,H,l),K.push(V),this.K.set(l,V);else{F.wWinId?l=F.wWinId.toString():(l="_"+NM++,V=IsW(this,F,D,H,l),K.push(V),this.K.set(l,V));V=K;var c=F;H===0&&(H=5E3);
F=this.K.get(l);var r=!!c.aAppend,y=r?6:5,h=c.segs,S=null;c.pPenId&&(S=this.U.get(c.pPenId));for(c=0;c<h.length;c++){var v=h[c],L=v.utf8;if(L){var E=v.tOffsetMs||0,Q=null;v.pPenId&&(Q=this.U.get(v.pPenId));if((F.params.Kq!=null?F.params.Kq:F.U.length>1?1:0)===2&&r&&L==="\n")continue;v=null;var J=[],A;if(A=Q&&Q.K7===1){A=h;var B=c;if(B+3>=A.length||!A[B+1].pPenId||!A[B+2].pPenId||!A[B+3].pPenId)A=!1;else{var k=A[B+1].pPenId;(k=this.U.get(k))&&k.K7&&k.K7===2?(k=A[B+2].pPenId,k=this.U.get(k),!k||!k.K7||
k.K7<3?A=!1:(k=A[B+3].pPenId,A=(k=this.U.get(k))&&k.K7&&k.K7===2?!0:!1)):A=!1}}if(A)E=h[c+1].utf8,v=h[c+3].utf8,A=h[c+2].utf8,B=this.U.get(h[c+2].pPenId),L=BB8(L,E,A,v,B),v=new ET(D,H,y,l,L,r,Q),c+=3;else{if(L.indexOf("<")>-1){var b=void 0;J=Q;A=S;B=D;k=H;var M=E,Hc=y,fB=r,Rw=[],FG=g.pR("<html>"+L+"</html>");if(!FG.getElementsByTagName("parsererror").length&&((b=FG.firstChild)==null?0:b.childNodes.length))for(b=g.Z(FG.firstChild.childNodes),FG=b.next();!FG.done;FG=b.next()){FG=FG.value;var yN=void 0,
VN=void 0,aw=(VN=(yN=FG.textContent)==null?void 0:yN.replace(/\n/g,""))!=null?VN:"";if(FG.nodeType!==3||aw&&aw.match(/^ *$/)==null){yN={};Object.assign(yN,J||A);VN=void 0;switch((VN=FG)==null?void 0:VN.tagName){case "b":yN.bold=!0;break;case "i":yN.italic=!0;break;case "u":yN.underline=!0}Rw.push(new ET(B+M,k-M,Hc,F.id,aw,fB,yN))}}J=Rw}J.length||(J=[new ET(D+E,H-E,y,F.id,L,r,Q||S)])}if(J.length)for(r=g.Z(J),Q=r.next();!Q.done;Q=r.next())Q=Q.value,V.push(Q),F.U.push(Q);else v&&(V.push(v),F.U.push(v))}r=
!0}}}R=K}else R=[];return R};g.x(kG,g.yW);kG.prototype.BA=function(K,R,f){qa8(this.videoData.videoId,K.vssId,f.u6)};
kG.prototype.hS=function(K){if(this.audioTrack)for(var R=g.Z(this.audioTrack.captionTracks),f=R.next();!f.done;f=R.next())g.r2(this.U,f.value);K.iH()};g.x(TS,h9);TS.prototype.Y7=function(K){var R=this.K.U;h9.prototype.Y7.call(this,K);for(K=K.length;K<R.length;K++){var f=R[K];if(H&&f.U===D)var V=H;else{V={};Object.assign(V,f.U);Object.assign(V,aOB);var D=f.U;var H=V}rQ8(this,f,V)}};
var aOB={BUU:!0};g.x(PU,ZUW);PU.prototype.J=function(K,R,f,V,D){if(f<V){var H="_"+NM++;f=f/1E3-this.T;V=V/1E3-this.T;K=new Q$(f,V-f,5,H,{textAlign:0,oM:0,gi:R*2.5,kE:K*5.33});D=new ET(f,V-f,5,H,D);this.K.push(K);this.K.push(D)}};
g.x(gY,ae);gY.prototype.X=function(K){K=new PU(K,K.byteLength,this.K);if(gOi(K)){for(;K.byteOffset<K.U.byteLength;)for(K.version===0?K.X=Ie(K)*(1E3/45):K.version===1&&(K.X=Ie(K)*4294967296+Ie(K)),K.B=nK(K);K.B>0;K.B--){var R=nK(K),f=nK(K),V=nK(K);R&4&&(R&3)===this.track&&(this.track===0||this.track===1)&&(R=this.U,R.U.push({time:K.X,type:this.track,T0:f,Dy:V,order:R.U.length}))}LbS(this.U,K);return K.K}return[]};
gY.prototype.reset=function(){this.U.clear()};g.x(OT,h9);g.w=OT.prototype;g.w.gB=function(){g.Ke(this.Kh)};
g.w.t8=function(){this.element.removeEventListener("transitionend",this.t8,!1);g.c2(this.element,"ytp-rollup-mode");this.v7(this.Gt,!0)};
g.w.S9=function(){return this.X?this.UF:this.Z};
g.w.Wd=function(){return this.X?this.Z:this.UF};
g.w.v7=function(K,R){this.Gt=K;if(this.K.params.ZL){for(var f=0,V=0;V<this.T.length&&f<K.length;V++)this.T[V]===K[f]&&f++;f>0&&f<K.length&&(K=this.T.concat(K.slice(f)));this.bd=this.UF;this.Z=this.UF=0;h9.prototype.v7.call(this,K);MXu(this,R)}h9.prototype.v7.call(this,K)};bU8.prototype.unload=function(){this.U!=null&&(this.G.removeEventListener("sabrCaptionsDataLoaded",this.U),this.U=null);this.QI=[];this.G.publish("sabrCaptionsBufferedRangesUpdated",this.QI)};
bU8.prototype.HS=function(K){return{formatId:g.nH(K.info.RY.info,this.qY),t5:K.info.t5+(this.qY?0:1),startTimeMs:K.info.J*1E3,durationMs:K.info.N*1E3}};g.x(jW,g.yW);jW.prototype.BA=function(K,R,f){this.dC();R=K.getId();R=R!=null&&R in this.K.U?this.K.U[R]:null;R||(R=K.languageCode,R=this.K.isManifestless?G4u(this,R,"386"):G4u(this,R));R&&(this.J=K,this.T=R,YYW(this.N,f),this.G.publish("sabrCaptionsTrackChanged",g.nH(R.info,this.K.qY)))};
jW.prototype.hS=function(K){var R=this.K.isManifestless?m88(this,"386"):m88(this);R=g.Z(R);for(var f=R.next();!f.done;f=R.next())g.r2(this.U,f.value);K.iH()};
jW.prototype.dC=function(){this.J&&(this.J=this.T=null,this.N.unload(),this.G.publish("sabrCaptionsTrackChanged",null))};
jW.prototype.uA=function(){return""};var C68="WEBVTT".split("").map(function(K){return K.charCodeAt(0)});
g.x(ssi,ae);
ssi.prototype.X=function(K,R){K instanceof ArrayBuffer&&(K=g.vu(new Uint8Array(K)));var f=[];K=K.split(Qoi);for(var V=1;V<K.length;V++){var D=K[V],H=R;if(D!==""&&!NOV.test(D)){var l=UDV.exec(D);if(l&&l.length>=4){var F=Rfi(l[1]),c=Rfi(l[2])-F;F+=H;var r=(l=l[3])?l.split(" "):[];l={};var y=null;var h="";var S=null,v="";r=g.Z(r);for(var L=r.next();!L.done;L=r.next())if(L=L.value.split(":"),L.length===2){var E=L[1];switch(L[0]){case "line":L=E.split(",");L[0].endsWith("%")&&(y=L[0],l.kE=Number.parseInt(y,
10),L.length===2&&(h=L[1].trim()));break;case "position":L=E.split(",");S=L[0];l.gi=Number.parseInt(S,10);L.length===2&&(v=L[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}y||h||(h="end");if(!S)switch(l.textAlign){case 0:l.gi=0;break;case 1:l.gi=100;break;case 2:l.gi=50}if(l.textAlign!=null){y=0;switch(h){case "center":y+=3;break;case "end":y+=6;break;default:y+=0}switch(v){case "line-left":y+=0;break;case "center":y+=
1;break;case "line-right":y+=2;break;default:switch(l.textAlign){case 0:y+=0;break;case 2:y+=1;break;case 1:y+=2}}h=y<0||y>8?7:y;l.oM=h}D=D.substring(UDV.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");v=l;l=D;D={};if(l.indexOf("<")<0&&l.indexOf("&")<0)H=fOV(F,c,5,v),c=new ET(F,c,5,H.id,l,!1,g.ZL(D)?void 0:D),f.push(H),f.push(c),H.U.push(c);else for(h=l.split(WG_),h.length===1?(l=5,v=fOV(F,c,l,v)):(y=l=6,v=Object.assign({j8:32},v),v=new Q$(F,c,y,"_"+NM++,v)),f.push(v),y=F,S=0;S<h.length;S++)r=h[S],
S%2===0?(L=g.pR("<html>"+r+"</html>"),L.getElementsByTagName("parsererror").length?(E=L.createElement("span"),E.appendChild(L.createTextNode(r))):E=L.firstChild,KG8(this,y,c-(y-F),l,v,S>0,E,D,f)):y=Rfi(r)+H}UDV.lastIndex=0}}return f};
var NOV=/^NOTE/,Qoi=/(?:\r\n|\r|\n){2,}/,UDV=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),WG_=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.x(qM,g.O);qM.prototype.clear=function(){this.U&&this.U.dispose();this.U=null};
qM.prototype.reset=function(){this.U&&this.U.reset()};
qM.prototype.uD=function(){g.O.prototype.uD.call(this);this.clear()};var sT={windowColor:"#080808",windowOpacity:0,textAlign:2,oM:7,gi:50,kE:100,isDefault:!0,xB:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.x(FGE,g.cz);g.w=FGE.prototype;g.w.uD=function(){if(this.J||this.y0){var K=this.G.CL();K&&!K.mZ()&&K.k8()}else xDT(this,!1);g.cz.prototype.uD.call(this)};
g.w.RH=function(){return this.W.Y("html5_honor_caption_availabilities_in_audio_track")&&this.X!=="LIVE"&&this.X!=="SABR_LIVE"};
g.w.ge=function(){if(this.kW)return this.J||this.y0;if(this.X==="HLS")return this.J;var K=this.getAudioTrack();if(this.RH()){if(!K.captionTracks.length)return!1;if(!this.K)return!0}K=Iz$(K,g.fc(this.W));return K==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:K==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?MM(this):rt8(this)||MM(this)?!0:ytp(this)};
g.w.load=function(){g.cz.prototype.load.call(this);this.EF=this.getAudioTrack();if(this.K)this.U&&(this.Za.clear(),this.J?ooE(this,!0):this.player.getPresentingPlayerType()!==3&&this.K.BA(this.U,"json3",this.bd),this.X!=="HLS"&&this.J||this.y0||YG(this)||this.player.iM("captionschanged",g.E2(this.U)));else{var K;this.X==="OFFLINE"?K=new kG(this.player,this.videoData,this.getAudioTrack()):this.X==="SABR_LIVE"?K=new jW(this.videoData.U,this.player):this.X==="HLS"?K=new Ga8(this.player):this.X==="LIVE"?
K=new y$(this.videoData.U,this.player):this.X==="INNERTUBE"?K=new g.hu(this.player,this.videoData,this.getAudioTrack()):K=new g.Su(this.player,this.videoData.Gt,this.videoData.videoId,g.QDe(this.videoData),this.videoData.CP,this.videoData.eventId);this.K=K;g.q(this,this.K);this.K.hS(this.bd)}};
g.w.unload=function(){this.J&&this.U?ooE(this,!1):(this.G2&&g.Rt(this.G2),this.player.BV("captions"),this.er=[],this.K&&this.K.dC(),this.Za.clear(),this.UF&&this.player.PV(this.UF),this.Wc());g.cz.prototype.unload.call(this);this.player.uu();this.player.iM("captionschanged",{})};
g.w.create=function(){this.ge()&&this.load();var K;a:{var R,f,V;if(this.W.Y("web_player_nitrate_promo_tooltip")&&((R=this.videoData.getPlayerResponse())==null?0:(f=R.captions)==null?0:(V=f.playerCaptionsTracklistRenderer)==null?0:V.enableTouchCaptionsNitrate)){var D,H;if(R=(K=this.videoData.getPlayerResponse())==null?void 0:(D=K.captions)==null?void 0:(H=D.playerCaptionsTracklistRenderer)==null?void 0:H.captionTracks)for(K=g.Z(R),D=K.next();!D.done;D=K.next())if(D=D.value,D.kind==="asr"&&D.languageCode===
"en"){K=!0;break a}}K=!1}K&&this.G.publish("showpromotooltip",this.N.element)};
g.w.iH=function(){var K=Iz$(this.player.getAudioTrack(),g.fc(this.W));var R=K==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?pK(this,this.Z):K==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&MM(this)?bL(this):rt8(this)||this.Z||ytp(this)?pK(this,this.Z):MM(this)?bL(this):null;if(this.X!=="HLS"&&this.J||this.y0){var f=g.bI(this.K.U,!0);K=[];for(var V=0;V<f.length;V++){var D=f[V],H=g.tB("TRACK");H.setAttribute("kind","subtitles");H.setAttribute("label",g.x_(D));H.setAttribute("srclang",g.a3(D));H.setAttribute("id",
D.toString());this.y0||H.setAttribute("src",this.K.uA(D,"vtt"));D===R&&H.setAttribute("default","1");K.push(H)}R=this.G.CL();R.wq(K);K=R.ud();this.v5&&this.B5.j(K.textTracks,"change",this.HT5)}else!this.U&&R&&uL(this,R),this.player.iM("onCaptionsTrackListChanged"),this.player.h$("onApiChange")};
g.w.getTrackById=function(K){for(var R=g.bI(this.K.U,!0),f=0;f<R.length;f++)if(R[f].toString()===K)return R[f];return null};
g.w.HT5=function(){for(var K=this.G.CL().ud().textTracks,R=null,f=0;f<K.length;f++)K[f].mode==="showing"&&(R=this.getTrackById(K[f].id));(this.loaded?this.U:null)!==R&&uL(this,R,!0)};
g.w.Lir=function(){var K;(K=this.K)==null||K.hS(this.bd)};
g.w.VLp=function(){!this.U&&this.J||this.unload()};
g.w.u6=function(K,R,f,V){if(K){var D;Sqi(this,(D=this.U)!=null?D:void 0);this.K.UD()&&(this.er=[],this.G.BV("captions"),cU(this.qe),this.Za.reset());a:{D=this.Za;V=V||0;f=DDT(D,K,f||0);K=[];try{for(var H=g.Z(f),l=H.next();!l.done;l=H.next()){var F=l.value,c=F.trackData,r=F.s1,y=D.W.Y("safari_live_drm_captions_fix");if(typeof c!=="string"){f=K;var h=f.concat;if(y&&eKi(c))var S=HG8(D,c,r);else{var v=D,L=R,E=c,Q=r,J=V;if(!OUp(E))throw Error("Invalid binary caption track data");v.U||(v.U=new gY(J,L));
S=v.U.X(E,Q)}var A=h.call(f,S)}else{if(c.substring(0,6)==="WEBVTT")var B=K.concat(HG8(D,c,r));else{f=K;var k=f.concat;b:{L=v=void 0;E=D;Q=R;if(c[0]==="{")try{E.U||(E.U=new BU($DB(Q)));var b=L=E.U.X(c,r);break b}catch(VN){g.WR(VN);b=[];break b}var M=g.pR(c);if(!M||!M.firstChild){var Hc=Error("Invalid caption track data");Hc.params=c;throw Hc;}if(M.firstChild.tagName==="timedtext"){if(Number(M.firstChild.getAttribute("format"))===3){E.U||(E.U=new UT($DB(Q),E.W));b=v=E.U.X(M,r);break b}var fB=Error("Unsupported subtitles format in web player (Format2)");
fB.params=c;throw fB;}if(M.firstChild.tagName==="transcript"){var Rw=Error("Unsupported subtitles format in web player (Format1)");Rw.params=c;throw Rw;}var FG=Error("Invalid caption track data");FG.params=c;throw FG;}B=k.call(f,b)}A=B}K=A}var yN=K;break a}catch(VN){g.Lh(D.logger,187101178,"Captions parsing failed: "+VN.message+". ");D.clear();yN=[];break a}yN=void 0}R=yN;R.length>0&&(yN=this.U,this.Tr(yN,!!yN,YG(this)?"g":this.Z?"m":"s"));this.player.PV(R,void 0,this.X==="LIVE"||this.X==="SABR_LIVE");
!this.Z||this.y0||YG(this)||g.cX(this.W)||g.jA(this.W)||g.ke(this.W)||this.W.Xt==="shortspage"||this.player.isInline()||(g.Rt(this.G2),R=k4V({oM:0,gi:5,kE:5,ZL:2,textAlign:0,Gs:0,lang:"es"}),this.oY=[R],yN=["Haz clic en "," para ir a la configuraci\u00f3n"],this.OF||(H=new g.Hv(g.Wv()),g.q(this,H),this.OF=H.element),H=R.end-R.start,(l=g.x_(this.U))&&this.oY.push(new ET(R.start,H,0,R.id,l)),this.oY.push(new ET(R.start,H,0,R.id,yN[0]),new ET(R.start,H,0,R.id,this.OF,!0),new ET(R.start,H,0,R.id,yN[1],
!0)),this.player.PV(this.oY),g.eE(this.G2));!this.Z||this.y0||YG(this)||(g.fc(this.W)?my(this,!0):GS(this,!0),this.EF&&(this.EF.J=this.U),this.player.uu());this.Z=!1}};
g.w.onCueRangeEnter=function(K){this.er.push(K);cU(this.qe)};
g.w.onCueRangeExit=function(K){g.fa(this.er,K);this.K instanceof y$&&this.K.N&&this.player.LF([K]);cU(this.qe)};
g.w.getCaptionWindowContainerId=function(){return this.N.element.id};
g.w.H70=function(){zf_(this,this.oY);this.oY=null};
g.w.Pp=function(){var K=this;if(!this.Kh||!this.J){this.qe.stop();g.DzD(this.Ne);this.er.sort(g.IM);var R=this.er;if(this.UF){var f=g.Im(R,function(H){return this.UF.indexOf(H)===-1},this);
f.length&&(R=f)}R=g.Z(R);for(f=R.next();!f.done;f=R.next())voH(this,f.value);R=g.Z(Object.entries(this.Xt));var V=R.next();for(f={};!V.done;f={ob:void 0,bQ:void 0},V=R.next()){var D=g.Z(V.value);V=D.next().value;D=D.next().value;f.ob=V;f.bQ=D;this.Ne[f.ob]?(f.bQ.element.parentNode||(f.bQ instanceof OT||f.bQ instanceof TS||g.i_(this.Xt,function(H){return function(l,F){F!==H.ob&&l.K.params.oM===H.bQ.K.params.oM&&l.K.params.gi===H.bQ.K.params.gi&&l.K.params.kE===H.bQ.K.params.kE&&(l.dispose(),delete K.Xt[F]);
return F===H.ob}}(f),this),this.N.element.appendChild(f.bQ.element)),f.bQ.v7(this.Ne[f.ob])):(f.bQ.dispose(),delete this.Xt[f.ob])}}};
g.w.Z7r=function(){dD$(this,{},!0);this.player.iM("captionssettingschanged")};
g.w.h4=function(){var K=sT.xB;K={background:K.background,backgroundOpacity:K.backgroundOpacity,charEdgeStyle:K.charEdgeStyle,color:K.color,fontFamily:K.fontFamily,fontSizeIncrement:K.fontSizeIncrement,fontStyle:K.bold&&K.italic?3:K.bold?1:K.italic?2:0,textOpacity:K.textOpacity,windowColor:sT.windowColor,windowOpacity:sT.windowOpacity};var R=mVu()||{};R.background!=null&&(K.background=R.background);R.backgroundOverride!=null&&(K.backgroundOverride=R.backgroundOverride);R.backgroundOpacity!=null&&(K.backgroundOpacity=
R.backgroundOpacity);R.backgroundOpacityOverride!=null&&(K.backgroundOpacityOverride=R.backgroundOpacityOverride);R.charEdgeStyle!=null&&(K.charEdgeStyle=R.charEdgeStyle);R.charEdgeStyleOverride!=null&&(K.charEdgeStyleOverride=R.charEdgeStyleOverride);R.color!=null&&(K.color=R.color);R.colorOverride!=null&&(K.colorOverride=R.colorOverride);R.fontFamily!=null&&(K.fontFamily=R.fontFamily);R.fontFamilyOverride!=null&&(K.fontFamilyOverride=R.fontFamilyOverride);R.fontSizeIncrement!=null&&(K.fontSizeIncrement=
R.fontSizeIncrement);R.fontSizeIncrementOverride!=null&&(K.fontSizeIncrementOverride=R.fontSizeIncrementOverride);R.fontStyle!=null&&(K.fontStyle=R.fontStyle);R.fontStyleOverride!=null&&(K.fontStyleOverride=R.fontStyleOverride);R.textOpacity!=null&&(K.textOpacity=R.textOpacity);R.textOpacityOverride!=null&&(K.textOpacityOverride=R.textOpacityOverride);R.windowColor!=null&&(K.windowColor=R.windowColor);R.windowColorOverride!=null&&(K.windowColorOverride=R.windowColorOverride);R.windowOpacity!=null&&
(K.windowOpacity=R.windowOpacity);R.windowOpacityOverride!=null&&(K.windowOpacityOverride=R.windowOpacityOverride);return K};
g.w.Wp=function(K,R){var f={};Object.assign(f,mVu());Object.assign(f,K);dD$(this,f,R);this.player.iM("captionssettingschanged")};
g.w.Wc=function(){!this.J&&this.loaded&&(g.T2(this.Xt,function(K,R){K.dispose();delete this.Xt[R]},this),this.Pp())};
g.w.OJ=function(K,R){switch(K){case "fontSize":if(isNaN(R))break;K=g.fT(R,-2,4);this.Wp({fontSizeIncrement:K});return K;case "reload":R&&!this.J&&uL(this,this.U,!0);break;case "stickyLoading":R!==void 0&&this.W.Z&&(g.fc(this.W)?my(this,!!R):GS(this,!!R));break;case "track":return w4W(this,R);case "tracklist":return this.K?g.JQ(g.bI(this.K.U,!(!R||!R.includeAsr)),function(f){return g.E2(f)}):[];
case "translationLanguages":return this.K?this.K.B.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.J||R===void 0||xDT(this,!!R);break;case "sampleSubtitlesCustomized":this.J||xDT(this,!!R,R);break;case "recommendedTranslationLanguages":return g.Q0();case "defaultTranslationSourceTrackIndices":return this.K?this.K.Z:[]}};
g.w.getOptions=function(){var K="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.W.Z&&K.push("stickyLoading");return K};
g.w.zY=function(){var K=this.U;if(this.G.Ga("captions")){if(this.W.Y("html5_modify_caption_vss_logging")){var R;return(K=(R=this.videoData.dS)!=null?R:null)?{cc:g.i6G(K)}:{}}if(K)return R=K.vssId,K.translationLanguage&&R&&(R="t"+R+"."+g.a3(K)),{cc:R}}return{}};
g.w.pU0=function(){this.isSubtitlesOn()?(g.fc(this.W)?my(this,!1):GS(this,!1),Sqi(this),uL(this,null,!0)):this.mV()};
g.w.mV=function(){var K=YG(this)||!this.U?pK(this,!0):this.U;K&&this.sJ(K.vssId,"m");this.isSubtitlesOn()||uL(this,YG(this)||!this.U?pK(this,!0):this.U,!0)};
g.w.isSubtitlesOn=function(){return!!this.loaded&&!!this.U&&!YG(this)};
g.w.SCr=function(){var K=YG(this);MM(this,K)?uL(this,this.getAudioTrack().U,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.RH()&&(this.Z=!1,this.U=null,this.K&&(this.K.dispose(),this.K=null)),this.ge()&&(K?uL(this,pK(this,!1),!1):this.load()))};
g.w.nA=function(K){K&&(this.aY={top:K.top,right:K.right,bottom:K.bottom,left:K.left,width:1-K.left-K.right,height:1-K.top-K.bottom},this.N.element.style.top=this.aY.top*100+"%",this.N.element.style.left=this.aY.left*100+"%",this.N.element.style.width=this.aY.width*100+"%",this.N.element.style.height=this.aY.height*100+"%",this.N.element.style.position="absolute",K=LGB(this))&&(this.N.element.style.width=K.width+"px",this.N.element.style.height=K.height+"px")};
g.w.onVideoDataChange=function(K,R){K==="newdata"&&(this.videoData=R,this.loaded&&this.unload(),this.Z=!1,this.U=null,this.K&&(this.K.dispose(),this.K=null,this.player.iM("captionschanged",{})),this.ge()&&this.load())};
g.w.getAudioTrack=function(){return this.player.getAudioTrack()};
g.w.LtF=function(){var K=this.G.CL();K&&!K.mZ()&&K.k8();this.G.isFullscreen()?(this.J=this.kW=!0,this.loaded&&this.iH()):(this.kW=this.W.controlsType==="3",this.J=lOi(this));uL(this,this.U)};
g.w.t7=function(){var K,R,f,V=(K=this.videoData.getPlayerResponse())==null?void 0:(R=K.captions)==null?void 0:(f=R.playerCaptionsTracklistRenderer)==null?void 0:f.openTranscriptCommand;V&&this.player.lD("innertubeCommand",V)};
g.w.Tr=function(K,R,f){var V=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,D="";K&&(D=K.vssId,D=D.replace(V,""));var H="";K&&K.getId()&&(H=K.getId()||"");K&&K.getXtags()&&(K=K.getXtags(),K=K.replace(V,""),H=H.concat(";"+K));this.G.Tr(R?D:"",R?H:"",f)};
g.w.sJ=function(K,R){K=(K||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");K.length>0&&this.G.sJ(K,R)};g.Fk("captions",FGE);})(_yt_player);
