(function(g){var window=this;'use strict';var ef_=function(K){K.publish("autonavvisibility")},Kr$=function(K,R){K.lD("onAutonavCoundownStarted",R)},RXW=function(K){return K.isBackground()&&K.qF()},fSB=function(K){var R,f,V;
return K==null?void 0:(R=K.playerOverlays)==null?void 0:(f=R.playerOverlayRenderer)==null?void 0:(V=f.autoplay)==null?void 0:V.playerOverlayAutoplayRenderer},HB=function(K){var R=K.C(),f=R.J;
g.Y.call(this,{V:"a",D:"ytp-autonav-suggestion-card",L:{href:"{{url}}",target:f?R.EF:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{V:"div",Me:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],L:{style:"{{background}}"},S:[{V:"div",L:{"aria-label":"{{timestamp}}"},Me:["ytp-autonav-timestamp"],Q0:"{{duration}}"},{V:"div",Me:["ytp-autonav-live-stamp"],Q0:"En directo"},
{V:"div",Me:["ytp-autonav-upcoming-stamp"],Q0:"Pr\u00f3ximamente"},{V:"div",D:"ytp-autonav-list-overlay",S:[{V:"div",D:"ytp-autonav-mix-text",Q0:"Mix"},{V:"div",D:"ytp-autonav-mix-icon"}]}]},{V:"div",Me:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Q0:"{{title}}"},{V:"div",Me:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Q0:"{{author}}"},{V:"div",Me:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Q0:"{{views_and_publish_time}}"}]});this.G=
K;this.suggestion=null;this.U=f;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},$9=function(K,R){R=R===void 0?!1:R;
g.Y.call(this,{V:"div",D:"ytp-autonav-endscreen-countdown-overlay"});var f=this;this.T=R;this.cancelCommand=this.B=void 0;this.X=0;this.container=new g.Y({V:"div",D:"ytp-autonav-endscreen-countdown-container"});g.q(this,this.container);this.container.V0(this.element);R=K.C();var V=R.J;this.G=K;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.j(K,"videodatachange",this.onVideoDataChange);this.U=new g.Y({V:"div",D:"ytp-autonav-endscreen-upnext-container",L:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{V:"div",D:"ytp-autonav-endscreen-upnext-header"},{V:"div",D:"ytp-autonav-endscreen-upnext-alternative-header",Q0:"{{autoplayAlternativeHeader}}"},{V:"a",D:"ytp-autonav-endscreen-link-container",L:{href:"{{url}}",target:V?R.EF:""},S:[{V:"div",D:"ytp-autonav-endscreen-upnext-thumbnail",L:{style:"{{background}}"},S:[{V:"div",L:{"aria-label":"{{timestamp}}"},Me:["ytp-autonav-timestamp"],
Q0:"{{duration}}"},{V:"div",Me:["ytp-autonav-live-stamp"],Q0:"En directo"},{V:"div",Me:["ytp-autonav-upcoming-stamp"],Q0:"Pr\u00f3ximamente"}]},{V:"div",D:"ytp-autonav-endscreen-video-info",S:[{V:"div",D:"ytp-autonav-endscreen-premium-badge"},{V:"div",D:"ytp-autonav-endscreen-upnext-title",Q0:"{{title}}"},{V:"div",D:"ytp-autonav-endscreen-upnext-author",Q0:"{{author}}"},{V:"div",D:"ytp-autonav-view-and-date",Q0:"{{views_and_publish_time}}"},{V:"div",D:"ytp-autonav-author-and-view",Q0:"{{author_and_views}}"}]}]}]});
g.q(this,this.U);this.U.V0(this.container.element);V||this.j(this.U.IY("ytp-autonav-endscreen-link-container"),"click",this.N8);this.G.createClientVe(this.container.element,this,115127);this.G.createClientVe(this.U.IY("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.Y({V:"div",D:"ytp-autonav-overlay"});g.q(this,this.overlay);this.overlay.V0(this.container.element);this.K=new g.Y({V:"div",D:"ytp-autonav-endscreen-button-container"});g.q(this,this.K);this.K.V0(this.container.element);
this.cancelButton=new g.Y({V:"button",Me:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],L:{"aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},Q0:"Cancelar"});g.q(this,this.cancelButton);this.cancelButton.V0(this.K.element);this.cancelButton.listen("click",this.GM,this);this.G.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.Y({V:"a",Me:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
"ytp-autonav-endscreen-upnext-button-rounded"],L:{href:"{{url}}",role:"button","aria-label":"Reproducir siguiente v\u00eddeo"},Q0:"Ver ahora"});g.q(this,this.playButton);this.playButton.V0(this.K.element);this.playButton.listen("click",this.N8,this);this.G.createServerVe(this.playButton.element,this.playButton,!0);(R=this.G.getVideoData())&&VFu(this,R);this.J=new g.CW(function(){DRT(f)},500);
g.q(this,this.J);this.Dt();this.j(K,"autonavvisibility",this.Dt);this.G.Y("web_autonav_color_transition")&&(this.j(K,"autonavchange",this.eF),this.j(K,"onAutonavCoundownStarted",this.WB0))},lw=function(K){var R=K.G.OT(!0,K.G.isFullscreen());
g.yb(K.container.element,"ytp-autonav-endscreen-small-mode",K.C7(R));g.yb(K.container.element,"ytp-autonav-endscreen-is-premium",!!K.suggestion&&!!K.suggestion.AmQ);g.yb(K.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!K.G.EO());g.yb(K.G.getRootNode(),"countdown-running",K.Iv());g.yb(K.container.element,"ytp-player-content",K.G.EO());g.Ds(K.overlay.element,{width:R.width+"px"});if(!K.Iv()){K.G.EO()?HVE(K,Math.round($R_(K)/1E3)):HVE(K);R=!!K.suggestion&&!!K.suggestion.T9;var f=K.G.EO()||
!R;g.yb(K.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!f&&R);g.yb(K.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",f&&!R);K.K.dn(K.G.EO());g.yb(K.element,"ytp-enable-w2w-color-transitions",lS_(K))}},DRT=function(K){var R=$R_(K),f=Math,V=f.min;
var D=K.X?Date.now()-K.X:0;f=V.call(f,D,R);HVE(K,Math.ceil((R-f)/1E3));R-f<=500&&K.Iv()?K.select(!0):K.Iv()&&K.J.start()},$R_=function(K){if(K.G.isFullscreen()){var R;
K=(R=K.G.getVideoData())==null?void 0:R.kL;return K===-1||K===void 0?8E3:K}return K.G.cZ()>=0?K.G.cZ():g.mz(K.G.C().experiments,"autoplay_time")||1E4},VFu=function(K,R){R=R.getWatchNextResponse();
var f,V;R=(f=fSB(R))==null?void 0:(V=f.nextButton)==null?void 0:V.buttonRenderer;K.B=R==null?void 0:R.navigationEndpoint;f=R==null?void 0:R.trackingParams;K.playButton&&f&&K.G.setTrackingParams(K.playButton.element,f)},lS_=function(K){var R;
return!((R=K.G.getVideoData())==null||!R.watchToWatchTransitionRenderer)},HVE=function(K,R){R=R===void 0?-1:R;
K=K.U.IY("ytp-autonav-endscreen-upnext-header");g.Ba(K);if(R>=0){R=String(R);var f="A continuaci\u00f3n en $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],V="A continuaci\u00f3n en $SECONDS".indexOf(f);if(V>=0){K.appendChild(g.AB("A continuaci\u00f3n en $SECONDS".slice(0,V)));var D=g.tB("span");g.$w(D,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Pa(D,R);K.appendChild(D);K.appendChild(g.AB("A continuaci\u00f3n en $SECONDS".slice(V+f.length)));return}}g.Pa(K,"Siguiente")},da=function(K,R){g.Y.call(this,
{V:"div",
Me:["html5-endscreen","ytp-player-content",R||"base-endscreen"]});this.created=!1;this.player=K},F2=function(K){g.Y.call(this,{V:"div",
Me:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},S:[{V:"div",D:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{V:"span",D:"ytp-upnext-top",S:[{V:"span",D:"ytp-upnext-header",Q0:"Siguiente"},{V:"span",D:"ytp-upnext-title",Q0:"{{title}}"},{V:"span",D:"ytp-upnext-author",Q0:"{{author}}"}]},{V:"a",D:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Reproducir siguiente v\u00eddeo"},S:[{V:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},S:[{V:"circle",D:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{V:"circle",D:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{V:"path",D:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{V:"span",D:"ytp-upnext-bottom",S:[{V:"span",D:"ytp-upnext-cancel"},{V:"span",D:"ytp-upnext-paused",
Q0:"La reproducci\u00f3n autom\u00e1tica est\u00e1 en pausa"}]}]});this.api=K;this.cancelButton=null;this.B=this.IY("ytp-svg-autoplay-ring");this.X=this.notification=this.U=this.suggestion=null;this.J=new g.CW(this.BH,5E3,this);this.K=0;var R=this.IY("ytp-upnext-cancel");this.cancelButton=new g.Y({V:"button",Me:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},Q0:"Cancelar"});g.q(this,this.cancelButton);this.cancelButton.listen("click",
this.f2,this);this.cancelButton.V0(R);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.q(this,this.J);this.api.createClientVe(this.element,this,18788);R=this.IY("ytp-upnext-autoplay-icon");this.j(R,"click",this.Yk);this.api.createClientVe(R,this,115130);this.k6();this.j(K,"autonavvisibility",this.k6);this.j(K,"mdxnowautoplaying",this.CMD);this.j(K,"mdxautoplaycanceled",this.lkW);g.yb(this.element,"ytp-upnext-mobile",this.api.C().K)},dRH=function(K,R){if(R)return R;
if(K.api.isFullscreen()){var f;K=(f=K.api.getVideoData())==null?void 0:f.kL;return K===-1||K===void 0?8E3:K}return K.api.cZ()>=0?K.api.cZ():g.mz(K.api.C().experiments,"autoplay_time")||1E4},Fri=function(K,R){R=dRH(K,R);
var f=Math,V=f.min;var D=(0,g.N7)()-K.K;f=V.call(f,D,R);R=R===0?1:Math.min(f/R,1);K.B.setAttribute("stroke-dashoffset",""+-211*(R+1));R>=1&&K.Iv()&&K.api.getPresentingPlayerType()!==3?K.select(!0):K.Iv()&&K.U.start()},cB=function(K){da.call(this,K,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.Y({V:"div",D:"ytp-suggestion-panel",S:[{V:"div",Me:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Q0:"M\u00e1s v\u00eddeos"}]});this.N=new g.Y({V:"div",D:"ytp-suggestions-container"});this.videos=[];this.X=null;this.B=this.T=!1;this.K=new $9(this.player);g.q(this,this.K);this.K.V0(this.element);K.getVideoData().bd?this.U=this.K:(this.U=new F2(K),g.nl(this.player,this.U.element,4),g.q(this,this.U));this.overlay=new g.Y({V:"div",
D:"ytp-autonav-overlay-cancelled-state"});g.q(this,this.overlay);this.overlay.V0(this.element);this.J=new g.de(this);g.q(this,this.J);g.q(this,this.table);this.table.V0(this.element);this.table.show();g.q(this,this.N);this.N.V0(this.table.element);this.hide()},ra=function(K){var R=K.EO();
R!==K.B&&(K.B=R,ef_(K.player),K.B?(K.K!==K.U&&K.K.hide(),K.table.hide()):(K.K!==K.U&&K.K.show(),K.table.show()))},cIH=function(K){da.call(this,K,"videowall-endscreen");
var R=this;this.G=K;this.stills=[];this.X=this.videoData=null;this.J=this.T=!1;this.N=null;g.dy(this.element,"modern-videowall-endscreen");this.K=new g.de(this);g.q(this,this.K);this.B=new g.CW(function(){g.dy(R.element,"ytp-show-tiles")},0);
g.q(this,this.B);this.table=new g.Hv({V:"div",D:"ytp-modern-endscreen-content"});g.q(this,this.table);this.table.V0(this.element);K.getVideoData().bd?this.U=new $9(K,!0):this.U=new F2(K);g.q(this,this.U);g.nl(this.player,this.U.element,4);K.createClientVe(this.element,this,158789);this.hide()},y6=function(K){return g.IC(K.player)&&K.J9()&&!K.X},hj=function(K){var R=K.EO();
R!==K.T&&(K.T=R,ef_(K.player))},rIB=function(K){da.call(this,K,"subscribecard-endscreen");
this.U=new g.Y({V:"div",D:"ytp-subscribe-card",S:[{V:"img",D:"ytp-author-image",L:{src:"{{profilePicture}}"}},{V:"div",D:"ytp-subscribe-card-right",S:[{V:"div",D:"ytp-author-name",Q0:"{{author}}"},{V:"div",D:"html5-subscribe-button-container"}]}]});g.q(this,this.U);this.U.V0(this.element);var R=K.getVideoData();this.subscribeButton=new g.bY("Suscribirme",null,"Anular suscripci\u00f3n",null,!0,!1,R.M$,R.subscribed,"trailer-endscreen",null,K,!1);g.q(this,this.subscribeButton);this.subscribeButton.V0(this.U.IY("html5-subscribe-button-container"));
this.j(K,"videodatachange",this.T2);this.T2();this.hide()},oJ=function(K){var R=K.C(),f=g.Du||g.Bg?{style:"will-change: opacity"}:void 0,V=R.J,D=["ytp-videowall-still"];
R.K&&D.push("ytp-videowall-show-text");g.Y.call(this,{V:"a",Me:D,L:{href:"{{url}}",target:V?R.EF:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{V:"div",D:"ytp-videowall-still-image",L:{style:"{{background}}"}},{V:"span",D:"ytp-videowall-still-info",L:{"aria-hidden":"true"},S:[{V:"span",D:"ytp-videowall-still-info-bg",S:[{V:"span",D:"ytp-videowall-still-info-content",L:f,S:[{V:"span",D:"ytp-videowall-still-info-title",Q0:"{{title}}"},
{V:"span",D:"ytp-videowall-still-info-author",Q0:"{{author_and_views}}"},{V:"span",D:"ytp-videowall-still-info-live",Q0:"En directo"},{V:"span",D:"ytp-videowall-still-info-duration",Q0:"{{duration}}"}]}]}]},{V:"span",Me:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},S:[{V:"span",D:"ytp-videowall-still-listlabel-icon"},"Lista de reproducci\u00f3n",{V:"span",D:"ytp-videowall-still-listlabel-length",S:[" (",{V:"span",Q0:"{{playlist_length}}"},")"]}]},
{V:"span",Me:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},S:[{V:"span",D:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{V:"span",D:"ytp-videowall-still-listlabel-length",Q0:" (50+)"}]}]});this.suggestion=null;this.K=V;this.api=K;this.U=new g.de(this);g.q(this,this.U);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.U.j(K,"videodatachange",this.onVideoDataChange);K.createServerVe(this.element,this);this.onVideoDataChange()},
S2=function(K){da.call(this,K,"videowall-endscreen");
var R=this;this.G=K;this.X=0;this.stills=[];this.J=this.videoData=null;this.B=this.N=!1;this.Z=null;this.K=new g.de(this);g.q(this,this.K);this.T=new g.CW(function(){g.dy(R.element,"ytp-show-tiles")},0);
g.q(this,this.T);var f=new g.Y({V:"button",Me:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Anterior"},S:[g.oh()]});g.q(this,f);f.V0(this.element);f.listen("click",this.L2,this);this.table=new g.Hv({V:"div",D:"ytp-endscreen-content"});g.q(this,this.table);this.table.V0(this.element);f=new g.Y({V:"button",Me:["ytp-button","ytp-endscreen-next"],L:{"aria-label":"Siguiente"},S:[g.SD()]});g.q(this,f);f.V0(this.element);f.listen("click",this.jF,this);K.getVideoData().bd?this.U=new $9(K,!0):this.U=
new F2(K);g.q(this,this.U);g.nl(this.player,this.U.element,4);K.createClientVe(this.element,this,158789);this.hide()},iw=function(K){return g.IC(K.player)&&K.J9()&&!K.J},vB=function(K){var R=K.EO();
R!==K.N&&(K.N=R,ef_(K.player))},yIW=function(K,R){g.Y.call(this,{V:"button",
Me:["ytp-watch-on-youtube-button","ytp-button"],Q0:"{{content}}"});this.G=K;this.buttonType=this.buttonType=R;this.jx();this.buttonType===2&&g.dy(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.jx);this.dn(!0)},LF=function(K){da.call(this,K,"watch-again-on-youtube-endscreen");
this.watchButton=new yIW(K,1);g.q(this,this.watchButton);this.watchButton.V0(this.element);g.jHz(K)&&(this.U=new g.m8(K),g.q(this,this.U),this.K=new g.Y({V:"div",Me:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],L:{tabIndex:"-1"},S:[this.U]}),g.q(this,this.K),this.U.V0(this.K.element),this.K.V0(this.element));K.createClientVe(this.element,this,156914);this.hide()},iVV=function(K){g.cz.call(this,K);
var R=this;this.endScreen=null;this.U=this.K=this.X=!1;this.listeners=new g.de(this);g.q(this,this.listeners);var f=K.C();K.isEmbedsShortsMode()?this.endScreen=new LF(K):hXS(K)?(this.X=!0,oTH(this),this.U?this.endScreen=new cB(K):f.Y("delhi_modern_endscreen")?this.endScreen=new cIH(K):this.endScreen=new S2(K)):f.WB?this.endScreen=new rIB(K):this.endScreen=new da(K);g.q(this,this.endScreen);g.nl(K,this.endScreen.element,4);SsT(this);this.listeners.j(K,"videodatachange",this.onVideoDataChange,this);
this.listeners.j(K,g.gI("endscreen"),function(V){R.onCueRangeEnter(V)});
this.listeners.j(K,g.OK("endscreen"),function(V){R.onCueRangeExit(V)})},oTH=function(K){var R=K.player.getVideoData();
if(!R||K.U===R.xN&&K.K===R.bd)return!1;K.U=R.xN;K.K=R.bd;return!0},hXS=function(K){K=K.C();
return K.aQ&&!K.WB&&!K.disableOrganicUi},SsT=function(K){K.player.BV("endscreen");
var R=K.player.getVideoData();R=new g.nQ(Math.max((R.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var f=new g.nQ(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});K.player.PV([R,f])};
g.Wm.prototype.cZ=g.O5(8,function(){return this.app.cZ()});
g.h6.prototype.cZ=g.O5(7,function(){return this.getVideoData().IN});
g.aC.prototype.ZH=g.O5(6,function(K){this.Vl().ZH(K)});
g.I$.prototype.ZH=g.O5(5,function(K){this.r_!==K&&(this.r_=K,this.M9())});
g.x(HB,g.Y);HB.prototype.select=function(){this.G.V4(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.rG||void 0)&&this.G.logClick(this.element)};
HB.prototype.onClick=function(K){g.FK(K,this.G,this.U,this.suggestion.sessionData||void 0)&&this.select()};
HB.prototype.onKeyPress=function(K){switch(K.keyCode){case 13:case 32:K.defaultPrevented||(this.select(),K.preventDefault())}};g.x($9,g.Y);g.w=$9.prototype;g.w.C5=function(K){this.suggestion!==K&&(this.suggestion=K,g.sM(this.U,K),this.playButton.updateValue("url",this.suggestion.mq()),lw(this))};
g.w.Iv=function(){return this.X>0};
g.w.kX=function(){this.Iv()||(this.X=Date.now(),DRT(this),Kr$(this.G,$R_(this)),g.yb(this.G.getRootNode(),"countdown-running",this.Iv()))};
g.w.vM=function(){this.Dg();DRT(this);var K=this.U.IY("ytp-autonav-endscreen-upnext-header");K&&g.Pa(K,"Siguiente")};
g.w.Dg=function(){this.Iv()&&(this.J.stop(),this.X=0)};
g.w.select=function(K){this.G.nextVideo(!1,K===void 0?!1:K);this.Dg()};
g.w.N8=function(K){g.FK(K,this.G)&&(K.currentTarget===this.playButton.element?this.G.logClick(this.playButton.element):K.currentTarget===this.U.IY("ytp-autonav-endscreen-link-container")&&(K=this.U.IY("ytp-autonav-endscreen-link-container"),this.G.logVisibility(K,!0),this.G.logClick(K)),this.B?(this.G.lD("innertubeCommand",this.B),this.Dg()):this.select())};
g.w.GM=function(){this.G.logClick(this.cancelButton.element);g.Zk(this.G,!0);this.cancelCommand&&this.G.lD("innertubeCommand",this.cancelCommand)};
g.w.onVideoDataChange=function(K,R){VFu(this,R);K=R.getWatchNextResponse();var f,V;K=(f=fSB(K))==null?void 0:(V=f.cancelButton)==null?void 0:V.buttonRenderer;this.cancelCommand=K==null?void 0:K.command};
g.w.WB0=function(K){if(lS_(this)){var R=this.G.getVideoData().watchToWatchTransitionRenderer,f=R==null?void 0:R.fromColorPaletteDark;R=R==null?void 0:R.toColorPaletteDark;if(f&&R){var V=this.element;V.style.setProperty("--w2w-start-background-color",g.TE(f.surgeColor));V.style.setProperty("--w2w-start-primary-text-color",g.TE(f.primaryTitleColor));V.style.setProperty("--w2w-start-secondary-text-color",g.TE(f.secondaryTitleColor));V.style.setProperty("--w2w-end-background-color",g.TE(R.surgeColor));
V.style.setProperty("--w2w-end-primary-text-color",g.TE(R.primaryTitleColor));V.style.setProperty("--w2w-end-secondary-text-color",g.TE(R.secondaryTitleColor));V.style.setProperty("--w2w-animation-duration",K+"ms")}g.yb(this.element,"ytp-w2w-animate",!0)}};
g.w.eF=function(K){this.G.Y("web_autonav_color_transition")&&K!==2&&g.yb(this.element,"ytp-w2w-animate",!1)};
g.w.Dt=function(){var K=this.G.EO();this.T&&this.EC!==K&&this.dn(K);lw(this);this.G.logVisibility(this.container.element,K);this.G.logVisibility(this.cancelButton.element,K);this.G.logVisibility(this.U.IY("ytp-autonav-endscreen-link-container"),K);this.G.logVisibility(this.playButton.element,K)};
g.w.C7=function(K){return K.width<400||K.height<459};g.x(da,g.Y);g.w=da.prototype;g.w.create=function(){this.created=!0};
g.w.destroy=function(){this.created=!1};
g.w.J9=function(){return!1};
g.w.EO=function(){return!1};
g.w.nx=function(){return!1};g.x(F2,g.Y);g.w=F2.prototype;g.w.BH=function(){this.notification&&(this.J.stop(),this.hs(this.X),this.X=null,this.notification.close(),this.notification=null)};
g.w.C5=function(K){this.suggestion=K;g.sM(this,K,"hqdefault.jpg")};
g.w.k6=function(){this.dn(this.api.EO());this.api.logVisibility(this.element,this.api.EO());this.api.logVisibility(this.IY("ytp-upnext-autoplay-icon"),this.api.EO());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.EO())};
g.w.nYY=function(){window.focus();this.BH()};
g.w.kX=function(K){var R=this;this.Iv()||(g.V1("a11y-announce","Siguiente "+this.suggestion.title),this.K=(0,g.N7)(),this.U=new g.CW(function(){Fri(R,K)},25),Fri(this,K),Kr$(this.api,dRH(this,K)));
g.c2(this.element,"ytp-upnext-autoplay-paused")};
g.w.hide=function(){g.Y.prototype.hide.call(this)};
g.w.Iv=function(){return!!this.U};
g.w.vM=function(){this.Dg();this.K=(0,g.N7)();Fri(this);g.dy(this.element,"ytp-upnext-autoplay-paused")};
g.w.Dg=function(){this.Iv()&&(this.U.dispose(),this.U=null)};
g.w.select=function(K){K=K===void 0?!1:K;if(this.api.C().Y("autonav_notifications")&&K&&window.Notification&&typeof document.hasFocus==="function"){var R=Notification.permission;R==="default"?Notification.requestPermission():R!=="granted"||document.hasFocus()||(this.BH(),this.notification=new Notification("Siguiente",{body:this.suggestion.title,icon:this.suggestion.AK()}),this.X=this.j(this.notification,"click",this.nYY),this.J.start())}this.Dg();this.api.nextVideo(!1,K)};
g.w.Yk=function(K){!g.Ta(this.cancelButton.element,K.target)&&g.FK(K,this.api)&&(this.api.EO()&&this.api.logClick(this.IY("ytp-upnext-autoplay-icon")),this.select())};
g.w.f2=function(){this.api.EO()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Zk(this.api,!0)};
g.w.CMD=function(K){this.api.getPresentingPlayerType();this.show();this.kX(K)};
g.w.lkW=function(){this.api.getPresentingPlayerType();this.Dg();this.hide()};
g.w.uD=function(){this.Dg();this.BH();g.Y.prototype.uD.call(this)};g.x(cB,da);g.w=cB.prototype;g.w.create=function(){da.prototype.create.call(this);this.J.j(this.player,"appresize",this.H6);this.J.j(this.player,"onVideoAreaChange",this.H6);this.J.j(this.player,"videodatachange",this.onVideoDataChange);this.J.j(this.player,"autonavchange",this.j5);this.J.j(this.player,"onAutonavCancelled",this.ol);this.onVideoDataChange()};
g.w.show=function(){da.prototype.show.call(this);(this.T||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.Zk(this.player,!1);g.IC(this.player)&&this.J9()&&!this.X?(ra(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||RXW(this.player.nP())&&this.player.Y("web_player_pip_logging_fix")?this.U.select(!0):this.U.kX():this.videoData.autonavState===3&&this.U.vM()):(g.Zk(this.player,!0),ra(this));this.H6()};
g.w.hide=function(){da.prototype.hide.call(this);this.U.vM();ra(this)};
g.w.H6=function(){var K=this.player.OT(!0,this.player.isFullscreen());ra(this);lw(this.K);g.yb(this.element,"ytp-autonav-cancelled-small-mode",this.C7(K));g.yb(this.element,"ytp-autonav-cancelled-tiny-mode",this.uY(K));g.yb(this.element,"ytp-autonav-cancelled-mini-mode",K.width<=400||K.height<=360);this.overlay&&g.Ds(this.overlay.element,{width:K.width+"px"});if(!this.B)for(K=0;K<this.videos.length;K++)g.yb(this.videos[K].element,"ytp-suggestion-card-with-margin",K%2===1)};
g.w.onVideoDataChange=function(){var K=this.player.getVideoData();if(this.videoData!==K&&K){this.videoData=K;K=this.videoData.suggestions;var R=g.lv(this.videoData);R&&(this.U.C5(R),this.U!==this.K&&this.K.C5(R));if(K&&K.length)for(R=0;R<vTT.length;++R){var f=vTT[R];if(K&&K[f]){this.videos[R]=new HB(this.player);var V=this.videos[R];f=K[f];V.suggestion!==f&&(V.suggestion=f,g.sM(V,f));g.q(this,this.videos[R]);this.videos[R].V0(this.N.element)}}this.H6()}};
g.w.j5=function(K){K===1?(this.T=!1,this.X=this.videoData.clientPlaybackNonce,this.U.Dg(),this.EC&&this.H6()):(this.T=!0,this.EO()&&(K===2?this.U.kX():K===3&&this.U.vM()))};
g.w.ol=function(K){K?this.j5(1):(this.X=null,this.T=!1)};
g.w.J9=function(){return this.videoData.autonavState!==1};
g.w.C7=function(K){return(K.width<910||K.height<459)&&!this.uY(K)&&!(K.width<=400||K.height<=360)};
g.w.uY=function(K){return K.width<800&&!(K.width<=400||K.height<=360)};
g.w.EO=function(){return this.EC&&g.IC(this.player)&&this.J9()&&!this.X};
var vTT=[1,3,2,4];g.x(cIH,da);g.w=cIH.prototype;g.w.create=function(){da.prototype.create.call(this);var K=this.player.getVideoData();K&&(this.videoData=K);this.UK();this.K.j(this.player,"appresize",this.UK);this.K.j(this.player,"onVideoAreaChange",this.UK);this.K.j(this.player,"videodatachange",this.onVideoDataChange);this.K.j(this.player,"autonavchange",this.fY);this.K.j(this.player,"onAutonavCancelled",this.TM);K=this.videoData.autonavState;K!==this.N&&this.fY(K);this.K.j(this.element,"transitionend",this.D4)};
g.w.destroy=function(){g.kc(this.K);g.Ls(this.stills);this.stills=[];da.prototype.destroy.call(this);g.c2(this.element,"ytp-show-tiles");this.B.stop();this.N=this.videoData.autonavState};
g.w.J9=function(){return this.videoData.autonavState!==1};
g.w.show=function(){var K=this.EC;da.prototype.show.call(this);g.c2(this.element,"ytp-show-tiles");this.player.C().K?g.Ke(this.B):this.B.start();(this.J||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.Zk(this.player,!1);y6(this)?(hj(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||RXW(this.player.nP())&&this.player.Y("web_player_pip_logging_fix")?this.U.select(!0):this.U.kX():this.videoData.autonavState===3&&this.U.vM()):(g.Zk(this.player,!0),hj(this));K!==this.EC&&
this.player.logVisibility(this.element,!0)};
g.w.hide=function(){var K=this.EC;da.prototype.hide.call(this);this.U.vM();hj(this);K!==this.EC&&this.player.logVisibility(this.element,!1)};
g.w.D4=function(K){K.target===this.element&&this.UK()};
g.w.UK=function(){var K,R,f,V;var D=((K=this.videoData)==null?0:(R=K.suggestions)==null?0:R.length)?(f=this.videoData)==null?void 0:f.suggestions:[(V=this.videoData)==null?void 0:g.lv(V)];if(D.length){R=this.G.OT(!0,this.G.isFullscreen());K=Math.floor((R.width-64+16)/(g.fT(R.width*.27,250,450)+16));R=Math.min(3,Math.floor((R.height-64)/((R.width-64-(K-1)*16)/K*.5625+70)));g.ry(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.dy(this.element,"ytp-modern-endscreen-limit-rows-"+R);g.yb(this.element,"ytp-modern-endscreen-single-item",K===1);g.yb(this.element,"ytp-modern-endscreen-row-0",R===0);K=this.table.element;K.ariaLive="polite";this.U.C5(g.lv(this.videoData));this.U instanceof $9&&lw(this.U);g.yb(this.element,"ytp-endscreen-takeover",y6(this));hj(this);R=0;K.ariaBusy="true";f=D.length;for(V=0;V<f;V++){var H=V%f,l=this.stills[V];l||(l=new g.CE(this.player),this.stills[V]=l,K.appendChild(l.element));g.e9B(l,D[H]);R++}this.stills.length=
R}};
g.w.onVideoDataChange=function(){var K=this.player.getVideoData(1);this.videoData!==K&&(K!=null&&g.lv(K)?(this.videoData=K,this.UK()):this.player.KQ("missg",{vid:(K==null?void 0:K.videoId)||"",cpn:(K==null?void 0:K.clientPlaybackNonce)||""}))};
g.w.nx=function(){return this.U.Iv()};
g.w.fY=function(K){K===1?(this.J=!1,this.X=this.videoData.clientPlaybackNonce,this.U.Dg(),this.EC&&this.UK()):(this.J=!0,this.EC&&y6(this)&&(K===2?this.U.kX():K===3&&this.U.vM()))};
g.w.TM=function(K){if(K){for(K=0;K<this.stills.length;K++)this.G.logVisibility(this.stills[K].element,!0);this.fY(1)}else this.X=null,this.J=!1;this.UK()};
g.w.EO=function(){return this.EC&&y6(this)};g.x(rIB,da);rIB.prototype.T2=function(){var K=this.player.getVideoData();this.U.update({profilePicture:K.profilePicture,author:K.author});this.subscribeButton.channelId=K.M$;var R=this.subscribeButton;K.subscribed?R.U():R.K()};g.x(oJ,g.Y);oJ.prototype.select=function(){this.api.V4(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.rG||void 0)&&this.api.logClick(this.element)};
oJ.prototype.onClick=function(K){if(g.kN(this.api.C())&&this.api.Y("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var R=this.suggestion.mq(),f={};g.kb(this.api,f);R=g.B9(R,f);g.cW(R,this.api,K)}else g.FK(K,this.api,this.K,this.suggestion.sessionData||void 0)&&this.select()};
oJ.prototype.onKeyPress=function(K){switch(K.keyCode){case 13:case 32:K.defaultPrevented||(this.select(),K.preventDefault())}};
oJ.prototype.onVideoDataChange=function(){var K=this.api.getVideoData(),R=this.api.C();this.K=K.nL?!1:R.J};g.x(S2,da);g.w=S2.prototype;g.w.create=function(){da.prototype.create.call(this);var K=this.player.getVideoData();K&&(this.videoData=K);this.AR();this.K.j(this.player,"appresize",this.AR);this.K.j(this.player,"onVideoAreaChange",this.AR);this.K.j(this.player,"videodatachange",this.onVideoDataChange);this.K.j(this.player,"autonavchange",this.YH);this.K.j(this.player,"onAutonavCancelled",this.Nm);K=this.videoData.autonavState;K!==this.Z&&this.YH(K);this.K.j(this.element,"transitionend",this.H3)};
g.w.destroy=function(){g.kc(this.K);g.Ls(this.stills);this.stills=[];da.prototype.destroy.call(this);g.c2(this.element,"ytp-show-tiles");this.T.stop();this.Z=this.videoData.autonavState};
g.w.J9=function(){return this.videoData.autonavState!==1};
g.w.show=function(){var K=this.EC;da.prototype.show.call(this);g.c2(this.element,"ytp-show-tiles");this.player.C().K?g.Ke(this.T):this.T.start();(this.B||this.J&&this.J!==this.videoData.clientPlaybackNonce)&&g.Zk(this.player,!1);iw(this)?(vB(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||RXW(this.player.nP())&&this.player.Y("web_player_pip_logging_fix")?this.U.select(!0):this.U.kX():this.videoData.autonavState===3&&this.U.vM()):(g.Zk(this.player,!0),vB(this));K!==this.EC&&
this.player.logVisibility(this.element,!0)};
g.w.hide=function(){var K=this.EC;da.prototype.hide.call(this);this.U.vM();vB(this);K!==this.EC&&this.player.logVisibility(this.element,!1)};
g.w.H3=function(K){K.target===this.element&&this.AR()};
g.w.AR=function(){var K,R,f,V;var D=((K=this.videoData)==null?0:(R=K.suggestions)==null?0:R.length)?(f=this.videoData)==null?void 0:f.suggestions:[(V=this.videoData)==null?void 0:g.lv(V)];if(D.length){g.dy(this.element,"ytp-endscreen-paginate");var H=this.G.OT(!0,this.G.isFullscreen());if(K=g.Ll(this.G))K=K.uH()?48:32,H.width-=K*2;var l=H.width/H.height;V=96/54;R=K=2;var F=Math.max(H.width/96,2),c=Math.max(H.height/54,2);f=D.length;var r=f*4;for(r-=4;r>0&&(K<F||R<c);){var y=K/2,h=R/2,S=K<=F-2&&r>=
h*4,v=R<=c-2&&r>=y*4;if((y+1)/h*V/l>l/(y/(h+1)*V)&&v)r-=y*4,R+=2;else if(S)r-=h*4,K+=2;else if(v)r-=y*4,R+=2;else break}V=!1;r>=12&&f*4-r<=6&&(R>=4||K>=4)&&(V=!0);r=K*96;F=R*54;l=r/F<l?H.height/F:H.width/r;l=Math.min(l,2);r=Math.floor(Math.min(H.width,r*l));F=Math.floor(Math.min(H.height,F*l));H=this.table.element;H.ariaLive="polite";g.SX(H,r,F);g.Ds(H,{marginLeft:r/-2+"px",marginTop:F/-2+"px"});this.U.C5(g.lv(this.videoData));this.U instanceof $9&&lw(this.U);g.yb(this.element,"ytp-endscreen-takeover",
iw(this));vB(this);r+=4;F+=4;l=0;H.ariaBusy="true";for(c=0;c<K;c++)for(y=0;y<R;y++)if(h=l,v=0,V&&c>=K-2&&y>=R-2?v=1:y%2===0&&c%2===0&&(y<2&&c<2?y===0&&c===0&&(v=2):v=2),h=g.VJ(h+this.X,f),v!==0){S=this.stills[l];S||(S=new oJ(this.player),this.stills[l]=S,H.appendChild(S.element));var L=Math.floor(F*y/R),E=Math.floor(r*c/K),Q=Math.floor(F*(y+v)/R)-L-4,J=Math.floor(r*(c+v)/K)-E-4;g.rB(S.element,E,L);g.SX(S.element,J,Q);g.Ds(S.element,"transitionDelay",(y+c)/20+"s");g.yb(S.element,"ytp-videowall-still-mini",
v===1);g.yb(S.element,"ytp-videowall-still-large",v>2);v=Math.max(J,Q);g.yb(S.element,"ytp-videowall-still-round-large",v>=256);g.yb(S.element,"ytp-videowall-still-round-medium",v>96&&v<256);g.yb(S.element,"ytp-videowall-still-round-small",v<=96);h=D[h];S.suggestion!==h&&(S.suggestion=h,v=S.api.C(),L=g.lp(S.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.sM(S,h,L),g.kN(v)&&!S.api.Y("web_player_log_click_before_generating_ve_conversion_params")&&(v=h.mq(),L={},g.hX(S.api,"addEmbedsConversionTrackingParams",
[L]),v=g.B9(v,L),S.updateValue("url",v)),(h=(h=h.sessionData)&&h.itct)&&S.api.setTrackingParams(S.element,h));l++}H.ariaBusy="false";g.yb(this.element,"ytp-endscreen-paginate",l<f);for(D=this.stills.length-1;D>=l;D--)K=this.stills[D],g.kU(K.element),g.v5(K);this.stills.length=l}};
g.w.onVideoDataChange=function(){var K=this.player.getVideoData(1);this.videoData!==K&&(K!=null&&g.lv(K)?(this.X=0,this.videoData=K,this.AR()):this.player.KQ("missg",{vid:(K==null?void 0:K.videoId)||"",cpn:(K==null?void 0:K.clientPlaybackNonce)||""}))};
g.w.jF=function(){this.X+=this.stills.length;this.AR()};
g.w.L2=function(){this.X-=this.stills.length;this.AR()};
g.w.nx=function(){return this.U.Iv()};
g.w.YH=function(K){K===1?(this.B=!1,this.J=this.videoData.clientPlaybackNonce,this.U.Dg(),this.EC&&this.AR()):(this.B=!0,this.EC&&iw(this)&&(K===2?this.U.kX():K===3&&this.U.vM()))};
g.w.Nm=function(K){if(K){for(K=0;K<this.stills.length;K++)this.G.logVisibility(this.stills[K].element,!0);this.YH(1)}else this.J=null,this.B=!1;this.AR()};
g.w.EO=function(){return this.EC&&iw(this)};g.x(yIW,g.Y);g.w=yIW.prototype;g.w.jx=function(){switch(this.buttonType){case 1:var K="Ver otra vez en YouTube";var R=156915;break;case 2:K="Seguir reproduciendo en YouTube";R=156942;break;default:K="Seguir reproduciendo en YouTube",R=156942}this.update({content:K});this.G.hasVe(this.element)&&this.G.destroyVe(this.element);this.G.createClientVe(this.element,this,R)};
g.w.onClick=function(K){this.G.Y("web_player_log_click_before_generating_ve_conversion_params")&&this.G.logClick(this.element);g.cW(this.getVideoUrl(),this.G,K);this.G.Y("web_player_log_click_before_generating_ve_conversion_params")||this.G.logClick(this.element)};
g.w.getVideoUrl=function(){var K=!0;switch(this.buttonType){case 1:K=!0;break;case 2:K=!1}K=this.G.getVideoUrl(K,!1,!1,!0);var R=this.G.C();if(g.kN(R)){var f={};g.kN(R)&&g.hX(this.G,"addEmbedsConversionTrackingParams",[f]);K=g.B9(K,f)}return K};
g.w.logVisibility=function(){this.G.logVisibility(this.element,this.EC&&this.EF)};
g.w.show=function(){g.Y.prototype.show.call(this);this.logVisibility()};
g.w.hide=function(){g.Y.prototype.hide.call(this);this.logVisibility()};
g.w.bM=function(K){g.Y.prototype.bM.call(this,K);this.logVisibility()};g.x(LF,da);LF.prototype.hasSuggestions=function(){var K;return(K=this.U)==null?void 0:K.hasSuggestions()};
LF.prototype.show=function(){if(this.player.getPlayerState()!==3){da.prototype.show.call(this);var K=this.K;if(K){var R=this.U.hasSuggestions();g.yb(this.element,"ytp-shorts-branded-ui",R);R?K.show():K.hide()}var f;(f=g.Ll(this.player))==null||f.ZH(!0);this.player.logVisibility(this.element,!0);this.watchButton.bM(!0)}};
LF.prototype.hide=function(){da.prototype.hide.call(this);var K;(K=g.Ll(this.player))==null||K.ZH(!1);this.player.logVisibility(this.element,!1);this.watchButton.bM(!1)};g.x(iVV,g.cz);g.w=iVV.prototype;g.w.ge=function(){var K=this.player.getVideoData(),R=K.mutedAutoplay&&(K.limitedPlaybackDurationInSeconds>0||K.endSeconds>0||K.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!R)return!0;var f;var V=!!((K==null?0:g.lv(K))||(K==null?0:(f=K.suggestions)==null?0:f.length));V=!hXS(this.player)||V;K=K.F1;f=this.player.eV();return V&&!K&&!f&&!R};
g.w.EO=function(){return this.endScreen.EO()};
g.w.sYr=function(){return this.EO()?this.endScreen.nx():!1};
g.w.uD=function(){this.player.BV("endscreen");g.cz.prototype.uD.call(this)};
g.w.load=function(){var K=this.player.getVideoData();var R=K.transitionEndpointAtEndOfStream;if(R&&R.videoId){var f=this.player.JV().KT.get("heartbeat"),V=g.lv(K);!V||R.videoId!==V.videoId||K.LS?(this.player.V4(R.videoId,void 0,void 0,!0,!0,R),f&&f.VX("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),K=!0):K=!1}else K=!1;K||(g.cz.prototype.load.call(this),this.endScreen.show())};
g.w.unload=function(){g.cz.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.w.onCueRangeEnter=function(K){this.ge()&&(this.endScreen.created||this.endScreen.create(),K.getId()==="load"&&this.load())};
g.w.onCueRangeExit=function(K){K.getId()==="load"&&this.loaded&&this.unload()};
g.w.onVideoDataChange=function(){SsT(this);this.X&&oTH(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.U?this.endScreen=new cB(this.player):this.endScreen=new S2(this.player),g.q(this,this.endScreen),g.nl(this.player,this.endScreen.element,4))};g.Fk("endscreen",iVV);})(_yt_player);
